#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_Reverse_Zombie

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"
#include "Altar_structs.hpp"


namespace SDK::Params
{

// Function ABP_Reverse_Zombie.ABP_Reverse_Zombie_C.ExecuteUbergraph_ABP_Reverse_Zombie
// 0x0188 (0x0188 - 0x0000)
struct ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4B95[0x4];                                     // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FCharacterLayerLinkTable               K2Node_MakeStruct_CharacterLayerLinkTable;         // 0x0008(0x0018)(NoDestructor)
	class UAnimInstance*                          CallFunc_GetLinkedAnimLayerInstanceByClass_ReturnValue; // 0x0020(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TMap<struct FGameplayTag, struct FCharacterLayerLinkTable> K2Node_MakeMap_Map;                                // 0x0028(0x0050)()
	struct FCharacterPropertyLinkTable            K2Node_MakeStruct_CharacterPropertyLinkTable;      // 0x0078(0x0018)(NoDestructor)
	class UAnimInstance*                          CallFunc_GetLinkedAnimLayerInstanceByClass_ReturnValue_1; // 0x0090(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FCharacterPropertyLinkTable            K2Node_MakeStruct_CharacterPropertyLinkTable_1;    // 0x0098(0x0018)(NoDestructor)
	class UAnimInstance*                          CallFunc_GetLinkedAnimLayerInstanceByClass_ReturnValue_2; // 0x00B0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UTABP_HitReact_Procedural_C*            K2Node_DynamicCast_AsTABP_Hit_React_Procedural;    // 0x00B8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x00C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4B96[0x7];                                     // 0x00C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimInstance*                          CallFunc_GetLinkedAnimLayerInstanceByClass_ReturnValue_3; // 0x00C8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UTABP_LookAt_C*                         K2Node_DynamicCast_AsTABP_Look_At;                 // 0x00D0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x00D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4B97[0x7];                                     // 0x00D9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimInstance*                          CallFunc_GetLinkedAnimLayerInstanceByClass_ReturnValue_4; // 0x00E0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UTABP_FacialPose_C*                     K2Node_DynamicCast_AsTABP_Facial_Pose;             // 0x00E8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x00F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4B98[0x7];                                     // 0x00F1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimInstance*                          CallFunc_GetLinkedAnimLayerInstanceByClass_ReturnValue_5; // 0x00F8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UTABP_FeetIK_LeaningBiped_C*            K2Node_DynamicCast_AsTABP_Feet_IK_Leaning_Biped;   // 0x0100(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x0108(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4B99[0x7];                                     // 0x0109(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimInstance*                          CallFunc_GetLinkedAnimLayerInstanceByClass_ReturnValue_6; // 0x0110(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UAnimInstance*                          CallFunc_GetLinkedAnimLayerInstanceByClass_ReturnValue_7; // 0x0118(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FCharacterPropertyLinkTable            K2Node_MakeStruct_CharacterPropertyLinkTable_2;    // 0x0120(0x0018)(NoDestructor)
	class UTABP_TurnInPlaceCreature_C*            K2Node_DynamicCast_AsTABP_Turn_in_Place_Creature;  // 0x0138(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_4;                     // 0x0140(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4B9A[0x7];                                     // 0x0141(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FCharacterPropertyLinkTable>    K2Node_MakeArray_Array;                            // 0x0148(0x0010)(ReferenceParm)
	class UAnimInstance*                          CallFunc_GetLinkedAnimLayerInstanceByClass_ReturnValue_8; // 0x0158(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UTABP_Creature_Biped_LowerAndUpperBody_C* K2Node_DynamicCast_AsTABP_Creature_Biped_Lower_and_Upper_Body; // 0x0160(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_5;                     // 0x0168(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4B9B[0x7];                                     // 0x0169(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimInstance*                          CallFunc_GetLinkedAnimLayerInstanceByClass_ReturnValue_9; // 0x0170(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UTABP_Blink_C*                          K2Node_DynamicCast_AsTABP_Blink;                   // 0x0178(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_6;                     // 0x0180(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie) == 0x000008, "Wrong alignment on ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie");
static_assert(sizeof(ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie) == 0x000188, "Wrong size on ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie");
static_assert(offsetof(ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie, EntryPoint) == 0x000000, "Member 'ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie::EntryPoint' has a wrong offset!");
static_assert(offsetof(ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie, K2Node_MakeStruct_CharacterLayerLinkTable) == 0x000008, "Member 'ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie::K2Node_MakeStruct_CharacterLayerLinkTable' has a wrong offset!");
static_assert(offsetof(ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie, CallFunc_GetLinkedAnimLayerInstanceByClass_ReturnValue) == 0x000020, "Member 'ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie::CallFunc_GetLinkedAnimLayerInstanceByClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie, K2Node_MakeMap_Map) == 0x000028, "Member 'ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie::K2Node_MakeMap_Map' has a wrong offset!");
static_assert(offsetof(ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie, K2Node_MakeStruct_CharacterPropertyLinkTable) == 0x000078, "Member 'ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie::K2Node_MakeStruct_CharacterPropertyLinkTable' has a wrong offset!");
static_assert(offsetof(ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie, CallFunc_GetLinkedAnimLayerInstanceByClass_ReturnValue_1) == 0x000090, "Member 'ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie::CallFunc_GetLinkedAnimLayerInstanceByClass_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie, K2Node_MakeStruct_CharacterPropertyLinkTable_1) == 0x000098, "Member 'ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie::K2Node_MakeStruct_CharacterPropertyLinkTable_1' has a wrong offset!");
static_assert(offsetof(ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie, CallFunc_GetLinkedAnimLayerInstanceByClass_ReturnValue_2) == 0x0000B0, "Member 'ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie::CallFunc_GetLinkedAnimLayerInstanceByClass_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie, K2Node_DynamicCast_AsTABP_Hit_React_Procedural) == 0x0000B8, "Member 'ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie::K2Node_DynamicCast_AsTABP_Hit_React_Procedural' has a wrong offset!");
static_assert(offsetof(ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie, K2Node_DynamicCast_bSuccess) == 0x0000C0, "Member 'ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie, CallFunc_GetLinkedAnimLayerInstanceByClass_ReturnValue_3) == 0x0000C8, "Member 'ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie::CallFunc_GetLinkedAnimLayerInstanceByClass_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie, K2Node_DynamicCast_AsTABP_Look_At) == 0x0000D0, "Member 'ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie::K2Node_DynamicCast_AsTABP_Look_At' has a wrong offset!");
static_assert(offsetof(ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie, K2Node_DynamicCast_bSuccess_1) == 0x0000D8, "Member 'ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie, CallFunc_GetLinkedAnimLayerInstanceByClass_ReturnValue_4) == 0x0000E0, "Member 'ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie::CallFunc_GetLinkedAnimLayerInstanceByClass_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie, K2Node_DynamicCast_AsTABP_Facial_Pose) == 0x0000E8, "Member 'ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie::K2Node_DynamicCast_AsTABP_Facial_Pose' has a wrong offset!");
static_assert(offsetof(ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie, K2Node_DynamicCast_bSuccess_2) == 0x0000F0, "Member 'ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie, CallFunc_GetLinkedAnimLayerInstanceByClass_ReturnValue_5) == 0x0000F8, "Member 'ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie::CallFunc_GetLinkedAnimLayerInstanceByClass_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie, K2Node_DynamicCast_AsTABP_Feet_IK_Leaning_Biped) == 0x000100, "Member 'ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie::K2Node_DynamicCast_AsTABP_Feet_IK_Leaning_Biped' has a wrong offset!");
static_assert(offsetof(ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie, K2Node_DynamicCast_bSuccess_3) == 0x000108, "Member 'ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie::K2Node_DynamicCast_bSuccess_3' has a wrong offset!");
static_assert(offsetof(ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie, CallFunc_GetLinkedAnimLayerInstanceByClass_ReturnValue_6) == 0x000110, "Member 'ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie::CallFunc_GetLinkedAnimLayerInstanceByClass_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie, CallFunc_GetLinkedAnimLayerInstanceByClass_ReturnValue_7) == 0x000118, "Member 'ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie::CallFunc_GetLinkedAnimLayerInstanceByClass_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie, K2Node_MakeStruct_CharacterPropertyLinkTable_2) == 0x000120, "Member 'ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie::K2Node_MakeStruct_CharacterPropertyLinkTable_2' has a wrong offset!");
static_assert(offsetof(ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie, K2Node_DynamicCast_AsTABP_Turn_in_Place_Creature) == 0x000138, "Member 'ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie::K2Node_DynamicCast_AsTABP_Turn_in_Place_Creature' has a wrong offset!");
static_assert(offsetof(ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie, K2Node_DynamicCast_bSuccess_4) == 0x000140, "Member 'ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie::K2Node_DynamicCast_bSuccess_4' has a wrong offset!");
static_assert(offsetof(ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie, K2Node_MakeArray_Array) == 0x000148, "Member 'ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie, CallFunc_GetLinkedAnimLayerInstanceByClass_ReturnValue_8) == 0x000158, "Member 'ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie::CallFunc_GetLinkedAnimLayerInstanceByClass_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie, K2Node_DynamicCast_AsTABP_Creature_Biped_Lower_and_Upper_Body) == 0x000160, "Member 'ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie::K2Node_DynamicCast_AsTABP_Creature_Biped_Lower_and_Upper_Body' has a wrong offset!");
static_assert(offsetof(ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie, K2Node_DynamicCast_bSuccess_5) == 0x000168, "Member 'ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie::K2Node_DynamicCast_bSuccess_5' has a wrong offset!");
static_assert(offsetof(ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie, CallFunc_GetLinkedAnimLayerInstanceByClass_ReturnValue_9) == 0x000170, "Member 'ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie::CallFunc_GetLinkedAnimLayerInstanceByClass_ReturnValue_9' has a wrong offset!");
static_assert(offsetof(ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie, K2Node_DynamicCast_AsTABP_Blink) == 0x000178, "Member 'ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie::K2Node_DynamicCast_AsTABP_Blink' has a wrong offset!");
static_assert(offsetof(ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie, K2Node_DynamicCast_bSuccess_6) == 0x000180, "Member 'ABP_Reverse_Zombie_C_ExecuteUbergraph_ABP_Reverse_Zombie::K2Node_DynamicCast_bSuccess_6' has a wrong offset!");

}

