#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ALI_LocomotionSwimming

#include "Basic.hpp"

#include "ALI_LocomotionSwimming_classes.hpp"
#include "ALI_LocomotionSwimming_parameters.hpp"


namespace SDK
{

// Function ALI_LocomotionSwimming.ALI_LocomotionSwimming_C.SwimmingLayer
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        Param_SwimmingLayer                                    (Parm, OutParm, NoDestructor)

void IALI_LocomotionSwimming_C::SwimmingLayer(struct FPoseLink* Param_SwimmingLayer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ALI_LocomotionSwimming_C", "SwimmingLayer");

	Params::ALI_LocomotionSwimming_C_SwimmingLayer Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_SwimmingLayer != nullptr)
		*Param_SwimmingLayer = std::move(Parms.Param_SwimmingLayer);
}

}

