#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ALI_LookAt

#include "Basic.hpp"

#include "ALI_LookAt_classes.hpp"
#include "ALI_LookAt_parameters.hpp"


namespace SDK
{

// Function ALI_LookAt.ALI_LookAt_C.LookAtLayer
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        AnimationPose                                          (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink                        Param_LookAtLayer                                      (Parm, OutParm, NoDestructor)

void IALI_LookAt_C::LookAtLayer(const struct FPoseLink& AnimationPose, struct FPoseLink* Param_LookAtLayer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ALI_LookAt_C", "LookAtLayer");

	Params::ALI_LookAt_C_LookAtLayer Parms{};

	Parms.AnimationPose = std::move(AnimationPose);

	UObject::ProcessEvent(Func, &Parms);

	if (Param_LookAtLayer != nullptr)
		*Param_LookAtLayer = std::move(Parms.Param_LookAtLayer);
}

}

