#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ALI_TorchPose

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass ALI_TorchPose.ALI_TorchPose_C
// 0x0000 (0x0028 - 0x0028)
class IALI_TorchPose_C final : public IAnimLayerInterface
{
public:
	void TorchLayer(const struct FPoseLink& InPose, struct FPoseLink* Param_TorchLayer);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ALI_TorchPose_C">();
	}
	static class IALI_TorchPose_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IALI_TorchPose_C>();
	}
};
static_assert(alignof(IALI_TorchPose_C) == 0x000008, "Wrong alignment on IALI_TorchPose_C");
static_assert(sizeof(IALI_TorchPose_C) == 0x000028, "Wrong size on IALI_TorchPose_C");

}

