#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ALI_Stagger

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass ALI_Stagger.ALI_Stagger_C
// 0x0000 (0x0028 - 0x0028)
class IALI_Stagger_C final : public IAnimLayerInterface
{
public:
	void StaggerLayer(const struct FPoseLink& InPose, struct FPoseLink* Param_StaggerLayer);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ALI_Stagger_C">();
	}
	static class IALI_Stagger_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IALI_Stagger_C>();
	}
};
static_assert(alignof(IALI_Stagger_C) == 0x000008, "Wrong alignment on IALI_Stagger_C");
static_assert(sizeof(IALI_Stagger_C) == 0x000028, "Wrong size on IALI_Stagger_C");

}

