#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ALI_FacialAnimation

#include "Basic.hpp"

#include "ALI_FacialAnimation_classes.hpp"
#include "ALI_FacialAnimation_parameters.hpp"


namespace SDK
{

// Function ALI_FacialAnimation.ALI_FacialAnimation_C.FacialAnimationLayer
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        InPose                                                 (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink                        Param_FacialAnimationLayer                             (Parm, OutParm, NoDestructor)

void IALI_FacialAnimation_C::FacialAnimationLayer(const struct FPoseLink& InPose, struct FPoseLink* Param_FacialAnimationLayer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ALI_FacialAnimation_C", "FacialAnimationLayer");

	Params::ALI_FacialAnimation_C_FacialAnimationLayer Parms{};

	Parms.InPose = std::move(InPose);

	UObject::ProcessEvent(Func, &Parms);

	if (Param_FacialAnimationLayer != nullptr)
		*Param_FacialAnimationLayer = std::move(Parms.Param_FacialAnimationLayer);
}

}

