#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ALI_CombatAttacking

#include "Basic.hpp"

#include "ALI_CombatAttacking_classes.hpp"
#include "ALI_CombatAttacking_parameters.hpp"


namespace SDK
{

// Function ALI_CombatAttacking.ALI_CombatAttacking_C.AttackingLayer
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        InPose                                                 (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink                        Param_AttackingLayer                                   (Parm, OutParm, NoDestructor)

void IALI_CombatAttacking_C::AttackingLayer(const struct FPoseLink& InPose, struct FPoseLink* Param_AttackingLayer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ALI_CombatAttacking_C", "AttackingLayer");

	Params::ALI_CombatAttacking_C_AttackingLayer Parms{};

	Parms.InPose = std::move(InPose);

	UObject::ProcessEvent(Func, &Parms);

	if (Param_AttackingLayer != nullptr)
		*Param_AttackingLayer = std::move(Parms.Param_AttackingLayer);
}

}

