#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ALI_LocomotionSneaking

#include "Basic.hpp"

#include "ALI_LocomotionSneaking_classes.hpp"
#include "ALI_LocomotionSneaking_parameters.hpp"


namespace SDK
{

// Function ALI_LocomotionSneaking.ALI_LocomotionSneaking_C.SneakingLayer
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        Param_SneakingLayer                                    (Parm, OutParm, NoDestructor)

void IALI_LocomotionSneaking_C::SneakingLayer(struct FPoseLink* Param_SneakingLayer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ALI_LocomotionSneaking_C", "SneakingLayer");

	Params::ALI_LocomotionSneaking_C_SneakingLayer Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_SneakingLayer != nullptr)
		*Param_SneakingLayer = std::move(Parms.Param_SneakingLayer);
}

}

