#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ALI_ConversationIdle

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass ALI_ConversationIdle.ALI_ConversationIdle_C
// 0x0000 (0x0028 - 0x0028)
class IALI_ConversationIdle_C final : public IAnimLayerInterface
{
public:
	void ConversationIdleLayer(const struct FPoseLink& InPose, struct FPoseLink* Param_ConversationIdleLayer);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ALI_ConversationIdle_C">();
	}
	static class IALI_ConversationIdle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IALI_ConversationIdle_C>();
	}
};
static_assert(alignof(IALI_ConversationIdle_C) == 0x000008, "Wrong alignment on IALI_ConversationIdle_C");
static_assert(sizeof(IALI_ConversationIdle_C) == 0x000028, "Wrong size on IALI_ConversationIdle_C");

}

