#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ALI_HorseRidingInAir

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass ALI_HorseRidingInAir.ALI_HorseRidingInAir_C
// 0x0000 (0x0028 - 0x0028)
class IALI_HorseRidingInAir_C final : public IAnimLayerInterface
{
public:
	void HorseRidingInAirLayer(const struct FPoseLink& InPose, struct FPoseLink* Param_HorseRidingInAirLayer);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ALI_HorseRidingInAir_C">();
	}
	static class IALI_HorseRidingInAir_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IALI_HorseRidingInAir_C>();
	}
};
static_assert(alignof(IALI_HorseRidingInAir_C) == 0x000008, "Wrong alignment on IALI_HorseRidingInAir_C");
static_assert(sizeof(IALI_HorseRidingInAir_C) == 0x000028, "Wrong size on IALI_HorseRidingInAir_C");

}

