#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ALI_EnhancedLocomotion

#include "Basic.hpp"

#include "ALI_EnhancedLocomotion_classes.hpp"
#include "ALI_EnhancedLocomotion_parameters.hpp"


namespace SDK
{

// Function ALI_EnhancedLocomotion.ALI_EnhancedLocomotion_C.EnhancedLocomotionLayer
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        InPose                                                 (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink                        Param_EnhancedLocomotionLayer                          (Parm, OutParm, NoDestructor)

void IALI_EnhancedLocomotion_C::EnhancedLocomotionLayer(const struct FPoseLink& InPose, struct FPoseLink* Param_EnhancedLocomotionLayer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ALI_EnhancedLocomotion_C", "EnhancedLocomotionLayer");

	Params::ALI_EnhancedLocomotion_C_EnhancedLocomotionLayer Parms{};

	Parms.InPose = std::move(InPose);

	UObject::ProcessEvent(Func, &Parms);

	if (Param_EnhancedLocomotionLayer != nullptr)
		*Param_EnhancedLocomotionLayer = std::move(Parms.Param_EnhancedLocomotionLayer);
}

}

