#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ARSmallColumn01

#include "Basic.hpp"

#include "Altar_classes.hpp"


namespace SDK
{

// VModdableBlueprintGeneratedClass BP_ARSmallColumn01.BP_ARSmallColumn01_C
// 0x0038 (0x0380 - 0x0348)
class ABP_ARSmallColumn01_C final : public AVStatic
{
public:
	class ULocalMapComponent*                     LocalMapComponent;                                 // 0x0348(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UObject*                                BPC_SpawnManager;                                  // 0x0350(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UObject*                                BPC_Stain_02;                                      // 0x0358(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UObject*                                BPC_Stain_01;                                      // 0x0360(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_arsmallcolumn01_Brick_A_01;                     // 0x0368(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_arsmallcolumn01_Column_A_01;                    // 0x0370(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   MeshComponent1;                                    // 0x0378(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ARSmallColumn01_C">();
	}
	static class ABP_ARSmallColumn01_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ARSmallColumn01_C>();
	}
};
static_assert(alignof(ABP_ARSmallColumn01_C) == 0x000008, "Wrong alignment on ABP_ARSmallColumn01_C");
static_assert(sizeof(ABP_ARSmallColumn01_C) == 0x000380, "Wrong size on ABP_ARSmallColumn01_C");
static_assert(offsetof(ABP_ARSmallColumn01_C, LocalMapComponent) == 0x000348, "Member 'ABP_ARSmallColumn01_C::LocalMapComponent' has a wrong offset!");
static_assert(offsetof(ABP_ARSmallColumn01_C, BPC_SpawnManager) == 0x000350, "Member 'ABP_ARSmallColumn01_C::BPC_SpawnManager' has a wrong offset!");
static_assert(offsetof(ABP_ARSmallColumn01_C, BPC_Stain_02) == 0x000358, "Member 'ABP_ARSmallColumn01_C::BPC_Stain_02' has a wrong offset!");
static_assert(offsetof(ABP_ARSmallColumn01_C, BPC_Stain_01) == 0x000360, "Member 'ABP_ARSmallColumn01_C::BPC_Stain_01' has a wrong offset!");
static_assert(offsetof(ABP_ARSmallColumn01_C, SM_arsmallcolumn01_Brick_A_01) == 0x000368, "Member 'ABP_ARSmallColumn01_C::SM_arsmallcolumn01_Brick_A_01' has a wrong offset!");
static_assert(offsetof(ABP_ARSmallColumn01_C, SM_arsmallcolumn01_Column_A_01) == 0x000370, "Member 'ABP_ARSmallColumn01_C::SM_arsmallcolumn01_Column_A_01' has a wrong offset!");
static_assert(offsetof(ABP_ARSmallColumn01_C, MeshComponent1) == 0x000378, "Member 'ABP_ARSmallColumn01_C::MeshComponent1' has a wrong offset!");

}

