#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ARWHallDeadEnd01

#include "Basic.hpp"

#include "Altar_classes.hpp"


namespace SDK
{

// VModdableBlueprintGeneratedClass BP_ARWHallDeadEnd01.BP_ARWHallDeadEnd01_C
// 0x00A8 (0x03F0 - 0x0348)
class ABP_ARWHallDeadEnd01_C final : public AVStatic
{
public:
	class ULocalMapComponent*                     LocalMapComponent;                                 // 0x0348(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UObject*                                BPC_WallLeaks_02;                                  // 0x0350(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UObject*                                BPC_WallLeaks_01;                                  // 0x0358(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UObject*                                BPC_WallStain_01;                                  // 0x0360(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_AyleidInt_BrokenStones_02;                      // 0x0368(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_AyleidInt_BrokenStones_01;                      // 0x0370(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UObject*                                BPC_SpawnManager;                                  // 0x0378(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UObject*                                BPC_Puddles_01;                                    // 0x0380(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDecalComponent*                        MIC_Decal_Puddle_9;                                // 0x0388(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDecalComponent*                        MIC_Decal_Puddle_08;                               // 0x0390(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Caves_GroundRocks_02_A15;                       // 0x0398(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Caves_GroundRocks_02_A10;                       // 0x03A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Caves_GroundRocks_02_A16;                       // 0x03A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_AyleidInt_Rubble_15;                            // 0x03B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Whall_Floor_F_02;                               // 0x03B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Whall_Column_D_07;                              // 0x03C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Whall_Column_C_07;                              // 0x03C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Whall_Column_B_17;                              // 0x03D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Whall_Column_A_09;                              // 0x03D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Whall_Wall_J_01;                                // 0x03E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   MeshComponent1;                                    // 0x03E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ARWHallDeadEnd01_C">();
	}
	static class ABP_ARWHallDeadEnd01_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ARWHallDeadEnd01_C>();
	}
};
static_assert(alignof(ABP_ARWHallDeadEnd01_C) == 0x000008, "Wrong alignment on ABP_ARWHallDeadEnd01_C");
static_assert(sizeof(ABP_ARWHallDeadEnd01_C) == 0x0003F0, "Wrong size on ABP_ARWHallDeadEnd01_C");
static_assert(offsetof(ABP_ARWHallDeadEnd01_C, LocalMapComponent) == 0x000348, "Member 'ABP_ARWHallDeadEnd01_C::LocalMapComponent' has a wrong offset!");
static_assert(offsetof(ABP_ARWHallDeadEnd01_C, BPC_WallLeaks_02) == 0x000350, "Member 'ABP_ARWHallDeadEnd01_C::BPC_WallLeaks_02' has a wrong offset!");
static_assert(offsetof(ABP_ARWHallDeadEnd01_C, BPC_WallLeaks_01) == 0x000358, "Member 'ABP_ARWHallDeadEnd01_C::BPC_WallLeaks_01' has a wrong offset!");
static_assert(offsetof(ABP_ARWHallDeadEnd01_C, BPC_WallStain_01) == 0x000360, "Member 'ABP_ARWHallDeadEnd01_C::BPC_WallStain_01' has a wrong offset!");
static_assert(offsetof(ABP_ARWHallDeadEnd01_C, SM_AyleidInt_BrokenStones_02) == 0x000368, "Member 'ABP_ARWHallDeadEnd01_C::SM_AyleidInt_BrokenStones_02' has a wrong offset!");
static_assert(offsetof(ABP_ARWHallDeadEnd01_C, SM_AyleidInt_BrokenStones_01) == 0x000370, "Member 'ABP_ARWHallDeadEnd01_C::SM_AyleidInt_BrokenStones_01' has a wrong offset!");
static_assert(offsetof(ABP_ARWHallDeadEnd01_C, BPC_SpawnManager) == 0x000378, "Member 'ABP_ARWHallDeadEnd01_C::BPC_SpawnManager' has a wrong offset!");
static_assert(offsetof(ABP_ARWHallDeadEnd01_C, BPC_Puddles_01) == 0x000380, "Member 'ABP_ARWHallDeadEnd01_C::BPC_Puddles_01' has a wrong offset!");
static_assert(offsetof(ABP_ARWHallDeadEnd01_C, MIC_Decal_Puddle_9) == 0x000388, "Member 'ABP_ARWHallDeadEnd01_C::MIC_Decal_Puddle_9' has a wrong offset!");
static_assert(offsetof(ABP_ARWHallDeadEnd01_C, MIC_Decal_Puddle_08) == 0x000390, "Member 'ABP_ARWHallDeadEnd01_C::MIC_Decal_Puddle_08' has a wrong offset!");
static_assert(offsetof(ABP_ARWHallDeadEnd01_C, SM_Caves_GroundRocks_02_A15) == 0x000398, "Member 'ABP_ARWHallDeadEnd01_C::SM_Caves_GroundRocks_02_A15' has a wrong offset!");
static_assert(offsetof(ABP_ARWHallDeadEnd01_C, SM_Caves_GroundRocks_02_A10) == 0x0003A0, "Member 'ABP_ARWHallDeadEnd01_C::SM_Caves_GroundRocks_02_A10' has a wrong offset!");
static_assert(offsetof(ABP_ARWHallDeadEnd01_C, SM_Caves_GroundRocks_02_A16) == 0x0003A8, "Member 'ABP_ARWHallDeadEnd01_C::SM_Caves_GroundRocks_02_A16' has a wrong offset!");
static_assert(offsetof(ABP_ARWHallDeadEnd01_C, SM_AyleidInt_Rubble_15) == 0x0003B0, "Member 'ABP_ARWHallDeadEnd01_C::SM_AyleidInt_Rubble_15' has a wrong offset!");
static_assert(offsetof(ABP_ARWHallDeadEnd01_C, SM_Whall_Floor_F_02) == 0x0003B8, "Member 'ABP_ARWHallDeadEnd01_C::SM_Whall_Floor_F_02' has a wrong offset!");
static_assert(offsetof(ABP_ARWHallDeadEnd01_C, SM_Whall_Column_D_07) == 0x0003C0, "Member 'ABP_ARWHallDeadEnd01_C::SM_Whall_Column_D_07' has a wrong offset!");
static_assert(offsetof(ABP_ARWHallDeadEnd01_C, SM_Whall_Column_C_07) == 0x0003C8, "Member 'ABP_ARWHallDeadEnd01_C::SM_Whall_Column_C_07' has a wrong offset!");
static_assert(offsetof(ABP_ARWHallDeadEnd01_C, SM_Whall_Column_B_17) == 0x0003D0, "Member 'ABP_ARWHallDeadEnd01_C::SM_Whall_Column_B_17' has a wrong offset!");
static_assert(offsetof(ABP_ARWHallDeadEnd01_C, SM_Whall_Column_A_09) == 0x0003D8, "Member 'ABP_ARWHallDeadEnd01_C::SM_Whall_Column_A_09' has a wrong offset!");
static_assert(offsetof(ABP_ARWHallDeadEnd01_C, SM_Whall_Wall_J_01) == 0x0003E0, "Member 'ABP_ARWHallDeadEnd01_C::SM_Whall_Wall_J_01' has a wrong offset!");
static_assert(offsetof(ABP_ARWHallDeadEnd01_C, MeshComponent1) == 0x0003E8, "Member 'ABP_ARWHallDeadEnd01_C::MeshComponent1' has a wrong offset!");

}

