#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ARBlueAmb600

#include "Basic.hpp"

#include "Altar_classes.hpp"


namespace SDK
{

// VModdableBlueprintGeneratedClass BP_ARBlueAmb600.BP_ARBlueAmb600_C
// 0x0000 (0x0358 - 0x0358)
class ABP_ARBlueAmb600_C final : public AVPointLight
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ARBlueAmb600_C">();
	}
	static class ABP_ARBlueAmb600_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ARBlueAmb600_C>();
	}
};
static_assert(alignof(ABP_ARBlueAmb600_C) == 0x000008, "Wrong alignment on ABP_ARBlueAmb600_C");
static_assert(sizeof(ABP_ARBlueAmb600_C) == 0x000358, "Wrong size on ABP_ARBlueAmb600_C");

}

