#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ARWallShelf01

#include "Basic.hpp"

#include "Altar_classes.hpp"


namespace SDK
{

// VModdableBlueprintGeneratedClass BP_ARWallShelf01.BP_ARWallShelf01_C
// 0x0018 (0x0360 - 0x0348)
class ABP_ARWallShelf01_C final : public AVStatic
{
public:
	class ULocalMapComponent*                     LocalMap;                                          // 0x0348(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_arwallshelf01;                                  // 0x0350(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   MeshComponent1;                                    // 0x0358(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ARWallShelf01_C">();
	}
	static class ABP_ARWallShelf01_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ARWallShelf01_C>();
	}
};
static_assert(alignof(ABP_ARWallShelf01_C) == 0x000008, "Wrong alignment on ABP_ARWallShelf01_C");
static_assert(sizeof(ABP_ARWallShelf01_C) == 0x000360, "Wrong size on ABP_ARWallShelf01_C");
static_assert(offsetof(ABP_ARWallShelf01_C, LocalMap) == 0x000348, "Member 'ABP_ARWallShelf01_C::LocalMap' has a wrong offset!");
static_assert(offsetof(ABP_ARWallShelf01_C, SM_arwallshelf01) == 0x000350, "Member 'ABP_ARWallShelf01_C::SM_arwallshelf01' has a wrong offset!");
static_assert(offsetof(ABP_ARWallShelf01_C, MeshComponent1) == 0x000358, "Member 'ABP_ARWallShelf01_C::MeshComponent1' has a wrong offset!");

}

