#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ARWHallTransNarrow02

#include "Basic.hpp"

#include "Altar_classes.hpp"


namespace SDK
{

// VModdableBlueprintGeneratedClass BP_ARWHallTransNarrow02.BP_ARWHallTransNarrow02_C
// 0x0088 (0x03D0 - 0x0348)
class ABP_ARWHallTransNarrow02_C final : public AVStatic
{
public:
	class ULocalMapComponent*                     LocalMapComponent;                                 // 0x0348(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UObject*                                VEditorPortalBox;                                  // 0x0350(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Whall_Column_B_26;                              // 0x0358(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Whall_Wall_C_06;                                // 0x0360(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Whall_Column_D_13;                              // 0x0368(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Whall_Column_A_18;                              // 0x0370(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Whall_Column_C_13;                              // 0x0378(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Whall_Wall_A_07;                                // 0x0380(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Whall_Floor_G_02;                               // 0x0388(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Whall_Column_E_03;                              // 0x0390(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Whall_Column_F_02;                              // 0x0398(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Whall_Arch_A_02;                                // 0x03A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Whall_Wall_P_02;                                // 0x03A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Whall_Wall_D_03;                                // 0x03B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Whall_Floor_I_01;                               // 0x03B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Whall_Wall_B_12;                                // 0x03C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   MeshComponent1;                                    // 0x03C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ARWHallTransNarrow02_C">();
	}
	static class ABP_ARWHallTransNarrow02_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ARWHallTransNarrow02_C>();
	}
};
static_assert(alignof(ABP_ARWHallTransNarrow02_C) == 0x000008, "Wrong alignment on ABP_ARWHallTransNarrow02_C");
static_assert(sizeof(ABP_ARWHallTransNarrow02_C) == 0x0003D0, "Wrong size on ABP_ARWHallTransNarrow02_C");
static_assert(offsetof(ABP_ARWHallTransNarrow02_C, LocalMapComponent) == 0x000348, "Member 'ABP_ARWHallTransNarrow02_C::LocalMapComponent' has a wrong offset!");
static_assert(offsetof(ABP_ARWHallTransNarrow02_C, VEditorPortalBox) == 0x000350, "Member 'ABP_ARWHallTransNarrow02_C::VEditorPortalBox' has a wrong offset!");
static_assert(offsetof(ABP_ARWHallTransNarrow02_C, SM_Whall_Column_B_26) == 0x000358, "Member 'ABP_ARWHallTransNarrow02_C::SM_Whall_Column_B_26' has a wrong offset!");
static_assert(offsetof(ABP_ARWHallTransNarrow02_C, SM_Whall_Wall_C_06) == 0x000360, "Member 'ABP_ARWHallTransNarrow02_C::SM_Whall_Wall_C_06' has a wrong offset!");
static_assert(offsetof(ABP_ARWHallTransNarrow02_C, SM_Whall_Column_D_13) == 0x000368, "Member 'ABP_ARWHallTransNarrow02_C::SM_Whall_Column_D_13' has a wrong offset!");
static_assert(offsetof(ABP_ARWHallTransNarrow02_C, SM_Whall_Column_A_18) == 0x000370, "Member 'ABP_ARWHallTransNarrow02_C::SM_Whall_Column_A_18' has a wrong offset!");
static_assert(offsetof(ABP_ARWHallTransNarrow02_C, SM_Whall_Column_C_13) == 0x000378, "Member 'ABP_ARWHallTransNarrow02_C::SM_Whall_Column_C_13' has a wrong offset!");
static_assert(offsetof(ABP_ARWHallTransNarrow02_C, SM_Whall_Wall_A_07) == 0x000380, "Member 'ABP_ARWHallTransNarrow02_C::SM_Whall_Wall_A_07' has a wrong offset!");
static_assert(offsetof(ABP_ARWHallTransNarrow02_C, SM_Whall_Floor_G_02) == 0x000388, "Member 'ABP_ARWHallTransNarrow02_C::SM_Whall_Floor_G_02' has a wrong offset!");
static_assert(offsetof(ABP_ARWHallTransNarrow02_C, SM_Whall_Column_E_03) == 0x000390, "Member 'ABP_ARWHallTransNarrow02_C::SM_Whall_Column_E_03' has a wrong offset!");
static_assert(offsetof(ABP_ARWHallTransNarrow02_C, SM_Whall_Column_F_02) == 0x000398, "Member 'ABP_ARWHallTransNarrow02_C::SM_Whall_Column_F_02' has a wrong offset!");
static_assert(offsetof(ABP_ARWHallTransNarrow02_C, SM_Whall_Arch_A_02) == 0x0003A0, "Member 'ABP_ARWHallTransNarrow02_C::SM_Whall_Arch_A_02' has a wrong offset!");
static_assert(offsetof(ABP_ARWHallTransNarrow02_C, SM_Whall_Wall_P_02) == 0x0003A8, "Member 'ABP_ARWHallTransNarrow02_C::SM_Whall_Wall_P_02' has a wrong offset!");
static_assert(offsetof(ABP_ARWHallTransNarrow02_C, SM_Whall_Wall_D_03) == 0x0003B0, "Member 'ABP_ARWHallTransNarrow02_C::SM_Whall_Wall_D_03' has a wrong offset!");
static_assert(offsetof(ABP_ARWHallTransNarrow02_C, SM_Whall_Floor_I_01) == 0x0003B8, "Member 'ABP_ARWHallTransNarrow02_C::SM_Whall_Floor_I_01' has a wrong offset!");
static_assert(offsetof(ABP_ARWHallTransNarrow02_C, SM_Whall_Wall_B_12) == 0x0003C0, "Member 'ABP_ARWHallTransNarrow02_C::SM_Whall_Wall_B_12' has a wrong offset!");
static_assert(offsetof(ABP_ARWHallTransNarrow02_C, MeshComponent1) == 0x0003C8, "Member 'ABP_ARWHallTransNarrow02_C::MeshComponent1' has a wrong offset!");

}

