#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ARWelkydIHolder01

#include "Basic.hpp"

#include "Altar_classes.hpp"


namespace SDK
{

// VModdableBlueprintGeneratedClass BP_ARWelkydIHolder01.BP_ARWelkydIHolder01_C
// 0x0010 (0x0358 - 0x0348)
class ABP_ARWelkydIHolder01_C final : public AVStatic
{
public:
	class ULocalMapComponent*                     LocalMapComponent;                                 // 0x0348(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   MeshComponent1;                                    // 0x0350(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ARWelkydIHolder01_C">();
	}
	static class ABP_ARWelkydIHolder01_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ARWelkydIHolder01_C>();
	}
};
static_assert(alignof(ABP_ARWelkydIHolder01_C) == 0x000008, "Wrong alignment on ABP_ARWelkydIHolder01_C");
static_assert(sizeof(ABP_ARWelkydIHolder01_C) == 0x000358, "Wrong size on ABP_ARWelkydIHolder01_C");
static_assert(offsetof(ABP_ARWelkydIHolder01_C, LocalMapComponent) == 0x000348, "Member 'ABP_ARWelkydIHolder01_C::LocalMapComponent' has a wrong offset!");
static_assert(offsetof(ABP_ARWelkydIHolder01_C, MeshComponent1) == 0x000350, "Member 'ABP_ARWelkydIHolder01_C::MeshComponent1' has a wrong offset!");

}

