#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ARDais01

#include "Basic.hpp"

#include "Altar_classes.hpp"


namespace SDK
{

// VModdableBlueprintGeneratedClass BP_ARDais01.BP_ARDais01_C
// 0x00F0 (0x0438 - 0x0348)
class ABP_ARDais01_C final : public AVStatic
{
public:
	class ULocalMapComponent*                     LocalMapComponent;                                 // 0x0348(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Caves_GroundRocks_02_A_Sliced_2;                // 0x0350(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Caves_GroundRocks_02_A_Sliced_3;                // 0x0358(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Caves_GroundRocks_02_A_Sliced_5;                // 0x0360(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Caves_GroundRocks_02_A_Sliced_4;                // 0x0368(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_AyleidInt_Gravel_3;                             // 0x0370(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_AyleidInt_Gravel_5;                             // 0x0378(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_AyleidInt_Gravel_4;                             // 0x0380(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_AyleidInt_Gravel_01;                            // 0x0388(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_AyleidInt_Gravel_2;                             // 0x0390(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Caves_GroundRocks_02_A_Sliced_01;               // 0x0398(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_AyleidInt_Rubble_15;                            // 0x03A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Caves_GroundRocks_02_A_Sliced_02;               // 0x03A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UObject*                                BPC_Puddle_02;                                     // 0x03B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UObject*                                BPC_Puddle_01;                                     // 0x03B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UObject*                                BPC_BrokenStones_02;                               // 0x03C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UObject*                                BPC_SpawnManager;                                  // 0x03C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UObject*                                BPC_BrokenStones_01;                               // 0x03D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_InteriorFloor_Stairs_A_COL_02;                  // 0x03D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_InteriorFloor_Stairs_A_COL_01;                  // 0x03E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh8;                                       // 0x03E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh7;                                       // 0x03F0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh6;                                       // 0x03F8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh5;                                       // 0x0400(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh4;                                       // 0x0408(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh3;                                       // 0x0410(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh2;                                       // 0x0418(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh1;                                       // 0x0420(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x0428(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   MeshComponent1;                                    // 0x0430(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ARDais01_C">();
	}
	static class ABP_ARDais01_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ARDais01_C>();
	}
};
static_assert(alignof(ABP_ARDais01_C) == 0x000008, "Wrong alignment on ABP_ARDais01_C");
static_assert(sizeof(ABP_ARDais01_C) == 0x000438, "Wrong size on ABP_ARDais01_C");
static_assert(offsetof(ABP_ARDais01_C, LocalMapComponent) == 0x000348, "Member 'ABP_ARDais01_C::LocalMapComponent' has a wrong offset!");
static_assert(offsetof(ABP_ARDais01_C, SM_Caves_GroundRocks_02_A_Sliced_2) == 0x000350, "Member 'ABP_ARDais01_C::SM_Caves_GroundRocks_02_A_Sliced_2' has a wrong offset!");
static_assert(offsetof(ABP_ARDais01_C, SM_Caves_GroundRocks_02_A_Sliced_3) == 0x000358, "Member 'ABP_ARDais01_C::SM_Caves_GroundRocks_02_A_Sliced_3' has a wrong offset!");
static_assert(offsetof(ABP_ARDais01_C, SM_Caves_GroundRocks_02_A_Sliced_5) == 0x000360, "Member 'ABP_ARDais01_C::SM_Caves_GroundRocks_02_A_Sliced_5' has a wrong offset!");
static_assert(offsetof(ABP_ARDais01_C, SM_Caves_GroundRocks_02_A_Sliced_4) == 0x000368, "Member 'ABP_ARDais01_C::SM_Caves_GroundRocks_02_A_Sliced_4' has a wrong offset!");
static_assert(offsetof(ABP_ARDais01_C, SM_AyleidInt_Gravel_3) == 0x000370, "Member 'ABP_ARDais01_C::SM_AyleidInt_Gravel_3' has a wrong offset!");
static_assert(offsetof(ABP_ARDais01_C, SM_AyleidInt_Gravel_5) == 0x000378, "Member 'ABP_ARDais01_C::SM_AyleidInt_Gravel_5' has a wrong offset!");
static_assert(offsetof(ABP_ARDais01_C, SM_AyleidInt_Gravel_4) == 0x000380, "Member 'ABP_ARDais01_C::SM_AyleidInt_Gravel_4' has a wrong offset!");
static_assert(offsetof(ABP_ARDais01_C, SM_AyleidInt_Gravel_01) == 0x000388, "Member 'ABP_ARDais01_C::SM_AyleidInt_Gravel_01' has a wrong offset!");
static_assert(offsetof(ABP_ARDais01_C, SM_AyleidInt_Gravel_2) == 0x000390, "Member 'ABP_ARDais01_C::SM_AyleidInt_Gravel_2' has a wrong offset!");
static_assert(offsetof(ABP_ARDais01_C, SM_Caves_GroundRocks_02_A_Sliced_01) == 0x000398, "Member 'ABP_ARDais01_C::SM_Caves_GroundRocks_02_A_Sliced_01' has a wrong offset!");
static_assert(offsetof(ABP_ARDais01_C, SM_AyleidInt_Rubble_15) == 0x0003A0, "Member 'ABP_ARDais01_C::SM_AyleidInt_Rubble_15' has a wrong offset!");
static_assert(offsetof(ABP_ARDais01_C, SM_Caves_GroundRocks_02_A_Sliced_02) == 0x0003A8, "Member 'ABP_ARDais01_C::SM_Caves_GroundRocks_02_A_Sliced_02' has a wrong offset!");
static_assert(offsetof(ABP_ARDais01_C, BPC_Puddle_02) == 0x0003B0, "Member 'ABP_ARDais01_C::BPC_Puddle_02' has a wrong offset!");
static_assert(offsetof(ABP_ARDais01_C, BPC_Puddle_01) == 0x0003B8, "Member 'ABP_ARDais01_C::BPC_Puddle_01' has a wrong offset!");
static_assert(offsetof(ABP_ARDais01_C, BPC_BrokenStones_02) == 0x0003C0, "Member 'ABP_ARDais01_C::BPC_BrokenStones_02' has a wrong offset!");
static_assert(offsetof(ABP_ARDais01_C, BPC_SpawnManager) == 0x0003C8, "Member 'ABP_ARDais01_C::BPC_SpawnManager' has a wrong offset!");
static_assert(offsetof(ABP_ARDais01_C, BPC_BrokenStones_01) == 0x0003D0, "Member 'ABP_ARDais01_C::BPC_BrokenStones_01' has a wrong offset!");
static_assert(offsetof(ABP_ARDais01_C, SM_InteriorFloor_Stairs_A_COL_02) == 0x0003D8, "Member 'ABP_ARDais01_C::SM_InteriorFloor_Stairs_A_COL_02' has a wrong offset!");
static_assert(offsetof(ABP_ARDais01_C, SM_InteriorFloor_Stairs_A_COL_01) == 0x0003E0, "Member 'ABP_ARDais01_C::SM_InteriorFloor_Stairs_A_COL_01' has a wrong offset!");
static_assert(offsetof(ABP_ARDais01_C, StaticMesh8) == 0x0003E8, "Member 'ABP_ARDais01_C::StaticMesh8' has a wrong offset!");
static_assert(offsetof(ABP_ARDais01_C, StaticMesh7) == 0x0003F0, "Member 'ABP_ARDais01_C::StaticMesh7' has a wrong offset!");
static_assert(offsetof(ABP_ARDais01_C, StaticMesh6) == 0x0003F8, "Member 'ABP_ARDais01_C::StaticMesh6' has a wrong offset!");
static_assert(offsetof(ABP_ARDais01_C, StaticMesh5) == 0x000400, "Member 'ABP_ARDais01_C::StaticMesh5' has a wrong offset!");
static_assert(offsetof(ABP_ARDais01_C, StaticMesh4) == 0x000408, "Member 'ABP_ARDais01_C::StaticMesh4' has a wrong offset!");
static_assert(offsetof(ABP_ARDais01_C, StaticMesh3) == 0x000410, "Member 'ABP_ARDais01_C::StaticMesh3' has a wrong offset!");
static_assert(offsetof(ABP_ARDais01_C, StaticMesh2) == 0x000418, "Member 'ABP_ARDais01_C::StaticMesh2' has a wrong offset!");
static_assert(offsetof(ABP_ARDais01_C, StaticMesh1) == 0x000420, "Member 'ABP_ARDais01_C::StaticMesh1' has a wrong offset!");
static_assert(offsetof(ABP_ARDais01_C, StaticMesh) == 0x000428, "Member 'ABP_ARDais01_C::StaticMesh' has a wrong offset!");
static_assert(offsetof(ABP_ARDais01_C, MeshComponent1) == 0x000430, "Member 'ABP_ARDais01_C::MeshComponent1' has a wrong offset!");

}

