#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ARDoor01b

#include "Basic.hpp"

#include "BP_Door_ardoor_classes.hpp"


namespace SDK
{

// VModdableBlueprintGeneratedClass BP_ARDoor01b.BP_ARDoor01b_C
// 0x0000 (0x04E0 - 0x04E0)
class ABP_ARDoor01b_C final : public ABP_Door_ardoor_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ARDoor01b_C">();
	}
	static class ABP_ARDoor01b_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ARDoor01b_C>();
	}
};
static_assert(alignof(ABP_ARDoor01b_C) == 0x000008, "Wrong alignment on ABP_ARDoor01b_C");
static_assert(sizeof(ABP_ARDoor01b_C) == 0x0004E0, "Wrong size on ABP_ARDoor01b_C");

}

