#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Daedric_Arrow_Dropped

#include "Basic.hpp"

#include "BP_Ammo_Generic_Dropped_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Daedric_Arrow_Dropped.BP_Daedric_Arrow_Dropped_C
// 0x0000 (0x0378 - 0x0378)
class ABP_Daedric_Arrow_Dropped_C final : public ABP_Ammo_Generic_Dropped_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Daedric_Arrow_Dropped_C">();
	}
	static class ABP_Daedric_Arrow_Dropped_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Daedric_Arrow_Dropped_C>();
	}
};
static_assert(alignof(ABP_Daedric_Arrow_Dropped_C) == 0x000008, "Wrong alignment on ABP_Daedric_Arrow_Dropped_C");
static_assert(sizeof(ABP_Daedric_Arrow_Dropped_C) == 0x000378, "Wrong size on ABP_Daedric_Arrow_Dropped_C");

}

