#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DungTombChestAlyied01

#include "Basic.hpp"

#include "BP_Chest_Archest01_classes.hpp"


namespace SDK
{

// VModdableBlueprintGeneratedClass BP_DungTombChestAlyied01.BP_DungTombChestAlyied01_C
// 0x0000 (0x0480 - 0x0480)
class ABP_DungTombChestAlyied01_C final : public ABP_Chest_Archest01_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_DungTombChestAlyied01_C">();
	}
	static class ABP_DungTombChestAlyied01_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_DungTombChestAlyied01_C>();
	}
};
static_assert(alignof(ABP_DungTombChestAlyied01_C) == 0x000008, "Wrong alignment on ABP_DungTombChestAlyied01_C");
static_assert(sizeof(ABP_DungTombChestAlyied01_C) == 0x000480, "Wrong size on ABP_DungTombChestAlyied01_C");

}

