#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Generic_Lich

#include "Basic.hpp"

#include "BP_Generic_Creature_classes.hpp"


namespace SDK
{

// VModdableBlueprintGeneratedClass BP_Generic_Lich.BP_Generic_Lich_C
// 0x0000 (0x0EE0 - 0x0EE0)
class ABP_Generic_Lich_C : public ABP_Generic_Creature_C
{
public:
	class UCapsuleComponent*                      SecondaryCollider;                                 // 0x0ED8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Generic_Lich_C">();
	}
	static class ABP_Generic_Lich_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Generic_Lich_C>();
	}
};
static_assert(alignof(ABP_Generic_Lich_C) == 0x000010, "Wrong alignment on ABP_Generic_Lich_C");
static_assert(sizeof(ABP_Generic_Lich_C) == 0x000EE0, "Wrong size on ABP_Generic_Lich_C");
static_assert(offsetof(ABP_Generic_Lich_C, SecondaryCollider) == 0x000ED8, "Member 'ABP_Generic_Lich_C::SecondaryCollider' has a wrong offset!");

}

