#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Generic_Zombie

#include "Basic.hpp"

#include "BP_Generic_Creature_classes.hpp"


namespace SDK
{

// VModdableBlueprintGeneratedClass BP_Generic_Zombie.BP_Generic_Zombie_C
// 0x0050 (0x0F30 - 0x0EE0)
class ABP_Generic_Zombie_C : public ABP_Generic_Creature_C
{
public:
	class USkeletalMeshComponent*                 Pants;                                             // 0x0ED8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 Hair;                                              // 0x0EE0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 Arm_L;                                             // 0x0EE8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 Arm_R;                                             // 0x0EF0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 Hand_l;                                            // 0x0EF8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 Hand_r;                                            // 0x0F00(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 Leg_R;                                             // 0x0F08(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 Leg_L;                                             // 0x0F10(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 Torso_R;                                           // 0x0F18(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 Torso_L;                                           // 0x0F20(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Generic_Zombie_C">();
	}
	static class ABP_Generic_Zombie_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Generic_Zombie_C>();
	}
};
static_assert(alignof(ABP_Generic_Zombie_C) == 0x000010, "Wrong alignment on ABP_Generic_Zombie_C");
static_assert(sizeof(ABP_Generic_Zombie_C) == 0x000F30, "Wrong size on ABP_Generic_Zombie_C");
static_assert(offsetof(ABP_Generic_Zombie_C, Pants) == 0x000ED8, "Member 'ABP_Generic_Zombie_C::Pants' has a wrong offset!");
static_assert(offsetof(ABP_Generic_Zombie_C, Hair) == 0x000EE0, "Member 'ABP_Generic_Zombie_C::Hair' has a wrong offset!");
static_assert(offsetof(ABP_Generic_Zombie_C, Arm_L) == 0x000EE8, "Member 'ABP_Generic_Zombie_C::Arm_L' has a wrong offset!");
static_assert(offsetof(ABP_Generic_Zombie_C, Arm_R) == 0x000EF0, "Member 'ABP_Generic_Zombie_C::Arm_R' has a wrong offset!");
static_assert(offsetof(ABP_Generic_Zombie_C, Hand_l) == 0x000EF8, "Member 'ABP_Generic_Zombie_C::Hand_l' has a wrong offset!");
static_assert(offsetof(ABP_Generic_Zombie_C, Hand_r) == 0x000F00, "Member 'ABP_Generic_Zombie_C::Hand_r' has a wrong offset!");
static_assert(offsetof(ABP_Generic_Zombie_C, Leg_R) == 0x000F08, "Member 'ABP_Generic_Zombie_C::Leg_R' has a wrong offset!");
static_assert(offsetof(ABP_Generic_Zombie_C, Leg_L) == 0x000F10, "Member 'ABP_Generic_Zombie_C::Leg_L' has a wrong offset!");
static_assert(offsetof(ABP_Generic_Zombie_C, Torso_R) == 0x000F18, "Member 'ABP_Generic_Zombie_C::Torso_R' has a wrong offset!");
static_assert(offsetof(ABP_Generic_Zombie_C, Torso_L) == 0x000F20, "Member 'ABP_Generic_Zombie_C::Torso_L' has a wrong offset!");

}

