#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Generic_Rat

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_Generic_Rat.BP_Generic_Rat_C.ExecuteUbergraph_BP_Generic_Rat
// 0x0004 (0x0004 - 0x0000)
struct BP_Generic_Rat_C_ExecuteUbergraph_BP_Generic_Rat final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Generic_Rat_C_ExecuteUbergraph_BP_Generic_Rat) == 0x000004, "Wrong alignment on BP_Generic_Rat_C_ExecuteUbergraph_BP_Generic_Rat");
static_assert(sizeof(BP_Generic_Rat_C_ExecuteUbergraph_BP_Generic_Rat) == 0x000004, "Wrong size on BP_Generic_Rat_C_ExecuteUbergraph_BP_Generic_Rat");
static_assert(offsetof(BP_Generic_Rat_C_ExecuteUbergraph_BP_Generic_Rat, EntryPoint) == 0x000000, "Member 'BP_Generic_Rat_C_ExecuteUbergraph_BP_Generic_Rat::EntryPoint' has a wrong offset!");

}

