#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Harrada

#include "Basic.hpp"

#include "Altar_classes.hpp"


namespace SDK
{

// VModdableBlueprintGeneratedClass BP_Harrada.BP_Harrada_C
// 0x0018 (0x0378 - 0x0360)
class ABP_Harrada_C final : public AVIngredient
{
public:
	class UNiagaraComponent*                      NiagaraComponent;                                  // 0x0360(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UVTESObjectRefComponent*                ObjectRefComponent;                                // 0x0368(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UVParticleEffectPairingComponent*       VParticleEffectPairingComponent;                   // 0x0370(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Harrada_C">();
	}
	static class ABP_Harrada_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Harrada_C>();
	}
};
static_assert(alignof(ABP_Harrada_C) == 0x000008, "Wrong alignment on ABP_Harrada_C");
static_assert(sizeof(ABP_Harrada_C) == 0x000378, "Wrong size on ABP_Harrada_C");
static_assert(offsetof(ABP_Harrada_C, NiagaraComponent) == 0x000360, "Member 'ABP_Harrada_C::NiagaraComponent' has a wrong offset!");
static_assert(offsetof(ABP_Harrada_C, ObjectRefComponent) == 0x000368, "Member 'ABP_Harrada_C::ObjectRefComponent' has a wrong offset!");
static_assert(offsetof(ABP_Harrada_C, VParticleEffectPairingComponent) == 0x000370, "Member 'ABP_Harrada_C::VParticleEffectPairingComponent' has a wrong offset!");

}

