#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_NDArmorLightHelmet1

#include "Basic.hpp"

#include "Altar_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_NDArmorLightHelmet1.BP_NDArmorLightHelmet1_C
// 0x0000 (0x0370 - 0x0370)
class ABP_NDArmorLightHelmet1_C final : public AVArmor
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_NDArmorLightHelmet1_C">();
	}
	static class ABP_NDArmorLightHelmet1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_NDArmorLightHelmet1_C>();
	}
};
static_assert(alignof(ABP_NDArmorLightHelmet1_C) == 0x000008, "Wrong alignment on ABP_NDArmorLightHelmet1_C");
static_assert(sizeof(ABP_NDArmorLightHelmet1_C) == 0x000370, "Wrong size on ABP_NDArmorLightHelmet1_C");

}

