#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PF_arwelkydclusterwhite01_Sta

#include "Basic.hpp"

#include "BP_Prefab_Crystals_Sta_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_PF_arwelkydclusterwhite01_Sta.BP_PF_arwelkydclusterwhite01_Sta_C
// 0x0020 (0x0540 - 0x0520)
class ABP_PF_arwelkydclusterwhite01_Sta_C : public ABP_Prefab_Crystals_Sta_C
{
public:
	class UVDetectionLightingProfileComponent*    VDetectionLightingProfile1;                        // 0x0520(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	bool                                          Is_Luster;                                         // 0x0528(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4C9B[0x7];                                     // 0x0529(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        Luster_Intensity;                                  // 0x0530(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Luster_Attenuation_Radius;                         // 0x0538(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_PF_arwelkydclusterwhite01_Sta_C">();
	}
	static class ABP_PF_arwelkydclusterwhite01_Sta_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PF_arwelkydclusterwhite01_Sta_C>();
	}
};
static_assert(alignof(ABP_PF_arwelkydclusterwhite01_Sta_C) == 0x000008, "Wrong alignment on ABP_PF_arwelkydclusterwhite01_Sta_C");
static_assert(sizeof(ABP_PF_arwelkydclusterwhite01_Sta_C) == 0x000540, "Wrong size on ABP_PF_arwelkydclusterwhite01_Sta_C");
static_assert(offsetof(ABP_PF_arwelkydclusterwhite01_Sta_C, VDetectionLightingProfile1) == 0x000520, "Member 'ABP_PF_arwelkydclusterwhite01_Sta_C::VDetectionLightingProfile1' has a wrong offset!");
static_assert(offsetof(ABP_PF_arwelkydclusterwhite01_Sta_C, Is_Luster) == 0x000528, "Member 'ABP_PF_arwelkydclusterwhite01_Sta_C::Is_Luster' has a wrong offset!");
static_assert(offsetof(ABP_PF_arwelkydclusterwhite01_Sta_C, Luster_Intensity) == 0x000530, "Member 'ABP_PF_arwelkydclusterwhite01_Sta_C::Luster_Intensity' has a wrong offset!");
static_assert(offsetof(ABP_PF_arwelkydclusterwhite01_Sta_C, Luster_Attenuation_Radius) == 0x000538, "Member 'ABP_PF_arwelkydclusterwhite01_Sta_C::Luster_Attenuation_Radius' has a wrong offset!");

}

