#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ScrollStandardOpen2Apprentice

#include "Basic.hpp"

#include "Altar_classes.hpp"


namespace SDK
{

// VModdableBlueprintGeneratedClass BP_ScrollStandardOpen2Apprentice.BP_ScrollStandardOpen2Apprentice_C
// 0x0000 (0x0358 - 0x0358)
class ABP_ScrollStandardOpen2Apprentice_C final : public AVBook
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ScrollStandardOpen2Apprentice_C">();
	}
	static class ABP_ScrollStandardOpen2Apprentice_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ScrollStandardOpen2Apprentice_C>();
	}
};
static_assert(alignof(ABP_ScrollStandardOpen2Apprentice_C) == 0x000008, "Wrong alignment on ABP_ScrollStandardOpen2Apprentice_C");
static_assert(sizeof(ABP_ScrollStandardOpen2Apprentice_C) == 0x000358, "Wrong size on ABP_ScrollStandardOpen2Apprentice_C");

}

