#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SoulGem3Common1PettySoul

#include "Basic.hpp"

#include "Altar_classes.hpp"


namespace SDK
{

// VModdableBlueprintGeneratedClass BP_SoulGem3Common1PettySoul.BP_SoulGem3Common1PettySoul_C
// 0x0000 (0x0358 - 0x0358)
class ABP_SoulGem3Common1PettySoul_C final : public AVSoulGem
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_SoulGem3Common1PettySoul_C">();
	}
	static class ABP_SoulGem3Common1PettySoul_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_SoulGem3Common1PettySoul_C>();
	}
};
static_assert(alignof(ABP_SoulGem3Common1PettySoul_C) == 0x000008, "Wrong alignment on ABP_SoulGem3Common1PettySoul_C");
static_assert(sizeof(ABP_SoulGem3Common1PettySoul_C) == 0x000358, "Wrong size on ABP_SoulGem3Common1PettySoul_C");

}

