#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ScrollStandardShield3Journeyman

#include "Basic.hpp"

#include "Altar_classes.hpp"


namespace SDK
{

// VModdableBlueprintGeneratedClass BP_ScrollStandardShield3Journeyman.BP_ScrollStandardShield3Journeyman_C
// 0x0000 (0x0358 - 0x0358)
class ABP_ScrollStandardShield3Journeyman_C final : public AVBook
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ScrollStandardShield3Journeyman_C">();
	}
	static class ABP_ScrollStandardShield3Journeyman_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ScrollStandardShield3Journeyman_C>();
	}
};
static_assert(alignof(ABP_ScrollStandardShield3Journeyman_C) == 0x000008, "Wrong alignment on ABP_ScrollStandardShield3Journeyman_C");
static_assert(sizeof(ABP_ScrollStandardShield3Journeyman_C) == 0x000358, "Wrong size on ABP_ScrollStandardShield3Journeyman_C");

}

