#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Spell_AreaEffect

#include "Basic.hpp"

#include "Altar_structs.hpp"
#include "BPE_EffectSize_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "BPE_ColorIndexSelection_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function BP_Spell_AreaEffect.BP_Spell_AreaEffect_C.Activate Point Light
// 0x0014 (0x0014 - 0x0000)
struct BP_Spell_AreaEffect_C_Activate_Point_Light final
{
public:
	bool                                          Condition;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBPE_ColorIndexSelection                      Temp_byte_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4BD3[0x2];                                     // 0x0002(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           K2Node_Select_Default;                             // 0x0004(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Spell_AreaEffect_C_Activate_Point_Light) == 0x000004, "Wrong alignment on BP_Spell_AreaEffect_C_Activate_Point_Light");
static_assert(sizeof(BP_Spell_AreaEffect_C_Activate_Point_Light) == 0x000014, "Wrong size on BP_Spell_AreaEffect_C_Activate_Point_Light");
static_assert(offsetof(BP_Spell_AreaEffect_C_Activate_Point_Light, Condition) == 0x000000, "Member 'BP_Spell_AreaEffect_C_Activate_Point_Light::Condition' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_Activate_Point_Light, Temp_byte_Variable) == 0x000001, "Member 'BP_Spell_AreaEffect_C_Activate_Point_Light::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_Activate_Point_Light, K2Node_Select_Default) == 0x000004, "Member 'BP_Spell_AreaEffect_C_Activate_Point_Light::K2Node_Select_Default' has a wrong offset!");

// Function BP_Spell_AreaEffect.BP_Spell_AreaEffect_C.BndEvt__BP_Spell_AreaEffect_Niagara VFX_K2Node_ComponentBoundEvent_0_OnNiagaraSystemFinished__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct BP_Spell_AreaEffect_C_BndEvt__BP_Spell_AreaEffect_Niagara_VFX_K2Node_ComponentBoundEvent_0_OnNiagaraSystemFinished__DelegateSignature final
{
public:
	class UNiagaraComponent*                      PSystem;                                           // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Spell_AreaEffect_C_BndEvt__BP_Spell_AreaEffect_Niagara_VFX_K2Node_ComponentBoundEvent_0_OnNiagaraSystemFinished__DelegateSignature) == 0x000008, "Wrong alignment on BP_Spell_AreaEffect_C_BndEvt__BP_Spell_AreaEffect_Niagara_VFX_K2Node_ComponentBoundEvent_0_OnNiagaraSystemFinished__DelegateSignature");
static_assert(sizeof(BP_Spell_AreaEffect_C_BndEvt__BP_Spell_AreaEffect_Niagara_VFX_K2Node_ComponentBoundEvent_0_OnNiagaraSystemFinished__DelegateSignature) == 0x000008, "Wrong size on BP_Spell_AreaEffect_C_BndEvt__BP_Spell_AreaEffect_Niagara_VFX_K2Node_ComponentBoundEvent_0_OnNiagaraSystemFinished__DelegateSignature");
static_assert(offsetof(BP_Spell_AreaEffect_C_BndEvt__BP_Spell_AreaEffect_Niagara_VFX_K2Node_ComponentBoundEvent_0_OnNiagaraSystemFinished__DelegateSignature, PSystem) == 0x000000, "Member 'BP_Spell_AreaEffect_C_BndEvt__BP_Spell_AreaEffect_Niagara_VFX_K2Node_ComponentBoundEvent_0_OnNiagaraSystemFinished__DelegateSignature::PSystem' has a wrong offset!");

// Function BP_Spell_AreaEffect.BP_Spell_AreaEffect_C.ExecuteUbergraph_BP_Spell_AreaEffect
// 0x01E0 (0x01E0 - 0x0000)
struct BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4BD4[0x4];                                     // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FBlueprintParameters                   K2Node_Event_Parameters;                           // 0x0008(0x0030)(ConstParm)
	bool                                          K2Node_Event_bIsTargetAnActor;                     // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4BD5[0x7];                                     // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 K2Node_Event_CasterActor;                          // 0x0040(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bDoesBeginInFirstPerson;              // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EVCastType                                    K2Node_Event_CastType;                             // 0x0049(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4BD6[0x2];                                     // 0x004A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         K2Node_Event_Magnitude;                            // 0x004C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_Event_Area;                                 // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_Event_Duration;                             // 0x0054(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector_NetQuantizeNormal              K2Node_Event_ImpactNormal;                         // 0x0058(0x0018)(ConstParm, NoDestructor, HasGetValueTypeHash)
	struct FVector_NetQuantizeNormal              K2Node_Event_Normal;                               // 0x0070(0x0018)(ConstParm, NoDestructor, HasGetValueTypeHash)
	EVSpellLevel                                  K2Node_Event_level;                                // 0x0088(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bIsTheEndOfTheEffect;                 // 0x0089(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bIsMainEffect;                        // 0x008A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bIsSecondEffect;                      // 0x008B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4BD7[0x4];                                     // 0x008C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 K2Node_Event_CollidedActor;                        // 0x0090(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_Event_CollidedComponent;                    // 0x0098(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_DeltaSeconds;                         // 0x00A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4BD8[0x4];                                     // 0x00A4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UNiagaraComponent*                      K2Node_ComponentBoundEvent_PSystem;                // 0x00A8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x00B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4BD9[0x7];                                     // 0x00B1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Divide_DoubleDouble_ReturnValue;          // 0x00B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  CallFunc_GetPlayerPawn_ReturnValue;                // 0x00C0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetDistanceTo_ReturnValue;                // 0x00C8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_DoubleDouble_ReturnValue;       // 0x00CC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_DoubleDouble_ReturnValue;         // 0x00CD(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue_1;                 // 0x00CE(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4BDA[0x1];                                     // 0x00CF(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Divide_DoubleDouble_ReturnValue_1;        // 0x00D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_SelectFloat_ReturnValue;                  // 0x00D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_DoubleDouble_ReturnValue_1;     // 0x00E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4BDB[0x7];                                     // 0x00E1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_SelectFloat_ReturnValue_1;                // 0x00E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_DoubleDouble_ReturnValue_2;     // 0x00F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4BDC[0x7];                                     // 0x00F1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Divide_DoubleDouble_ReturnValue_2;        // 0x00F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_SelectFloat_ReturnValue_2;                // 0x0100(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_DoubleDouble_ReturnValue_3;     // 0x0108(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4BDD[0x7];                                     // 0x0109(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_SelectFloat_ReturnValue_3;                // 0x0110(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Add_DoubleDouble_ReturnValue;             // 0x0118(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Add_DoubleDouble_ReturnValue_1;           // 0x0120(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue_2;                 // 0x0128(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4BDE[0x7];                                     // 0x0129(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_SelectFloat_ReturnValue_4;                // 0x0130(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue_3;                 // 0x0138(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4BDF[0x7];                                     // 0x0139(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_FMax_ReturnValue;                         // 0x0140(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_SelectFloat_ReturnValue_5;                // 0x0148(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_FMax_ReturnValue_1;                       // 0x0150(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_FMax_ReturnValue_2;                       // 0x0158(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_FMax_A_ImplicitCast;                      // 0x0160(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Divide_DoubleDouble_B_ImplicitCast;       // 0x0168(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Greater_DoubleDouble_B_ImplicitCast;      // 0x0170(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_SelectFloat_A_ImplicitCast;               // 0x0178(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Divide_DoubleDouble_B_ImplicitCast_1;     // 0x0180(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_LessEqual_DoubleDouble_A_ImplicitCast;    // 0x0188(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Update_Point_Light_Animation_Maximum_Intensity_ImplicitCast; // 0x0190(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_SelectFloat_B_ImplicitCast;               // 0x0198(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_LessEqual_DoubleDouble_A_ImplicitCast_1;  // 0x01A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Update_Point_Light_Animation_Fade_In_Duration_ImplicitCast; // 0x01A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Update_Point_Light_Animation_Fade_Out_Duration_ImplicitCast; // 0x01B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Update_Point_Light_Animation_Delay_ImplicitCast; // 0x01B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_SelectFloat_A_ImplicitCast_1;             // 0x01C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Add_DoubleDouble_A_ImplicitCast;          // 0x01C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Add_DoubleDouble_B_ImplicitCast;          // 0x01D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Delay_Duration_ImplicitCast;              // 0x01D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect) == 0x000008, "Wrong alignment on BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect");
static_assert(sizeof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect) == 0x0001E0, "Wrong size on BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, EntryPoint) == 0x000000, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, K2Node_Event_Parameters) == 0x000008, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::K2Node_Event_Parameters' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, K2Node_Event_bIsTargetAnActor) == 0x000038, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::K2Node_Event_bIsTargetAnActor' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, K2Node_Event_CasterActor) == 0x000040, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::K2Node_Event_CasterActor' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, K2Node_Event_bDoesBeginInFirstPerson) == 0x000048, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::K2Node_Event_bDoesBeginInFirstPerson' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, K2Node_Event_CastType) == 0x000049, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::K2Node_Event_CastType' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, K2Node_Event_Magnitude) == 0x00004C, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::K2Node_Event_Magnitude' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, K2Node_Event_Area) == 0x000050, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::K2Node_Event_Area' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, K2Node_Event_Duration) == 0x000054, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::K2Node_Event_Duration' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, K2Node_Event_ImpactNormal) == 0x000058, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::K2Node_Event_ImpactNormal' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, K2Node_Event_Normal) == 0x000070, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::K2Node_Event_Normal' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, K2Node_Event_level) == 0x000088, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::K2Node_Event_level' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, K2Node_Event_bIsTheEndOfTheEffect) == 0x000089, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::K2Node_Event_bIsTheEndOfTheEffect' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, K2Node_Event_bIsMainEffect) == 0x00008A, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::K2Node_Event_bIsMainEffect' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, K2Node_Event_bIsSecondEffect) == 0x00008B, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::K2Node_Event_bIsSecondEffect' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, K2Node_Event_CollidedActor) == 0x000090, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::K2Node_Event_CollidedActor' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, K2Node_Event_CollidedComponent) == 0x000098, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::K2Node_Event_CollidedComponent' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, K2Node_Event_DeltaSeconds) == 0x0000A0, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::K2Node_Event_DeltaSeconds' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, K2Node_ComponentBoundEvent_PSystem) == 0x0000A8, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::K2Node_ComponentBoundEvent_PSystem' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, CallFunc_BooleanAND_ReturnValue) == 0x0000B0, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, CallFunc_Divide_DoubleDouble_ReturnValue) == 0x0000B8, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::CallFunc_Divide_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, CallFunc_GetPlayerPawn_ReturnValue) == 0x0000C0, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::CallFunc_GetPlayerPawn_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, CallFunc_GetDistanceTo_ReturnValue) == 0x0000C8, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::CallFunc_GetDistanceTo_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, CallFunc_LessEqual_DoubleDouble_ReturnValue) == 0x0000CC, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::CallFunc_LessEqual_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, CallFunc_Greater_DoubleDouble_ReturnValue) == 0x0000CD, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::CallFunc_Greater_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, CallFunc_BooleanAND_ReturnValue_1) == 0x0000CE, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::CallFunc_BooleanAND_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, CallFunc_Divide_DoubleDouble_ReturnValue_1) == 0x0000D0, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::CallFunc_Divide_DoubleDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, CallFunc_SelectFloat_ReturnValue) == 0x0000D8, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::CallFunc_SelectFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, CallFunc_LessEqual_DoubleDouble_ReturnValue_1) == 0x0000E0, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::CallFunc_LessEqual_DoubleDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, CallFunc_SelectFloat_ReturnValue_1) == 0x0000E8, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::CallFunc_SelectFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, CallFunc_LessEqual_DoubleDouble_ReturnValue_2) == 0x0000F0, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::CallFunc_LessEqual_DoubleDouble_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, CallFunc_Divide_DoubleDouble_ReturnValue_2) == 0x0000F8, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::CallFunc_Divide_DoubleDouble_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, CallFunc_SelectFloat_ReturnValue_2) == 0x000100, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::CallFunc_SelectFloat_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, CallFunc_LessEqual_DoubleDouble_ReturnValue_3) == 0x000108, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::CallFunc_LessEqual_DoubleDouble_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, CallFunc_SelectFloat_ReturnValue_3) == 0x000110, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::CallFunc_SelectFloat_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, CallFunc_Add_DoubleDouble_ReturnValue) == 0x000118, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::CallFunc_Add_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, CallFunc_Add_DoubleDouble_ReturnValue_1) == 0x000120, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::CallFunc_Add_DoubleDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, CallFunc_BooleanAND_ReturnValue_2) == 0x000128, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::CallFunc_BooleanAND_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, CallFunc_SelectFloat_ReturnValue_4) == 0x000130, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::CallFunc_SelectFloat_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, CallFunc_BooleanAND_ReturnValue_3) == 0x000138, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::CallFunc_BooleanAND_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, CallFunc_FMax_ReturnValue) == 0x000140, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::CallFunc_FMax_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, CallFunc_SelectFloat_ReturnValue_5) == 0x000148, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::CallFunc_SelectFloat_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, CallFunc_FMax_ReturnValue_1) == 0x000150, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::CallFunc_FMax_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, CallFunc_FMax_ReturnValue_2) == 0x000158, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::CallFunc_FMax_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, CallFunc_FMax_A_ImplicitCast) == 0x000160, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::CallFunc_FMax_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, CallFunc_Divide_DoubleDouble_B_ImplicitCast) == 0x000168, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::CallFunc_Divide_DoubleDouble_B_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, CallFunc_Greater_DoubleDouble_B_ImplicitCast) == 0x000170, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::CallFunc_Greater_DoubleDouble_B_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, CallFunc_SelectFloat_A_ImplicitCast) == 0x000178, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::CallFunc_SelectFloat_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, CallFunc_Divide_DoubleDouble_B_ImplicitCast_1) == 0x000180, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::CallFunc_Divide_DoubleDouble_B_ImplicitCast_1' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, CallFunc_LessEqual_DoubleDouble_A_ImplicitCast) == 0x000188, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::CallFunc_LessEqual_DoubleDouble_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, CallFunc_Update_Point_Light_Animation_Maximum_Intensity_ImplicitCast) == 0x000190, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::CallFunc_Update_Point_Light_Animation_Maximum_Intensity_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, CallFunc_SelectFloat_B_ImplicitCast) == 0x000198, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::CallFunc_SelectFloat_B_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, CallFunc_LessEqual_DoubleDouble_A_ImplicitCast_1) == 0x0001A0, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::CallFunc_LessEqual_DoubleDouble_A_ImplicitCast_1' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, CallFunc_Update_Point_Light_Animation_Fade_In_Duration_ImplicitCast) == 0x0001A8, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::CallFunc_Update_Point_Light_Animation_Fade_In_Duration_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, CallFunc_Update_Point_Light_Animation_Fade_Out_Duration_ImplicitCast) == 0x0001B0, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::CallFunc_Update_Point_Light_Animation_Fade_Out_Duration_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, CallFunc_Update_Point_Light_Animation_Delay_ImplicitCast) == 0x0001B8, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::CallFunc_Update_Point_Light_Animation_Delay_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, CallFunc_SelectFloat_A_ImplicitCast_1) == 0x0001C0, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::CallFunc_SelectFloat_A_ImplicitCast_1' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, CallFunc_Add_DoubleDouble_A_ImplicitCast) == 0x0001C8, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::CallFunc_Add_DoubleDouble_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, CallFunc_Add_DoubleDouble_B_ImplicitCast) == 0x0001D0, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::CallFunc_Add_DoubleDouble_B_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect, CallFunc_Delay_Duration_ImplicitCast) == 0x0001D8, "Member 'BP_Spell_AreaEffect_C_ExecuteUbergraph_BP_Spell_AreaEffect::CallFunc_Delay_Duration_ImplicitCast' has a wrong offset!");

// Function BP_Spell_AreaEffect.BP_Spell_AreaEffect_C.OnStartPlay
// 0x0098 (0x0098 - 0x0000)
struct BP_Spell_AreaEffect_C_OnStartPlay final
{
public:
	struct FBlueprintParameters                   Parameters;                                        // 0x0000(0x0030)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	bool                                          bIsTargetAnActor;                                  // 0x0030(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4BE0[0x7];                                     // 0x0031(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CasterActor;                                       // 0x0038(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          bDoesBeginInFirstPerson;                           // 0x0040(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EVCastType                                    CastType;                                          // 0x0041(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4BE1[0x2];                                     // 0x0042(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Magnitude;                                         // 0x0044(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Area;                                              // 0x0048(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Duration;                                          // 0x004C(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector_NetQuantizeNormal              ImpactNormal;                                      // 0x0050(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
	struct FVector_NetQuantizeNormal              Normal;                                            // 0x0068(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
	EVSpellLevel                                  Level;                                             // 0x0080(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bIsTheEndOfTheEffect;                              // 0x0081(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bIsMainEffect;                                     // 0x0082(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bIsSecondEffect;                                   // 0x0083(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4BE2[0x4];                                     // 0x0084(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CollidedActor;                                     // 0x0088(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    CollidedComponent;                                 // 0x0090(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Spell_AreaEffect_C_OnStartPlay) == 0x000008, "Wrong alignment on BP_Spell_AreaEffect_C_OnStartPlay");
static_assert(sizeof(BP_Spell_AreaEffect_C_OnStartPlay) == 0x000098, "Wrong size on BP_Spell_AreaEffect_C_OnStartPlay");
static_assert(offsetof(BP_Spell_AreaEffect_C_OnStartPlay, Parameters) == 0x000000, "Member 'BP_Spell_AreaEffect_C_OnStartPlay::Parameters' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_OnStartPlay, bIsTargetAnActor) == 0x000030, "Member 'BP_Spell_AreaEffect_C_OnStartPlay::bIsTargetAnActor' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_OnStartPlay, CasterActor) == 0x000038, "Member 'BP_Spell_AreaEffect_C_OnStartPlay::CasterActor' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_OnStartPlay, bDoesBeginInFirstPerson) == 0x000040, "Member 'BP_Spell_AreaEffect_C_OnStartPlay::bDoesBeginInFirstPerson' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_OnStartPlay, CastType) == 0x000041, "Member 'BP_Spell_AreaEffect_C_OnStartPlay::CastType' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_OnStartPlay, Magnitude) == 0x000044, "Member 'BP_Spell_AreaEffect_C_OnStartPlay::Magnitude' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_OnStartPlay, Area) == 0x000048, "Member 'BP_Spell_AreaEffect_C_OnStartPlay::Area' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_OnStartPlay, Duration) == 0x00004C, "Member 'BP_Spell_AreaEffect_C_OnStartPlay::Duration' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_OnStartPlay, ImpactNormal) == 0x000050, "Member 'BP_Spell_AreaEffect_C_OnStartPlay::ImpactNormal' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_OnStartPlay, Normal) == 0x000068, "Member 'BP_Spell_AreaEffect_C_OnStartPlay::Normal' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_OnStartPlay, Level) == 0x000080, "Member 'BP_Spell_AreaEffect_C_OnStartPlay::Level' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_OnStartPlay, bIsTheEndOfTheEffect) == 0x000081, "Member 'BP_Spell_AreaEffect_C_OnStartPlay::bIsTheEndOfTheEffect' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_OnStartPlay, bIsMainEffect) == 0x000082, "Member 'BP_Spell_AreaEffect_C_OnStartPlay::bIsMainEffect' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_OnStartPlay, bIsSecondEffect) == 0x000083, "Member 'BP_Spell_AreaEffect_C_OnStartPlay::bIsSecondEffect' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_OnStartPlay, CollidedActor) == 0x000088, "Member 'BP_Spell_AreaEffect_C_OnStartPlay::CollidedActor' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_OnStartPlay, CollidedComponent) == 0x000090, "Member 'BP_Spell_AreaEffect_C_OnStartPlay::CollidedComponent' has a wrong offset!");

// Function BP_Spell_AreaEffect.BP_Spell_AreaEffect_C.ReceiveTick
// 0x0004 (0x0004 - 0x0000)
struct BP_Spell_AreaEffect_C_ReceiveTick final
{
public:
	float                                         DeltaSeconds;                                      // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Spell_AreaEffect_C_ReceiveTick) == 0x000004, "Wrong alignment on BP_Spell_AreaEffect_C_ReceiveTick");
static_assert(sizeof(BP_Spell_AreaEffect_C_ReceiveTick) == 0x000004, "Wrong size on BP_Spell_AreaEffect_C_ReceiveTick");
static_assert(offsetof(BP_Spell_AreaEffect_C_ReceiveTick, DeltaSeconds) == 0x000000, "Member 'BP_Spell_AreaEffect_C_ReceiveTick::DeltaSeconds' has a wrong offset!");

// Function BP_Spell_AreaEffect.BP_Spell_AreaEffect_C.Select Accurate Niagara System
// 0x0070 (0x0070 - 0x0000)
struct BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System final
{
public:
	bool                                          Temp_bool_Variable;                                // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_1;                              // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBPE_EffectSize                               Temp_byte_Variable;                                // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4BE3[0x1];                                     // 0x0003(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue;               // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_2;                              // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_3;                              // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4BE4[0x6];                                     // 0x000A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<int32>                                 CallFunc_Map_Values_Values;                        // 0x0010(0x0010)(ReferenceParm)
	int32                                         CallFunc_Array_Get_Item;                           // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Get_Item_1;                         // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Get_Item_2;                         // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x002C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue_1;             // 0x002D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x002E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x002F(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0031(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4BE5[0x6];                                     // 0x0032(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UNiagaraSystem*                         K2Node_Select_Default;                             // 0x0038(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UNiagaraSystem*                         K2Node_Select_Default_1;                           // 0x0040(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x0049(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4BE6[0x6];                                     // 0x004A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UNiagaraSystem*                         K2Node_Select_Default_2;                           // 0x0050(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UNiagaraSystem*                         K2Node_Select_Default_3;                           // 0x0058(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UNiagaraSystem*                         K2Node_Select_Default_4;                           // 0x0060(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue_2;             // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_2;                // 0x0069(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System) == 0x000008, "Wrong alignment on BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System");
static_assert(sizeof(BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System) == 0x000070, "Wrong size on BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System");
static_assert(offsetof(BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System, Temp_bool_Variable) == 0x000000, "Member 'BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System, Temp_bool_Variable_1) == 0x000001, "Member 'BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System::Temp_bool_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System, Temp_byte_Variable) == 0x000002, "Member 'BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System, CallFunc_Conv_ByteToInt_ReturnValue) == 0x000004, "Member 'BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System::CallFunc_Conv_ByteToInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System, Temp_bool_Variable_2) == 0x000008, "Member 'BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System::Temp_bool_Variable_2' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System, Temp_bool_Variable_3) == 0x000009, "Member 'BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System::Temp_bool_Variable_3' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System, CallFunc_Map_Values_Values) == 0x000010, "Member 'BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System::CallFunc_Map_Values_Values' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System, CallFunc_Array_Get_Item) == 0x000020, "Member 'BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System, CallFunc_Array_Get_Item_1) == 0x000024, "Member 'BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System, CallFunc_Array_Get_Item_2) == 0x000028, "Member 'BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System::CallFunc_Array_Get_Item_2' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System, CallFunc_Greater_IntInt_ReturnValue) == 0x00002C, "Member 'BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System, CallFunc_Greater_IntInt_ReturnValue_1) == 0x00002D, "Member 'BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System::CallFunc_Greater_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System, CallFunc_Less_IntInt_ReturnValue) == 0x00002E, "Member 'BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System, CallFunc_Less_IntInt_ReturnValue_1) == 0x00002F, "Member 'BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System, CallFunc_IsValid_ReturnValue) == 0x000030, "Member 'BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System, CallFunc_IsValid_ReturnValue_1) == 0x000031, "Member 'BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System, K2Node_Select_Default) == 0x000038, "Member 'BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System, K2Node_Select_Default_1) == 0x000040, "Member 'BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System::K2Node_Select_Default_1' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System, CallFunc_IsValid_ReturnValue_2) == 0x000048, "Member 'BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System, CallFunc_IsValid_ReturnValue_3) == 0x000049, "Member 'BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System::CallFunc_IsValid_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System, K2Node_Select_Default_2) == 0x000050, "Member 'BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System::K2Node_Select_Default_2' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System, K2Node_Select_Default_3) == 0x000058, "Member 'BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System::K2Node_Select_Default_3' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System, K2Node_Select_Default_4) == 0x000060, "Member 'BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System::K2Node_Select_Default_4' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System, CallFunc_Greater_IntInt_ReturnValue_2) == 0x000068, "Member 'BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System::CallFunc_Greater_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System, CallFunc_Less_IntInt_ReturnValue_2) == 0x000069, "Member 'BP_Spell_AreaEffect_C_Select_Accurate_Niagara_System::CallFunc_Less_IntInt_ReturnValue_2' has a wrong offset!");

// Function BP_Spell_AreaEffect.BP_Spell_AreaEffect_C.Spawn Impact Decal Blueprint
// 0x00D0 (0x00D0 - 0x0000)
struct BP_Spell_AreaEffect_C_Spawn_Impact_Decal_Blueprint final
{
public:
	bool                                          CallFunc_IsVisible_ReturnValue;                    // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue_1;                // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValidClass_ReturnValue;                 // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4BE7[0x3];                                     // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue;      // 0x0008(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Conv_DoubleToVector_ReturnValue;          // 0x0020(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue;             // 0x0038(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x0050(0x0060)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue; // 0x00B0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_FinishSpawningActor_ReturnValue;          // 0x00B8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_K2_AttachToComponent_ReturnValue;         // 0x00C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4BE8[0x7];                                     // 0x00C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Conv_DoubleToVector_InDouble_ImplicitCast; // 0x00C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Spell_AreaEffect_C_Spawn_Impact_Decal_Blueprint) == 0x000010, "Wrong alignment on BP_Spell_AreaEffect_C_Spawn_Impact_Decal_Blueprint");
static_assert(sizeof(BP_Spell_AreaEffect_C_Spawn_Impact_Decal_Blueprint) == 0x0000D0, "Wrong size on BP_Spell_AreaEffect_C_Spawn_Impact_Decal_Blueprint");
static_assert(offsetof(BP_Spell_AreaEffect_C_Spawn_Impact_Decal_Blueprint, CallFunc_IsVisible_ReturnValue) == 0x000000, "Member 'BP_Spell_AreaEffect_C_Spawn_Impact_Decal_Blueprint::CallFunc_IsVisible_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_Spawn_Impact_Decal_Blueprint, CallFunc_Not_PreBool_ReturnValue) == 0x000001, "Member 'BP_Spell_AreaEffect_C_Spawn_Impact_Decal_Blueprint::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_Spawn_Impact_Decal_Blueprint, CallFunc_Not_PreBool_ReturnValue_1) == 0x000002, "Member 'BP_Spell_AreaEffect_C_Spawn_Impact_Decal_Blueprint::CallFunc_Not_PreBool_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_Spawn_Impact_Decal_Blueprint, CallFunc_BooleanAND_ReturnValue) == 0x000003, "Member 'BP_Spell_AreaEffect_C_Spawn_Impact_Decal_Blueprint::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_Spawn_Impact_Decal_Blueprint, CallFunc_IsValidClass_ReturnValue) == 0x000004, "Member 'BP_Spell_AreaEffect_C_Spawn_Impact_Decal_Blueprint::CallFunc_IsValidClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_Spawn_Impact_Decal_Blueprint, CallFunc_K2_GetComponentLocation_ReturnValue) == 0x000008, "Member 'BP_Spell_AreaEffect_C_Spawn_Impact_Decal_Blueprint::CallFunc_K2_GetComponentLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_Spawn_Impact_Decal_Blueprint, CallFunc_Conv_DoubleToVector_ReturnValue) == 0x000020, "Member 'BP_Spell_AreaEffect_C_Spawn_Impact_Decal_Blueprint::CallFunc_Conv_DoubleToVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_Spawn_Impact_Decal_Blueprint, CallFunc_Add_VectorVector_ReturnValue) == 0x000038, "Member 'BP_Spell_AreaEffect_C_Spawn_Impact_Decal_Blueprint::CallFunc_Add_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_Spawn_Impact_Decal_Blueprint, CallFunc_MakeTransform_ReturnValue) == 0x000050, "Member 'BP_Spell_AreaEffect_C_Spawn_Impact_Decal_Blueprint::CallFunc_MakeTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_Spawn_Impact_Decal_Blueprint, CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue) == 0x0000B0, "Member 'BP_Spell_AreaEffect_C_Spawn_Impact_Decal_Blueprint::CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_Spawn_Impact_Decal_Blueprint, CallFunc_FinishSpawningActor_ReturnValue) == 0x0000B8, "Member 'BP_Spell_AreaEffect_C_Spawn_Impact_Decal_Blueprint::CallFunc_FinishSpawningActor_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_Spawn_Impact_Decal_Blueprint, CallFunc_K2_AttachToComponent_ReturnValue) == 0x0000C0, "Member 'BP_Spell_AreaEffect_C_Spawn_Impact_Decal_Blueprint::CallFunc_K2_AttachToComponent_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_Spawn_Impact_Decal_Blueprint, CallFunc_Conv_DoubleToVector_InDouble_ImplicitCast) == 0x0000C8, "Member 'BP_Spell_AreaEffect_C_Spawn_Impact_Decal_Blueprint::CallFunc_Conv_DoubleToVector_InDouble_ImplicitCast' has a wrong offset!");

// Function BP_Spell_AreaEffect.BP_Spell_AreaEffect_C.UserConstructionScript
// 0x0070 (0x0070 - 0x0000)
struct BP_Spell_AreaEffect_C_UserConstructionScript final
{
public:
	bool                                          Temp_bool_Variable;                                // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_1;                              // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_DoubleDouble_ReturnValue;         // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4BE9[0x5];                                     // 0x0003(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        K2Node_Select_Default;                             // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_DoubleDouble_ReturnValue_1;       // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4BEA[0x7];                                     // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        K2Node_Select_Default_1;                           // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        K2Node_Select_Option_1_ImplicitCast;               // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Greater_DoubleDouble_A_ImplicitCast;      // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        K2Node_Select_Option_0_ImplicitCast;               // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        K2Node_Select_Option_0_ImplicitCast_1;             // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_VariableSet_Light_Lifetime_ImplicitCast;    // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4BEB[0x4];                                     // 0x0044(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Preset_Point_Light_Parameters_Specular_Scale_ImplicitCast; // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Preset_Point_Light_Parameters_Source_Radius_ImplicitCast; // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Preset_Point_Light_Parameters_Volumetric_Scattering_Intensity_ImplicitCast; // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Preset_Point_Light_Parameters_Indirect_Lighting_Intensity_ImplicitCast; // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Preset_Point_Light_Parameters_Attenuation_Radius_ImplicitCast; // 0x0068(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Spell_AreaEffect_C_UserConstructionScript) == 0x000008, "Wrong alignment on BP_Spell_AreaEffect_C_UserConstructionScript");
static_assert(sizeof(BP_Spell_AreaEffect_C_UserConstructionScript) == 0x000070, "Wrong size on BP_Spell_AreaEffect_C_UserConstructionScript");
static_assert(offsetof(BP_Spell_AreaEffect_C_UserConstructionScript, Temp_bool_Variable) == 0x000000, "Member 'BP_Spell_AreaEffect_C_UserConstructionScript::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_UserConstructionScript, Temp_bool_Variable_1) == 0x000001, "Member 'BP_Spell_AreaEffect_C_UserConstructionScript::Temp_bool_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_UserConstructionScript, CallFunc_Greater_DoubleDouble_ReturnValue) == 0x000002, "Member 'BP_Spell_AreaEffect_C_UserConstructionScript::CallFunc_Greater_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_UserConstructionScript, K2Node_Select_Default) == 0x000008, "Member 'BP_Spell_AreaEffect_C_UserConstructionScript::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_UserConstructionScript, CallFunc_Greater_DoubleDouble_ReturnValue_1) == 0x000010, "Member 'BP_Spell_AreaEffect_C_UserConstructionScript::CallFunc_Greater_DoubleDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_UserConstructionScript, K2Node_Select_Default_1) == 0x000018, "Member 'BP_Spell_AreaEffect_C_UserConstructionScript::K2Node_Select_Default_1' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_UserConstructionScript, K2Node_Select_Option_1_ImplicitCast) == 0x000020, "Member 'BP_Spell_AreaEffect_C_UserConstructionScript::K2Node_Select_Option_1_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_UserConstructionScript, CallFunc_Greater_DoubleDouble_A_ImplicitCast) == 0x000028, "Member 'BP_Spell_AreaEffect_C_UserConstructionScript::CallFunc_Greater_DoubleDouble_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_UserConstructionScript, K2Node_Select_Option_0_ImplicitCast) == 0x000030, "Member 'BP_Spell_AreaEffect_C_UserConstructionScript::K2Node_Select_Option_0_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_UserConstructionScript, K2Node_Select_Option_0_ImplicitCast_1) == 0x000038, "Member 'BP_Spell_AreaEffect_C_UserConstructionScript::K2Node_Select_Option_0_ImplicitCast_1' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_UserConstructionScript, K2Node_VariableSet_Light_Lifetime_ImplicitCast) == 0x000040, "Member 'BP_Spell_AreaEffect_C_UserConstructionScript::K2Node_VariableSet_Light_Lifetime_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_UserConstructionScript, CallFunc_Preset_Point_Light_Parameters_Specular_Scale_ImplicitCast) == 0x000048, "Member 'BP_Spell_AreaEffect_C_UserConstructionScript::CallFunc_Preset_Point_Light_Parameters_Specular_Scale_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_UserConstructionScript, CallFunc_Preset_Point_Light_Parameters_Source_Radius_ImplicitCast) == 0x000050, "Member 'BP_Spell_AreaEffect_C_UserConstructionScript::CallFunc_Preset_Point_Light_Parameters_Source_Radius_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_UserConstructionScript, CallFunc_Preset_Point_Light_Parameters_Volumetric_Scattering_Intensity_ImplicitCast) == 0x000058, "Member 'BP_Spell_AreaEffect_C_UserConstructionScript::CallFunc_Preset_Point_Light_Parameters_Volumetric_Scattering_Intensity_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_UserConstructionScript, CallFunc_Preset_Point_Light_Parameters_Indirect_Lighting_Intensity_ImplicitCast) == 0x000060, "Member 'BP_Spell_AreaEffect_C_UserConstructionScript::CallFunc_Preset_Point_Light_Parameters_Indirect_Lighting_Intensity_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_Spell_AreaEffect_C_UserConstructionScript, CallFunc_Preset_Point_Light_Parameters_Attenuation_Radius_ImplicitCast) == 0x000068, "Member 'BP_Spell_AreaEffect_C_UserConstructionScript::CallFunc_Preset_Point_Light_Parameters_Attenuation_Radius_ImplicitCast' has a wrong offset!");

}

