#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Spell_HitEffect

#include "Basic.hpp"

#include "BP_Spell_HitEffect_classes.hpp"
#include "BP_Spell_HitEffect_parameters.hpp"


namespace SDK
{

// Function BP_Spell_HitEffect.BP_Spell_HitEffect_C.BndEvt__BP_Spell_HitEffect_Niagara VFX_K2Node_ComponentBoundEvent_0_OnNiagaraSystemFinished__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UNiagaraComponent*                PSystem                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void ABP_Spell_HitEffect_C::BndEvt__BP_Spell_HitEffect_Niagara_VFX_K2Node_ComponentBoundEvent_0_OnNiagaraSystemFinished__DelegateSignature(class UNiagaraComponent* PSystem)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Spell_HitEffect_C", "BndEvt__BP_Spell_HitEffect_Niagara VFX_K2Node_ComponentBoundEvent_0_OnNiagaraSystemFinished__DelegateSignature");

	Params::BP_Spell_HitEffect_C_BndEvt__BP_Spell_HitEffect_Niagara_VFX_K2Node_ComponentBoundEvent_0_OnNiagaraSystemFinished__DelegateSignature Parms{};

	Parms.PSystem = PSystem;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Spell_HitEffect.BP_Spell_HitEffect_C.Child Behavior: After Setup
// (BlueprintCallable, BlueprintEvent)

void ABP_Spell_HitEffect_C::Child_Behavior__After_Setup()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Spell_HitEffect_C", "Child Behavior: After Setup");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Spell_HitEffect.BP_Spell_HitEffect_C.Child Behavior: Before Setup
// (BlueprintCallable, BlueprintEvent)

void ABP_Spell_HitEffect_C::Child_Behavior__Before_Setup()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Spell_HitEffect_C", "Child Behavior: Before Setup");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Spell_HitEffect.BP_Spell_HitEffect_C.ExecuteUbergraph_BP_Spell_HitEffect
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Spell_HitEffect_C::ExecuteUbergraph_BP_Spell_HitEffect(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Spell_HitEffect_C", "ExecuteUbergraph_BP_Spell_HitEffect");

	Params::BP_Spell_HitEffect_C_ExecuteUbergraph_BP_Spell_HitEffect Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Spell_HitEffect.BP_Spell_HitEffect_C.Get & Send Target Actor Data
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_Spell_HitEffect_C::Get___Send_Target_Actor_Data()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Spell_HitEffect_C", "Get & Send Target Actor Data");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Spell_HitEffect.BP_Spell_HitEffect_C.OnStartPlay
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FBlueprintParameters             Parameters                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// bool                                    bIsTargetAnActor                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           CasterActor                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    bDoesBeginInFirstPerson                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EVCastType                              CastType                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Magnitude                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Area                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Duration                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector_NetQuantizeNormal        ImpactNormal                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// struct FVector_NetQuantizeNormal        Normal                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// EVSpellLevel                            Level                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsTheEndOfTheEffect                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsMainEffect                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsSecondEffect                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           CollidedActor                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              CollidedComponent                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void ABP_Spell_HitEffect_C::OnStartPlay(const struct FBlueprintParameters& Parameters, bool bIsTargetAnActor, class AActor* CasterActor, bool bDoesBeginInFirstPerson, EVCastType CastType, int32 Magnitude, int32 Area, int32 Duration, const struct FVector_NetQuantizeNormal& ImpactNormal, const struct FVector_NetQuantizeNormal& Normal, EVSpellLevel Level, bool bIsTheEndOfTheEffect, bool bIsMainEffect, bool bIsSecondEffect, class AActor* CollidedActor, class UPrimitiveComponent* CollidedComponent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Spell_HitEffect_C", "OnStartPlay");

	Params::BP_Spell_HitEffect_C_OnStartPlay Parms{};

	Parms.Parameters = std::move(Parameters);
	Parms.bIsTargetAnActor = bIsTargetAnActor;
	Parms.CasterActor = CasterActor;
	Parms.bDoesBeginInFirstPerson = bDoesBeginInFirstPerson;
	Parms.CastType = CastType;
	Parms.Magnitude = Magnitude;
	Parms.Area = Area;
	Parms.Duration = Duration;
	Parms.ImpactNormal = std::move(ImpactNormal);
	Parms.Normal = std::move(Normal);
	Parms.Level = Level;
	Parms.bIsTheEndOfTheEffect = bIsTheEndOfTheEffect;
	Parms.bIsMainEffect = bIsMainEffect;
	Parms.bIsSecondEffect = bIsSecondEffect;
	Parms.CollidedActor = CollidedActor;
	Parms.CollidedComponent = CollidedComponent;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Spell_HitEffect.BP_Spell_HitEffect_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Spell_HitEffect_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Spell_HitEffect_C", "ReceiveTick");

	Params::BP_Spell_HitEffect_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Spell_HitEffect.BP_Spell_HitEffect_C.Select Accurate Niagara System Asset
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Spell_HitEffect_C::Select_Accurate_Niagara_System_Asset()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Spell_HitEffect_C", "Select Accurate Niagara System Asset");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Spell_HitEffect.BP_Spell_HitEffect_C.Spawn Impact Decal Blueprint
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_Spell_HitEffect_C::Spawn_Impact_Decal_Blueprint()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Spell_HitEffect_C", "Spawn Impact Decal Blueprint");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Spell_HitEffect.BP_Spell_HitEffect_C.Update & Send Target Actor Data
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_Spell_HitEffect_C::Update___Send_Target_Actor_Data()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Spell_HitEffect_C", "Update & Send Target Actor Data");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Spell_HitEffect.BP_Spell_HitEffect_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_Spell_HitEffect_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Spell_HitEffect_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

