#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TargetActor

#include "Basic.hpp"

#include "BP_TargetActor_classes.hpp"
#include "BP_TargetActor_parameters.hpp"


namespace SDK
{

// Function BP_TargetActor.BP_TargetActor_C.Evt_ChangeLightChannel
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Param_UseWorldLight                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_TargetActor_C::Evt_ChangeLightChannel(bool Param_UseWorldLight)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TargetActor_C", "Evt_ChangeLightChannel");

	Params::BP_TargetActor_C_Evt_ChangeLightChannel Parms{};

	Parms.Param_UseWorldLight = Param_UseWorldLight;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TargetActor.BP_TargetActor_C.Evt_InitalCameraAndLight
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Param_IsSM_                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_TargetActor_C::Evt_InitalCameraAndLight(bool Param_IsSM_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TargetActor_C", "Evt_InitalCameraAndLight");

	Params::BP_TargetActor_C_Evt_InitalCameraAndLight Parms{};

	Parms.Param_IsSM_ = Param_IsSM_;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TargetActor.BP_TargetActor_C.Evt_SpawnCenter
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Param_IsSM_                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Initial                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_TargetActor_C::Evt_SpawnCenter(bool Param_IsSM_, bool Initial)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TargetActor_C", "Evt_SpawnCenter");

	Params::BP_TargetActor_C_Evt_SpawnCenter Parms{};

	Parms.Param_IsSM_ = Param_IsSM_;
	Parms.Initial = Initial;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TargetActor.BP_TargetActor_C.Evt_UpdateCamera
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   RotationAdd_Z                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   RotationAdd_Y                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  ArmLengthAdd                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  Offset_X                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  Offset_Y                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Rotation_Light                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_TargetActor_C::Evt_UpdateCamera(float RotationAdd_Z, float RotationAdd_Y, double ArmLengthAdd, double Offset_X, double Offset_Y, float Rotation_Light)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TargetActor_C", "Evt_UpdateCamera");

	Params::BP_TargetActor_C_Evt_UpdateCamera Parms{};

	Parms.RotationAdd_Z = RotationAdd_Z;
	Parms.RotationAdd_Y = RotationAdd_Y;
	Parms.ArmLengthAdd = ArmLengthAdd;
	Parms.Offset_X = Offset_X;
	Parms.Offset_Y = Offset_Y;
	Parms.Rotation_Light = Rotation_Light;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TargetActor.BP_TargetActor_C.ExecuteUbergraph_BP_TargetActor
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_TargetActor_C::ExecuteUbergraph_BP_TargetActor(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TargetActor_C", "ExecuteUbergraph_BP_TargetActor");

	Params::BP_TargetActor_C_ExecuteUbergraph_BP_TargetActor Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TargetActor.BP_TargetActor_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_TargetActor_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TargetActor_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

