#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPCI_Spell_Fortify_Casting

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_Spell_Casting_classes.hpp"
#include "Altar_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPCI_Spell_Fortify_Casting.BPCI_Spell_Fortify_Casting_C
// 0x0060 (0x0BD0 - 0x0B70)
class ABPCI_Spell_Fortify_Casting_C final : public ABP_Spell_Casting_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BPCI_Spell_Fortify_Casting_C;       // 0x0B70(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	TMap<class FString, class FName>              Variant_List;                                      // 0x0B78(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void Child_Behavior__After_Setup();
	void ExecuteUbergraph_BPCI_Spell_Fortify_Casting(int32 EntryPoint);
	void OnStartPlay(const struct FBlueprintParameters& Parameters, bool bIsTargetAnActor, class AActor* CasterActor, bool bDoesBeginInFirstPerson, EVCastType CastType, int32 Magnitude, int32 Area, int32 Duration, const struct FVector_NetQuantizeNormal& ImpactNormal, const struct FVector_NetQuantizeNormal& Normal, EVSpellLevel Level, bool bIsTheEndOfTheEffect, bool bIsMainEffect, bool bIsSecondEffect, class AActor* CollidedActor, class UPrimitiveComponent* CollidedComponent);
	void Setup_Spell_Variant_Conditions(const TMap<class FString, class FName>& Naming_List);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPCI_Spell_Fortify_Casting_C">();
	}
	static class ABPCI_Spell_Fortify_Casting_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABPCI_Spell_Fortify_Casting_C>();
	}
};
static_assert(alignof(ABPCI_Spell_Fortify_Casting_C) == 0x000010, "Wrong alignment on ABPCI_Spell_Fortify_Casting_C");
static_assert(sizeof(ABPCI_Spell_Fortify_Casting_C) == 0x000BD0, "Wrong size on ABPCI_Spell_Fortify_Casting_C");
static_assert(offsetof(ABPCI_Spell_Fortify_Casting_C, UberGraphFrame_BPCI_Spell_Fortify_Casting_C) == 0x000B70, "Member 'ABPCI_Spell_Fortify_Casting_C::UberGraphFrame_BPCI_Spell_Fortify_Casting_C' has a wrong offset!");
static_assert(offsetof(ABPCI_Spell_Fortify_Casting_C, Variant_List) == 0x000B78, "Member 'ABPCI_Spell_Fortify_Casting_C::Variant_List' has a wrong offset!");

}

