#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPE_Candle_Type

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum BPE_Candle_Type.BPE_Candle_Type
// NumValues: 0x000C
enum class EBPE_Candle_Type : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator3                           = 2,
	NewEnumerator4                           = 3,
	NewEnumerator5                           = 4,
	NewEnumerator6                           = 5,
	NewEnumerator7                           = 6,
	NewEnumerator8                           = 7,
	NewEnumerator9                           = 8,
	NewEnumerator10                          = 9,
	NewEnumerator11                          = 10,
	BPE_Candle_MAX                           = 11,
};

}

