#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_Day_Night

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPI_Day_Night.BPI_Day_Night_C
// 0x0000 (0x0028 - 0x0028)
class IBPI_Day_Night_C final : public IInterface
{
public:
	void Set_Day();
	void Set_Night();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPI_Day_Night_C">();
	}
	static class IBPI_Day_Night_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_Day_Night_C>();
	}
};
static_assert(alignof(IBPI_Day_Night_C) == 0x000008, "Wrong alignment on IBPI_Day_Night_C");
static_assert(sizeof(IBPI_Day_Night_C) == 0x000028, "Wrong size on IBPI_Day_Night_C");

}

