#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Struct_EquipUnequip_Multiple

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct Struct_EquipUnequip_Multiple.Struct_EquipUnequip_Multiple
// 0x0020 (0x0020 - 0x0000)
struct FStruct_EquipUnequip_Multiple final
{
public:
	TArray<class UAnimSequenceBase*>              EquipAnim_5_23C0E7FC4F6749912E8926B63A799BEA;      // 0x0000(0x0010)(Edit, BlueprintVisible)
	TArray<class UAnimSequenceBase*>              UnequipAnim_6_68AFFDD241209AF4997241A528788317;    // 0x0010(0x0010)(Edit, BlueprintVisible)
};
static_assert(alignof(FStruct_EquipUnequip_Multiple) == 0x000008, "Wrong alignment on FStruct_EquipUnequip_Multiple");
static_assert(sizeof(FStruct_EquipUnequip_Multiple) == 0x000020, "Wrong size on FStruct_EquipUnequip_Multiple");
static_assert(offsetof(FStruct_EquipUnequip_Multiple, EquipAnim_5_23C0E7FC4F6749912E8926B63A799BEA) == 0x000000, "Member 'FStruct_EquipUnequip_Multiple::EquipAnim_5_23C0E7FC4F6749912E8926B63A799BEA' has a wrong offset!");
static_assert(offsetof(FStruct_EquipUnequip_Multiple, UnequipAnim_6_68AFFDD241209AF4997241A528788317) == 0x000010, "Member 'FStruct_EquipUnequip_Multiple::UnequipAnim_6_68AFFDD241209AF4997241A528788317' has a wrong offset!");

}

