#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TABP_Recoil_Multiple

#include "Basic.hpp"

#include "TABP_Recoil_Multiple_classes.hpp"
#include "TABP_Recoil_Multiple_parameters.hpp"


namespace SDK
{

// Function TABP_Recoil_Multiple.TABP_Recoil_Multiple_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        Param_AnimGraph                                        (Parm, OutParm, NoDestructor)

void UTABP_Recoil_Multiple_C::AnimGraph(struct FPoseLink* Param_AnimGraph)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TABP_Recoil_Multiple_C", "AnimGraph");

	Params::TABP_Recoil_Multiple_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_AnimGraph != nullptr)
		*Param_AnimGraph = std::move(Parms.Param_AnimGraph);
}


// Function TABP_Recoil_Multiple.TABP_Recoil_Multiple_C.ExecuteUbergraph_TABP_Recoil_Multiple
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTABP_Recoil_Multiple_C::ExecuteUbergraph_TABP_Recoil_Multiple(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TABP_Recoil_Multiple_C", "ExecuteUbergraph_TABP_Recoil_Multiple");

	Params::TABP_Recoil_Multiple_C_ExecuteUbergraph_TABP_Recoil_Multiple Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TABP_Recoil_Multiple.TABP_Recoil_Multiple_C.RecoilLayer
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink                        InPose                                                 (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink                        Param_RecoilLayer                                      (Parm, OutParm, NoDestructor)

void UTABP_Recoil_Multiple_C::RecoilLayer(const struct FPoseLink& InPose, struct FPoseLink* Param_RecoilLayer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TABP_Recoil_Multiple_C", "RecoilLayer");

	Params::TABP_Recoil_Multiple_C_RecoilLayer Parms{};

	Parms.InPose = std::move(InPose);

	UObject::ProcessEvent(Func, &Parms);

	if (Param_RecoilLayer != nullptr)
		*Param_RecoilLayer = std::move(Parms.Param_RecoilLayer);
}

}

