#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TABP_HitReact

#include "Basic.hpp"

#include "TABP_HitReact_classes.hpp"
#include "TABP_HitReact_parameters.hpp"


namespace SDK
{

// Function TABP_HitReact.TABP_HitReact_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        Param_AnimGraph                                        (Parm, OutParm, NoDestructor)

void UTABP_HitReact_C::AnimGraph(struct FPoseLink* Param_AnimGraph)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TABP_HitReact_C", "AnimGraph");

	Params::TABP_HitReact_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_AnimGraph != nullptr)
		*Param_AnimGraph = std::move(Parms.Param_AnimGraph);
}


// Function TABP_HitReact.TABP_HitReact_C.EvaluateGraphExposedInputs_ExecuteUbergraph_TABP_HitReact_AnimGraphNode_TransitionResult_644C9FF44594CDF8D28105B8F4CD72C2
// (BlueprintEvent)

void UTABP_HitReact_C::EvaluateGraphExposedInputs_ExecuteUbergraph_TABP_HitReact_AnimGraphNode_TransitionResult_644C9FF44594CDF8D28105B8F4CD72C2()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TABP_HitReact_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_TABP_HitReact_AnimGraphNode_TransitionResult_644C9FF44594CDF8D28105B8F4CD72C2");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TABP_HitReact.TABP_HitReact_C.ExecuteUbergraph_TABP_HitReact
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTABP_HitReact_C::ExecuteUbergraph_TABP_HitReact(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TABP_HitReact_C", "ExecuteUbergraph_TABP_HitReact");

	Params::TABP_HitReact_C_ExecuteUbergraph_TABP_HitReact Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TABP_HitReact.TABP_HitReact_C.HitReactLayer
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink                        InPose                                                 (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink                        Param_HitReactLayer                                    (Parm, OutParm, NoDestructor)

void UTABP_HitReact_C::HitReactLayer(const struct FPoseLink& InPose, struct FPoseLink* Param_HitReactLayer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TABP_HitReact_C", "HitReactLayer");

	Params::TABP_HitReact_C_HitReactLayer Parms{};

	Parms.InPose = std::move(InPose);

	UObject::ProcessEvent(Func, &Parms);

	if (Param_HitReactLayer != nullptr)
		*Param_HitReactLayer = std::move(Parms.Param_HitReactLayer);
}

}

