#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TABP_SpellCast_Multiple

#include "Basic.hpp"

#include "TABP_SpellCast_Multiple_classes.hpp"
#include "TABP_SpellCast_Multiple_parameters.hpp"


namespace SDK
{

// Function TABP_SpellCast_Multiple.TABP_SpellCast_Multiple_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        Param_AnimGraph                                        (Parm, OutParm, NoDestructor)

void UTABP_SpellCast_Multiple_C::AnimGraph(struct FPoseLink* Param_AnimGraph)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TABP_SpellCast_Multiple_C", "AnimGraph");

	Params::TABP_SpellCast_Multiple_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_AnimGraph != nullptr)
		*Param_AnimGraph = std::move(Parms.Param_AnimGraph);
}


// Function TABP_SpellCast_Multiple.TABP_SpellCast_Multiple_C.EvaluateGraphExposedInputs_ExecuteUbergraph_TABP_SpellCast_Multiple_AnimGraphNode_TransitionResult_2B1D0F52450BB7BC2CB786899621B87E
// (BlueprintEvent)

void UTABP_SpellCast_Multiple_C::EvaluateGraphExposedInputs_ExecuteUbergraph_TABP_SpellCast_Multiple_AnimGraphNode_TransitionResult_2B1D0F52450BB7BC2CB786899621B87E()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TABP_SpellCast_Multiple_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_TABP_SpellCast_Multiple_AnimGraphNode_TransitionResult_2B1D0F52450BB7BC2CB786899621B87E");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TABP_SpellCast_Multiple.TABP_SpellCast_Multiple_C.EvaluateGraphExposedInputs_ExecuteUbergraph_TABP_SpellCast_Multiple_AnimGraphNode_TransitionResult_2CA390CC4155BB1CB7578BA6A1B642E3
// (BlueprintEvent)

void UTABP_SpellCast_Multiple_C::EvaluateGraphExposedInputs_ExecuteUbergraph_TABP_SpellCast_Multiple_AnimGraphNode_TransitionResult_2CA390CC4155BB1CB7578BA6A1B642E3()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TABP_SpellCast_Multiple_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_TABP_SpellCast_Multiple_AnimGraphNode_TransitionResult_2CA390CC4155BB1CB7578BA6A1B642E3");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TABP_SpellCast_Multiple.TABP_SpellCast_Multiple_C.EvaluateGraphExposedInputs_ExecuteUbergraph_TABP_SpellCast_Multiple_AnimGraphNode_TransitionResult_5A2A8F3C40E988500F11EF8578606BAB
// (BlueprintEvent)

void UTABP_SpellCast_Multiple_C::EvaluateGraphExposedInputs_ExecuteUbergraph_TABP_SpellCast_Multiple_AnimGraphNode_TransitionResult_5A2A8F3C40E988500F11EF8578606BAB()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TABP_SpellCast_Multiple_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_TABP_SpellCast_Multiple_AnimGraphNode_TransitionResult_5A2A8F3C40E988500F11EF8578606BAB");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TABP_SpellCast_Multiple.TABP_SpellCast_Multiple_C.EvaluateGraphExposedInputs_ExecuteUbergraph_TABP_SpellCast_Multiple_AnimGraphNode_TransitionResult_61FA1789457FAAF7E474BBBC5080C7F2
// (BlueprintEvent)

void UTABP_SpellCast_Multiple_C::EvaluateGraphExposedInputs_ExecuteUbergraph_TABP_SpellCast_Multiple_AnimGraphNode_TransitionResult_61FA1789457FAAF7E474BBBC5080C7F2()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TABP_SpellCast_Multiple_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_TABP_SpellCast_Multiple_AnimGraphNode_TransitionResult_61FA1789457FAAF7E474BBBC5080C7F2");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TABP_SpellCast_Multiple.TABP_SpellCast_Multiple_C.EvaluateGraphExposedInputs_ExecuteUbergraph_TABP_SpellCast_Multiple_AnimGraphNode_TransitionResult_7ABDACD749F06BC39E88398BDA907EBC
// (BlueprintEvent)

void UTABP_SpellCast_Multiple_C::EvaluateGraphExposedInputs_ExecuteUbergraph_TABP_SpellCast_Multiple_AnimGraphNode_TransitionResult_7ABDACD749F06BC39E88398BDA907EBC()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TABP_SpellCast_Multiple_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_TABP_SpellCast_Multiple_AnimGraphNode_TransitionResult_7ABDACD749F06BC39E88398BDA907EBC");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TABP_SpellCast_Multiple.TABP_SpellCast_Multiple_C.EvaluateGraphExposedInputs_ExecuteUbergraph_TABP_SpellCast_Multiple_AnimGraphNode_TransitionResult_E8E67AFC4DAEAF828B57888098208411
// (BlueprintEvent)

void UTABP_SpellCast_Multiple_C::EvaluateGraphExposedInputs_ExecuteUbergraph_TABP_SpellCast_Multiple_AnimGraphNode_TransitionResult_E8E67AFC4DAEAF828B57888098208411()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TABP_SpellCast_Multiple_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_TABP_SpellCast_Multiple_AnimGraphNode_TransitionResult_E8E67AFC4DAEAF828B57888098208411");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TABP_SpellCast_Multiple.TABP_SpellCast_Multiple_C.ExecuteUbergraph_TABP_SpellCast_Multiple
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTABP_SpellCast_Multiple_C::ExecuteUbergraph_TABP_SpellCast_Multiple(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TABP_SpellCast_Multiple_C", "ExecuteUbergraph_TABP_SpellCast_Multiple");

	Params::TABP_SpellCast_Multiple_C_ExecuteUbergraph_TABP_SpellCast_Multiple Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TABP_SpellCast_Multiple.TABP_SpellCast_Multiple_C.SpellCastingLayer
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink                        Param_SpellCastingLayer                                (Parm, OutParm, NoDestructor)

void UTABP_SpellCast_Multiple_C::SpellCastingLayer(struct FPoseLink* Param_SpellCastingLayer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TABP_SpellCast_Multiple_C", "SpellCastingLayer");

	Params::TABP_SpellCast_Multiple_C_SpellCastingLayer Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_SpellCastingLayer != nullptr)
		*Param_SpellCastingLayer = std::move(Parms.Param_SpellCastingLayer);
}

}

