#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TABP_EnhancedLocomotionStanding

#include "Basic.hpp"

#include "TABP_EnhancedLocomotionStanding_classes.hpp"
#include "TABP_EnhancedLocomotionStanding_parameters.hpp"


namespace SDK
{

// Function TABP_EnhancedLocomotionStanding.TABP_EnhancedLocomotionStanding_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        Param_AnimGraph                                        (Parm, OutParm, NoDestructor)

void UTABP_EnhancedLocomotionStanding_C::AnimGraph(struct FPoseLink* Param_AnimGraph)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TABP_EnhancedLocomotionStanding_C", "AnimGraph");

	Params::TABP_EnhancedLocomotionStanding_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_AnimGraph != nullptr)
		*Param_AnimGraph = std::move(Parms.Param_AnimGraph);
}


// Function TABP_EnhancedLocomotionStanding.TABP_EnhancedLocomotionStanding_C.ExecuteUbergraph_TABP_EnhancedLocomotionStanding
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTABP_EnhancedLocomotionStanding_C::ExecuteUbergraph_TABP_EnhancedLocomotionStanding(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TABP_EnhancedLocomotionStanding_C", "ExecuteUbergraph_TABP_EnhancedLocomotionStanding");

	Params::TABP_EnhancedLocomotionStanding_C_ExecuteUbergraph_TABP_EnhancedLocomotionStanding Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TABP_EnhancedLocomotionStanding.TABP_EnhancedLocomotionStanding_C.StandingLayer
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink                        Param_StandingLayer                                    (Parm, OutParm, NoDestructor)

void UTABP_EnhancedLocomotionStanding_C::StandingLayer(struct FPoseLink* Param_StandingLayer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TABP_EnhancedLocomotionStanding_C", "StandingLayer");

	Params::TABP_EnhancedLocomotionStanding_C_StandingLayer Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_StandingLayer != nullptr)
		*Param_StandingLayer = std::move(Parms.Param_StandingLayer);
}

}

