#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TABP_Creature_Quadruped_LowerAndUpperBody

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK
{

// ScriptStruct TABP_Creature_Quadruped_LowerAndUpperBody.TABP_Creature_Quadruped_LowerAndUpperBody_C.AnimBlueprintGeneratedConstantData
// 0x00D7 (0x00D8 - 0x0001)
struct TABP_Creature_Quadruped_LowerAndUpperBody::FAnimBlueprintGeneratedConstantData final : public FAnimBlueprintConstantData
{
public:
	uint8                                         Pad_4B20[0x3];                                     // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   __NameProperty_29;                                 // 0x0004(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4B21[0x4];                                     // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnimNodeFunctionRef                   __StructProperty_30;                               // 0x0010(0x0020)(BlueprintVisible, NoDestructor)
	class FName                                   __NameProperty_31;                                 // 0x0030(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_32;                                 // 0x0038(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FAnimSubsystem_PropertyAccess          AnimBlueprintExtension_PropertyAccess;             // 0x0040(0x0080)()
	struct FAnimSubsystem_Base                    AnimBlueprintExtension_Base;                       // 0x00C0(0x0018)()
};
static_assert(alignof(TABP_Creature_Quadruped_LowerAndUpperBody::FAnimBlueprintGeneratedConstantData) == 0x000008, "Wrong alignment on TABP_Creature_Quadruped_LowerAndUpperBody::FAnimBlueprintGeneratedConstantData");
static_assert(sizeof(TABP_Creature_Quadruped_LowerAndUpperBody::FAnimBlueprintGeneratedConstantData) == 0x0000D8, "Wrong size on TABP_Creature_Quadruped_LowerAndUpperBody::FAnimBlueprintGeneratedConstantData");
static_assert(offsetof(TABP_Creature_Quadruped_LowerAndUpperBody::FAnimBlueprintGeneratedConstantData, __NameProperty_29) == 0x000004, "Member 'TABP_Creature_Quadruped_LowerAndUpperBody::FAnimBlueprintGeneratedConstantData::__NameProperty_29' has a wrong offset!");
static_assert(offsetof(TABP_Creature_Quadruped_LowerAndUpperBody::FAnimBlueprintGeneratedConstantData, __StructProperty_30) == 0x000010, "Member 'TABP_Creature_Quadruped_LowerAndUpperBody::FAnimBlueprintGeneratedConstantData::__StructProperty_30' has a wrong offset!");
static_assert(offsetof(TABP_Creature_Quadruped_LowerAndUpperBody::FAnimBlueprintGeneratedConstantData, __NameProperty_31) == 0x000030, "Member 'TABP_Creature_Quadruped_LowerAndUpperBody::FAnimBlueprintGeneratedConstantData::__NameProperty_31' has a wrong offset!");
static_assert(offsetof(TABP_Creature_Quadruped_LowerAndUpperBody::FAnimBlueprintGeneratedConstantData, __NameProperty_32) == 0x000038, "Member 'TABP_Creature_Quadruped_LowerAndUpperBody::FAnimBlueprintGeneratedConstantData::__NameProperty_32' has a wrong offset!");
static_assert(offsetof(TABP_Creature_Quadruped_LowerAndUpperBody::FAnimBlueprintGeneratedConstantData, AnimBlueprintExtension_PropertyAccess) == 0x000040, "Member 'TABP_Creature_Quadruped_LowerAndUpperBody::FAnimBlueprintGeneratedConstantData::AnimBlueprintExtension_PropertyAccess' has a wrong offset!");
static_assert(offsetof(TABP_Creature_Quadruped_LowerAndUpperBody::FAnimBlueprintGeneratedConstantData, AnimBlueprintExtension_Base) == 0x0000C0, "Member 'TABP_Creature_Quadruped_LowerAndUpperBody::FAnimBlueprintGeneratedConstantData::AnimBlueprintExtension_Base' has a wrong offset!");

// ScriptStruct TABP_Creature_Quadruped_LowerAndUpperBody.TABP_Creature_Quadruped_LowerAndUpperBody_C.AnimBlueprintGeneratedMutableData
// 0x0000 (0x0001 - 0x0001)
struct TABP_Creature_Quadruped_LowerAndUpperBody::FAnimBlueprintGeneratedMutableData final : public FAnimBlueprintMutableData
{
};
static_assert(alignof(TABP_Creature_Quadruped_LowerAndUpperBody::FAnimBlueprintGeneratedMutableData) == 0x000001, "Wrong alignment on TABP_Creature_Quadruped_LowerAndUpperBody::FAnimBlueprintGeneratedMutableData");
static_assert(sizeof(TABP_Creature_Quadruped_LowerAndUpperBody::FAnimBlueprintGeneratedMutableData) == 0x000001, "Wrong size on TABP_Creature_Quadruped_LowerAndUpperBody::FAnimBlueprintGeneratedMutableData");

}

