#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TABP_LocomotionStandingTurn

#include "Basic.hpp"

#include "AnimGraphRuntime_structs.hpp"
#include "Engine_structs.hpp"
#include "TABP_LocomotionStandingTurn_structs.hpp"
#include "Altar_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass TABP_LocomotionStandingTurn.TABP_LocomotionStandingTurn_C
// 0x0380 (0x0810 - 0x0490)
class UTABP_LocomotionStandingTurn_C final : public UVLocomotionStandTurnAnimInstance
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0490(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct TABP_LocomotionStandingTurn::FAnimBlueprintGeneratedMutableData __AnimBlueprintMutables;                           // 0x0498(0x0014)(HasGetValueTypeHash)
	uint8                                         Pad_447D[0x4];                                     // 0x04AC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_PropertyAccess;             // 0x04B0(0x0008)()
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_Base;                       // 0x04B8(0x0008)()
	struct FAnimNode_Root                         AnimGraphNode_Root_1;                              // 0x04C0(0x0020)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_1;                  // 0x04E0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult;                    // 0x0508(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_1;                    // 0x0530(0x0048)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer;                      // 0x0578(0x0048)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_1;                   // 0x05C0(0x0048)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_1;                       // 0x0608(0x0020)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer;                    // 0x0628(0x0070)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult;                         // 0x0698(0x0020)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine;                        // 0x06B8(0x00C8)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool;                     // 0x0780(0x0048)()
	struct FAnimNode_RefPose                      AnimGraphNode_LocalRefPose_1;                      // 0x07C8(0x0010)()
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x07D8(0x0020)()
	struct FAnimNode_RefPose                      AnimGraphNode_LocalRefPose;                        // 0x07F8(0x0010)()
	bool                                          K2Node_PropertyAccess_9;                           // 0x0808(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_PropertyAccess_7;                           // 0x0809(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_PropertyAccess_5;                           // 0x080A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_PropertyAccess;                             // 0x080B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void AnimGraph(struct FPoseLink* Param_AnimGraph);
	void ExecuteUbergraph_TABP_LocomotionStandingTurn(int32 EntryPoint);
	void StandingLayer(struct FPoseLink* Param_StandingLayer);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TABP_LocomotionStandingTurn_C">();
	}
	static class UTABP_LocomotionStandingTurn_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTABP_LocomotionStandingTurn_C>();
	}
};
static_assert(alignof(UTABP_LocomotionStandingTurn_C) == 0x000010, "Wrong alignment on UTABP_LocomotionStandingTurn_C");
static_assert(sizeof(UTABP_LocomotionStandingTurn_C) == 0x000810, "Wrong size on UTABP_LocomotionStandingTurn_C");
static_assert(offsetof(UTABP_LocomotionStandingTurn_C, UberGraphFrame) == 0x000490, "Member 'UTABP_LocomotionStandingTurn_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UTABP_LocomotionStandingTurn_C, __AnimBlueprintMutables) == 0x000498, "Member 'UTABP_LocomotionStandingTurn_C::__AnimBlueprintMutables' has a wrong offset!");
static_assert(offsetof(UTABP_LocomotionStandingTurn_C, AnimBlueprintExtension_PropertyAccess) == 0x0004B0, "Member 'UTABP_LocomotionStandingTurn_C::AnimBlueprintExtension_PropertyAccess' has a wrong offset!");
static_assert(offsetof(UTABP_LocomotionStandingTurn_C, AnimBlueprintExtension_Base) == 0x0004B8, "Member 'UTABP_LocomotionStandingTurn_C::AnimBlueprintExtension_Base' has a wrong offset!");
static_assert(offsetof(UTABP_LocomotionStandingTurn_C, AnimGraphNode_Root_1) == 0x0004C0, "Member 'UTABP_LocomotionStandingTurn_C::AnimGraphNode_Root_1' has a wrong offset!");
static_assert(offsetof(UTABP_LocomotionStandingTurn_C, AnimGraphNode_TransitionResult_1) == 0x0004E0, "Member 'UTABP_LocomotionStandingTurn_C::AnimGraphNode_TransitionResult_1' has a wrong offset!");
static_assert(offsetof(UTABP_LocomotionStandingTurn_C, AnimGraphNode_TransitionResult) == 0x000508, "Member 'UTABP_LocomotionStandingTurn_C::AnimGraphNode_TransitionResult' has a wrong offset!");
static_assert(offsetof(UTABP_LocomotionStandingTurn_C, AnimGraphNode_SequencePlayer_1) == 0x000530, "Member 'UTABP_LocomotionStandingTurn_C::AnimGraphNode_SequencePlayer_1' has a wrong offset!");
static_assert(offsetof(UTABP_LocomotionStandingTurn_C, AnimGraphNode_SequencePlayer) == 0x000578, "Member 'UTABP_LocomotionStandingTurn_C::AnimGraphNode_SequencePlayer' has a wrong offset!");
static_assert(offsetof(UTABP_LocomotionStandingTurn_C, AnimGraphNode_BlendListByBool_1) == 0x0005C0, "Member 'UTABP_LocomotionStandingTurn_C::AnimGraphNode_BlendListByBool_1' has a wrong offset!");
static_assert(offsetof(UTABP_LocomotionStandingTurn_C, AnimGraphNode_StateResult_1) == 0x000608, "Member 'UTABP_LocomotionStandingTurn_C::AnimGraphNode_StateResult_1' has a wrong offset!");
static_assert(offsetof(UTABP_LocomotionStandingTurn_C, AnimGraphNode_BlendSpacePlayer) == 0x000628, "Member 'UTABP_LocomotionStandingTurn_C::AnimGraphNode_BlendSpacePlayer' has a wrong offset!");
static_assert(offsetof(UTABP_LocomotionStandingTurn_C, AnimGraphNode_StateResult) == 0x000698, "Member 'UTABP_LocomotionStandingTurn_C::AnimGraphNode_StateResult' has a wrong offset!");
static_assert(offsetof(UTABP_LocomotionStandingTurn_C, AnimGraphNode_StateMachine) == 0x0006B8, "Member 'UTABP_LocomotionStandingTurn_C::AnimGraphNode_StateMachine' has a wrong offset!");
static_assert(offsetof(UTABP_LocomotionStandingTurn_C, AnimGraphNode_BlendListByBool) == 0x000780, "Member 'UTABP_LocomotionStandingTurn_C::AnimGraphNode_BlendListByBool' has a wrong offset!");
static_assert(offsetof(UTABP_LocomotionStandingTurn_C, AnimGraphNode_LocalRefPose_1) == 0x0007C8, "Member 'UTABP_LocomotionStandingTurn_C::AnimGraphNode_LocalRefPose_1' has a wrong offset!");
static_assert(offsetof(UTABP_LocomotionStandingTurn_C, AnimGraphNode_Root) == 0x0007D8, "Member 'UTABP_LocomotionStandingTurn_C::AnimGraphNode_Root' has a wrong offset!");
static_assert(offsetof(UTABP_LocomotionStandingTurn_C, AnimGraphNode_LocalRefPose) == 0x0007F8, "Member 'UTABP_LocomotionStandingTurn_C::AnimGraphNode_LocalRefPose' has a wrong offset!");
static_assert(offsetof(UTABP_LocomotionStandingTurn_C, K2Node_PropertyAccess_9) == 0x000808, "Member 'UTABP_LocomotionStandingTurn_C::K2Node_PropertyAccess_9' has a wrong offset!");
static_assert(offsetof(UTABP_LocomotionStandingTurn_C, K2Node_PropertyAccess_7) == 0x000809, "Member 'UTABP_LocomotionStandingTurn_C::K2Node_PropertyAccess_7' has a wrong offset!");
static_assert(offsetof(UTABP_LocomotionStandingTurn_C, K2Node_PropertyAccess_5) == 0x00080A, "Member 'UTABP_LocomotionStandingTurn_C::K2Node_PropertyAccess_5' has a wrong offset!");
static_assert(offsetof(UTABP_LocomotionStandingTurn_C, K2Node_PropertyAccess) == 0x00080B, "Member 'UTABP_LocomotionStandingTurn_C::K2Node_PropertyAccess' has a wrong offset!");

}

