#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TABP_TurnInPlaceCreature

#include "Basic.hpp"

#include "TABP_TurnInPlaceCreature_classes.hpp"
#include "TABP_TurnInPlaceCreature_parameters.hpp"


namespace SDK
{

// Function TABP_TurnInPlaceCreature.TABP_TurnInPlaceCreature_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        Param_AnimGraph                                        (Parm, OutParm, NoDestructor)

void UTABP_TurnInPlaceCreature_C::AnimGraph(struct FPoseLink* Param_AnimGraph)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TABP_TurnInPlaceCreature_C", "AnimGraph");

	Params::TABP_TurnInPlaceCreature_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_AnimGraph != nullptr)
		*Param_AnimGraph = std::move(Parms.Param_AnimGraph);
}


// Function TABP_TurnInPlaceCreature.TABP_TurnInPlaceCreature_C.ExecuteUbergraph_TABP_TurnInPlaceCreature
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTABP_TurnInPlaceCreature_C::ExecuteUbergraph_TABP_TurnInPlaceCreature(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TABP_TurnInPlaceCreature_C", "ExecuteUbergraph_TABP_TurnInPlaceCreature");

	Params::TABP_TurnInPlaceCreature_C_ExecuteUbergraph_TABP_TurnInPlaceCreature Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TABP_TurnInPlaceCreature.TABP_TurnInPlaceCreature_C.TurnInPlaceLayer
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink                        InPose                                                 (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink                        Param_TurnInPlaceLayer                                 (Parm, OutParm, NoDestructor)

void UTABP_TurnInPlaceCreature_C::TurnInPlaceLayer(const struct FPoseLink& InPose, struct FPoseLink* Param_TurnInPlaceLayer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TABP_TurnInPlaceCreature_C", "TurnInPlaceLayer");

	Params::TABP_TurnInPlaceCreature_C_TurnInPlaceLayer Parms{};

	Parms.InPose = std::move(InPose);

	UObject::ProcessEvent(Func, &Parms);

	if (Param_TurnInPlaceLayer != nullptr)
		*Param_TurnInPlaceLayer = std::move(Parms.Param_TurnInPlaceLayer);
}

}

