#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TABP_FeetIK_Humanoid

#include "Basic.hpp"

#include "TABP_FeetIK_Humanoid_classes.hpp"
#include "TABP_FeetIK_Humanoid_parameters.hpp"


namespace SDK
{

// Function TABP_FeetIK_Humanoid.TABP_FeetIK_Humanoid_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        Param_AnimGraph                                        (Parm, OutParm, NoDestructor)

void UTABP_FeetIK_Humanoid_C::AnimGraph(struct FPoseLink* Param_AnimGraph)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TABP_FeetIK_Humanoid_C", "AnimGraph");

	Params::TABP_FeetIK_Humanoid_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_AnimGraph != nullptr)
		*Param_AnimGraph = std::move(Parms.Param_AnimGraph);
}


// Function TABP_FeetIK_Humanoid.TABP_FeetIK_Humanoid_C.ExecuteUbergraph_TABP_FeetIK_Humanoid
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTABP_FeetIK_Humanoid_C::ExecuteUbergraph_TABP_FeetIK_Humanoid(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TABP_FeetIK_Humanoid_C", "ExecuteUbergraph_TABP_FeetIK_Humanoid");

	Params::TABP_FeetIK_Humanoid_C_ExecuteUbergraph_TABP_FeetIK_Humanoid Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TABP_FeetIK_Humanoid.TABP_FeetIK_Humanoid_C.FeetIKLayer
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink                        AnimationPose                                          (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink                        Param_FeetIKLayer                                      (Parm, OutParm, NoDestructor)

void UTABP_FeetIK_Humanoid_C::FeetIKLayer(const struct FPoseLink& AnimationPose, struct FPoseLink* Param_FeetIKLayer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TABP_FeetIK_Humanoid_C", "FeetIKLayer");

	Params::TABP_FeetIK_Humanoid_C_FeetIKLayer Parms{};

	Parms.AnimationPose = std::move(AnimationPose);

	UObject::ProcessEvent(Func, &Parms);

	if (Param_FeetIKLayer != nullptr)
		*Param_FeetIKLayer = std::move(Parms.Param_FeetIKLayer);
}

}

