#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TABP_LookAt

#include "Basic.hpp"

#include "TABP_LookAt_classes.hpp"
#include "TABP_LookAt_parameters.hpp"


namespace SDK
{

// Function TABP_LookAt.TABP_LookAt_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        Param_AnimGraph                                        (Parm, OutParm, NoDestructor)

void UTABP_LookAt_C::AnimGraph(struct FPoseLink* Param_AnimGraph)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TABP_LookAt_C", "AnimGraph");

	Params::TABP_LookAt_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_AnimGraph != nullptr)
		*Param_AnimGraph = std::move(Parms.Param_AnimGraph);
}


// Function TABP_LookAt.TABP_LookAt_C.EvaluateGraphExposedInputs_ExecuteUbergraph_TABP_LookAt_AnimGraphNode_AdvancedLookAt_A0FAD3894A8BA22925668A80995EC038
// (BlueprintEvent)

void UTABP_LookAt_C::EvaluateGraphExposedInputs_ExecuteUbergraph_TABP_LookAt_AnimGraphNode_AdvancedLookAt_A0FAD3894A8BA22925668A80995EC038()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TABP_LookAt_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_TABP_LookAt_AnimGraphNode_AdvancedLookAt_A0FAD3894A8BA22925668A80995EC038");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TABP_LookAt.TABP_LookAt_C.ExecuteUbergraph_TABP_LookAt
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTABP_LookAt_C::ExecuteUbergraph_TABP_LookAt(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TABP_LookAt_C", "ExecuteUbergraph_TABP_LookAt");

	Params::TABP_LookAt_C_ExecuteUbergraph_TABP_LookAt Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TABP_LookAt.TABP_LookAt_C.LookAtLayer
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink                        AnimationPose                                          (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink                        Param_LookAtLayer                                      (Parm, OutParm, NoDestructor)

void UTABP_LookAt_C::LookAtLayer(const struct FPoseLink& AnimationPose, struct FPoseLink* Param_LookAtLayer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TABP_LookAt_C", "LookAtLayer");

	Params::TABP_LookAt_C_LookAtLayer Parms{};

	Parms.AnimationPose = std::move(AnimationPose);

	UObject::ProcessEvent(Func, &Parms);

	if (Param_LookAtLayer != nullptr)
		*Param_LookAtLayer = std::move(Parms.Param_LookAtLayer);
}

}

