#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ModernMenu_Added_Effects_List

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Altar_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_ModernMenu_Added_Effects_List.WBP_ModernMenu_Added_Effects_List_C
// 0x0050 (0x0518 - 0x04C8)
class UWBP_ModernMenu_Added_Effects_List_C final : public UVAltarWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UVAddedEffectsListViewModel*            VAddedEffectsListViewModel;                        // 0x04D0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, DisableEditOnInstance, DuplicateTransient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWBP_NavigableScrollBox_SigilStoneMenu_C* NavigableEffectList;                               // 0x04D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	FMulticastInlineDelegateProperty_             OnItemClicked;                                     // 0x04E0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	FMulticastInlineDelegateProperty_             OnListUpdated;                                     // 0x04F0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	bool                                          bEntryShouldCollapsedOnUnfocus;                    // 0x0500(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bScrollOnRS;                                       // 0x0501(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3ECC[0x6];                                     // 0x0502(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	FMulticastInlineDelegateProperty_             OnItemClickReleased;                               // 0x0508(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void Construct();
	void CreateEffectItemList(const TArray<struct FModernEffectItemData>& NewItems);
	void DoScroll(double Scroll_Delta);
	void ExecuteUbergraph_WBP_ModernMenu_Added_Effects_List(int32 EntryPoint);
	void OnFocus();
	void OnItemClicked__DelegateSignature(const struct FModernEffectItemData& Item_Clicked);
	void OnItemClickReleased__DelegateSignature(const struct FModernEffectItemData& ItemClickReleased);
	void OnItemListClick(const struct FModernEffectItemData& EffectItemProperty);
	void OnItemListClickRelease(const struct FModernEffectItemData& NewParam);
	void OnListUpdated__DelegateSignature();
	void UpdateListView(const TArray<struct FModernEffectItemData>& NewItems);

	class UWidget* BP_GetDesiredFocusTarget() const;
	bool IsNavigatable() const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_ModernMenu_Added_Effects_List_C">();
	}
	static class UWBP_ModernMenu_Added_Effects_List_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_ModernMenu_Added_Effects_List_C>();
	}
};
static_assert(alignof(UWBP_ModernMenu_Added_Effects_List_C) == 0x000008, "Wrong alignment on UWBP_ModernMenu_Added_Effects_List_C");
static_assert(sizeof(UWBP_ModernMenu_Added_Effects_List_C) == 0x000518, "Wrong size on UWBP_ModernMenu_Added_Effects_List_C");
static_assert(offsetof(UWBP_ModernMenu_Added_Effects_List_C, UberGraphFrame) == 0x0004C8, "Member 'UWBP_ModernMenu_Added_Effects_List_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_ModernMenu_Added_Effects_List_C, VAddedEffectsListViewModel) == 0x0004D0, "Member 'UWBP_ModernMenu_Added_Effects_List_C::VAddedEffectsListViewModel' has a wrong offset!");
static_assert(offsetof(UWBP_ModernMenu_Added_Effects_List_C, NavigableEffectList) == 0x0004D8, "Member 'UWBP_ModernMenu_Added_Effects_List_C::NavigableEffectList' has a wrong offset!");
static_assert(offsetof(UWBP_ModernMenu_Added_Effects_List_C, OnItemClicked) == 0x0004E0, "Member 'UWBP_ModernMenu_Added_Effects_List_C::OnItemClicked' has a wrong offset!");
static_assert(offsetof(UWBP_ModernMenu_Added_Effects_List_C, OnListUpdated) == 0x0004F0, "Member 'UWBP_ModernMenu_Added_Effects_List_C::OnListUpdated' has a wrong offset!");
static_assert(offsetof(UWBP_ModernMenu_Added_Effects_List_C, bEntryShouldCollapsedOnUnfocus) == 0x000500, "Member 'UWBP_ModernMenu_Added_Effects_List_C::bEntryShouldCollapsedOnUnfocus' has a wrong offset!");
static_assert(offsetof(UWBP_ModernMenu_Added_Effects_List_C, bScrollOnRS) == 0x000501, "Member 'UWBP_ModernMenu_Added_Effects_List_C::bScrollOnRS' has a wrong offset!");
static_assert(offsetof(UWBP_ModernMenu_Added_Effects_List_C, OnItemClickReleased) == 0x000508, "Member 'UWBP_ModernMenu_Added_Effects_List_C::OnItemClickReleased' has a wrong offset!");

}

