#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Modern_Onboarding_Gameplay

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Altar_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Modern_Onboarding_Gameplay.WBP_Modern_Onboarding_Gameplay_C
// 0x0060 (0x0558 - 0x04F8)
class UWBP_Modern_Onboarding_Gameplay_C final : public UVModernOnboardingPage
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04F8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UVFooterViewModel*                      VFooterViewModel;                                  // 0x0500(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, DisableEditOnInstance, DuplicateTransient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       ExitAnimation;                                     // 0x0508(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       EnterAnimation;                                    // 0x0510(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWBP_MainMenu_Button_Wrapper_C*         ContinueButton;                                    // 0x0518(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Modern_Settings_StepsWidget_C*     DifficultyModeStep;                                // 0x0520(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Modern_Menu_Player_Footer_C*       Footer;                                            // 0x0528(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_AltarTextBlock_C*                  PageLabel;                                         // 0x0530(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Modern_Settings_StepsWidget_C*     ToggleAdaptiveTrigger;                             // 0x0538(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Modern_Settings_StepsWidget_C*     ToggleVibrationStep;                               // 0x0540(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Modern_Settings_StepsWidget_C*     VibrationStrenghtStep;                             // 0x0548(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	bool                                          IsConfirmed;                                       // 0x0550(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsStartAnimationFinished;                          // 0x0551(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsEndAnimationFinished;                            // 0x0552(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void BndEvt__WBP_Modern_Onboarding_Gameplay_ContinueButton_K2Node_ComponentBoundEvent_1_OnClick__DelegateSignature(class UCommonButtonBase* Button);
	bool BP_OnHandleBackAction();
	void Construct();
	void ExecuteUbergraph_WBP_Modern_Onboarding_Gameplay(int32 EntryPoint);
	void GetDifficultyModeRow(struct FModernSettingTableRow* Row);
	void GetMissingStep(const class FText& MissingText, struct FModernSettingTableRow* ModernSettingTableRow);
	void GetToggleAdaptiveTrigger(struct FModernSettingTableRow* Row);
	void GetToggleVibrationRow(struct FModernSettingTableRow* Row);
	void GetVibrationStrengthRow(struct FModernSettingTableRow* Row);
	void InitFooter();
	void InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_0(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction);
	void InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_1(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction);
	void InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_2(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction);
	void InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_3(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction);
	void InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_4(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction);
	void InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_5(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction);
	void InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_6(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction);
	void InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_7(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction);
	void LaunchEnterAnimation();
	void LaunchExitAnimation();
	void OnEnterAnimationEnded();
	void OnExit(bool Forward);
	void OnExitAnimationEnded();
	void OnFocus();
	void PreConstruct(bool IsDesignTime);
	void Reset();
	void ResetAllSettings();
	void SaveAllSettings();
	void SelectTitle();
	void SetupDifficultyModeStep();
	void SetupToggleAdaptiveTrigger();
	void SetupToggleVibrationStep();
	void SetupVibrationStrengthSlider();
	void This_Is_For_Plugin_Compliance(bool NewParam);

	class UWidget* BP_GetDesiredFocusTarget() const;
	bool CanBeSkiped() const;
	bool CanEnter() const;
	bool CanExit() const;
	bool DoesNeedEnterAnimation() const;
	bool DoesNeedExitAnimation() const;
	void GetFirstFocussableElement(class UVAltarWidget** Widget) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Modern_Onboarding_Gameplay_C">();
	}
	static class UWBP_Modern_Onboarding_Gameplay_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Modern_Onboarding_Gameplay_C>();
	}
};
static_assert(alignof(UWBP_Modern_Onboarding_Gameplay_C) == 0x000008, "Wrong alignment on UWBP_Modern_Onboarding_Gameplay_C");
static_assert(sizeof(UWBP_Modern_Onboarding_Gameplay_C) == 0x000558, "Wrong size on UWBP_Modern_Onboarding_Gameplay_C");
static_assert(offsetof(UWBP_Modern_Onboarding_Gameplay_C, UberGraphFrame) == 0x0004F8, "Member 'UWBP_Modern_Onboarding_Gameplay_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_Modern_Onboarding_Gameplay_C, VFooterViewModel) == 0x000500, "Member 'UWBP_Modern_Onboarding_Gameplay_C::VFooterViewModel' has a wrong offset!");
static_assert(offsetof(UWBP_Modern_Onboarding_Gameplay_C, ExitAnimation) == 0x000508, "Member 'UWBP_Modern_Onboarding_Gameplay_C::ExitAnimation' has a wrong offset!");
static_assert(offsetof(UWBP_Modern_Onboarding_Gameplay_C, EnterAnimation) == 0x000510, "Member 'UWBP_Modern_Onboarding_Gameplay_C::EnterAnimation' has a wrong offset!");
static_assert(offsetof(UWBP_Modern_Onboarding_Gameplay_C, ContinueButton) == 0x000518, "Member 'UWBP_Modern_Onboarding_Gameplay_C::ContinueButton' has a wrong offset!");
static_assert(offsetof(UWBP_Modern_Onboarding_Gameplay_C, DifficultyModeStep) == 0x000520, "Member 'UWBP_Modern_Onboarding_Gameplay_C::DifficultyModeStep' has a wrong offset!");
static_assert(offsetof(UWBP_Modern_Onboarding_Gameplay_C, Footer) == 0x000528, "Member 'UWBP_Modern_Onboarding_Gameplay_C::Footer' has a wrong offset!");
static_assert(offsetof(UWBP_Modern_Onboarding_Gameplay_C, PageLabel) == 0x000530, "Member 'UWBP_Modern_Onboarding_Gameplay_C::PageLabel' has a wrong offset!");
static_assert(offsetof(UWBP_Modern_Onboarding_Gameplay_C, ToggleAdaptiveTrigger) == 0x000538, "Member 'UWBP_Modern_Onboarding_Gameplay_C::ToggleAdaptiveTrigger' has a wrong offset!");
static_assert(offsetof(UWBP_Modern_Onboarding_Gameplay_C, ToggleVibrationStep) == 0x000540, "Member 'UWBP_Modern_Onboarding_Gameplay_C::ToggleVibrationStep' has a wrong offset!");
static_assert(offsetof(UWBP_Modern_Onboarding_Gameplay_C, VibrationStrenghtStep) == 0x000548, "Member 'UWBP_Modern_Onboarding_Gameplay_C::VibrationStrenghtStep' has a wrong offset!");
static_assert(offsetof(UWBP_Modern_Onboarding_Gameplay_C, IsConfirmed) == 0x000550, "Member 'UWBP_Modern_Onboarding_Gameplay_C::IsConfirmed' has a wrong offset!");
static_assert(offsetof(UWBP_Modern_Onboarding_Gameplay_C, IsStartAnimationFinished) == 0x000551, "Member 'UWBP_Modern_Onboarding_Gameplay_C::IsStartAnimationFinished' has a wrong offset!");
static_assert(offsetof(UWBP_Modern_Onboarding_Gameplay_C, IsEndAnimationFinished) == 0x000552, "Member 'UWBP_Modern_Onboarding_Gameplay_C::IsEndAnimationFinished' has a wrong offset!");

}

