#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Modern_Onboarding_HDRScreen

#include "Basic.hpp"

#include "Altar_structs.hpp"
#include "EnhancedInput_structs.hpp"


namespace SDK::Params
{

// Function WBP_Modern_Onboarding_HDRScreen.WBP_Modern_Onboarding_HDRScreen_C.BndEvt__WBP_Modern_Onboarding_HDRScreen_ContinueButton_K2Node_ComponentBoundEvent_0_OnClick__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct WBP_Modern_Onboarding_HDRScreen_C_BndEvt__WBP_Modern_Onboarding_HDRScreen_ContinueButton_K2Node_ComponentBoundEvent_0_OnClick__DelegateSignature final
{
public:
	class UCommonButtonBase*                      Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Modern_Onboarding_HDRScreen_C_BndEvt__WBP_Modern_Onboarding_HDRScreen_ContinueButton_K2Node_ComponentBoundEvent_0_OnClick__DelegateSignature) == 0x000008, "Wrong alignment on WBP_Modern_Onboarding_HDRScreen_C_BndEvt__WBP_Modern_Onboarding_HDRScreen_ContinueButton_K2Node_ComponentBoundEvent_0_OnClick__DelegateSignature");
static_assert(sizeof(WBP_Modern_Onboarding_HDRScreen_C_BndEvt__WBP_Modern_Onboarding_HDRScreen_ContinueButton_K2Node_ComponentBoundEvent_0_OnClick__DelegateSignature) == 0x000008, "Wrong size on WBP_Modern_Onboarding_HDRScreen_C_BndEvt__WBP_Modern_Onboarding_HDRScreen_ContinueButton_K2Node_ComponentBoundEvent_0_OnClick__DelegateSignature");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_BndEvt__WBP_Modern_Onboarding_HDRScreen_ContinueButton_K2Node_ComponentBoundEvent_0_OnClick__DelegateSignature, Button) == 0x000000, "Member 'WBP_Modern_Onboarding_HDRScreen_C_BndEvt__WBP_Modern_Onboarding_HDRScreen_ContinueButton_K2Node_ComponentBoundEvent_0_OnClick__DelegateSignature::Button' has a wrong offset!");

// Function WBP_Modern_Onboarding_HDRScreen.WBP_Modern_Onboarding_HDRScreen_C.BP_OnHandleBackAction
// 0x0004 (0x0004 - 0x0000)
struct WBP_Modern_Onboarding_HDRScreen_C_BP_OnHandleBackAction final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetIsFocussed_ReturnValue;                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Back_ReturnValue;                         // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Modern_Onboarding_HDRScreen_C_BP_OnHandleBackAction) == 0x000001, "Wrong alignment on WBP_Modern_Onboarding_HDRScreen_C_BP_OnHandleBackAction");
static_assert(sizeof(WBP_Modern_Onboarding_HDRScreen_C_BP_OnHandleBackAction) == 0x000004, "Wrong size on WBP_Modern_Onboarding_HDRScreen_C_BP_OnHandleBackAction");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_BP_OnHandleBackAction, ReturnValue) == 0x000000, "Member 'WBP_Modern_Onboarding_HDRScreen_C_BP_OnHandleBackAction::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_BP_OnHandleBackAction, CallFunc_GetIsFocussed_ReturnValue) == 0x000001, "Member 'WBP_Modern_Onboarding_HDRScreen_C_BP_OnHandleBackAction::CallFunc_GetIsFocussed_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_BP_OnHandleBackAction, CallFunc_Back_ReturnValue) == 0x000002, "Member 'WBP_Modern_Onboarding_HDRScreen_C_BP_OnHandleBackAction::CallFunc_Back_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_BP_OnHandleBackAction, CallFunc_IsValid_ReturnValue) == 0x000003, "Member 'WBP_Modern_Onboarding_HDRScreen_C_BP_OnHandleBackAction::CallFunc_IsValid_ReturnValue' has a wrong offset!");

// Function WBP_Modern_Onboarding_HDRScreen.WBP_Modern_Onboarding_HDRScreen_C.ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen
// 0x02E0 (0x02E0 - 0x0000)
struct WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4694[0x4];                                     // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FInputActionValue                      K2Node_EnhancedInputActionEvent_ActionValue_5;     // 0x0008(0x0020)(NoDestructor)
	float                                         K2Node_EnhancedInputActionEvent_ElapsedTime_5;     // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_EnhancedInputActionEvent_TriggeredTime_5;   // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	const class UInputAction*                     K2Node_EnhancedInputActionEvent_SourceAction_5;    // 0x0030(0x0008)(ConstParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FInputActionValue                      K2Node_EnhancedInputActionEvent_ActionValue_4;     // 0x0038(0x0020)(NoDestructor)
	float                                         K2Node_EnhancedInputActionEvent_ElapsedTime_4;     // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_EnhancedInputActionEvent_TriggeredTime_4;   // 0x005C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	const class UInputAction*                     K2Node_EnhancedInputActionEvent_SourceAction_4;    // 0x0060(0x0008)(ConstParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Conv_InputActionValueToBool_ReturnValue;  // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Conv_InputActionValueToBool_ReturnValue_1; // 0x0069(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4695[0x6];                                     // 0x006A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UInputAction*                           Temp_object_Variable;                              // 0x0070(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable;                                // 0x0078(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_0;                              // 0x0080(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_1;                              // 0x0088(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_1;                              // 0x0090(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0098(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4696[0x7];                                     // 0x0099(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        Temp_real_Variable_1_0;                            // 0x00A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_1_1;                            // 0x00A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FInputActionValue                      K2Node_EnhancedInputActionEvent_ActionValue_3;     // 0x00B0(0x0020)(NoDestructor)
	float                                         K2Node_EnhancedInputActionEvent_ElapsedTime_3;     // 0x00D0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_EnhancedInputActionEvent_TriggeredTime_3;   // 0x00D4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	const class UInputAction*                     K2Node_EnhancedInputActionEvent_SourceAction_3;    // 0x00D8(0x0008)(ConstParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FInputActionValue                      K2Node_EnhancedInputActionEvent_ActionValue_2;     // 0x00E0(0x0020)(NoDestructor)
	float                                         K2Node_EnhancedInputActionEvent_ElapsedTime_2;     // 0x0100(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_EnhancedInputActionEvent_TriggeredTime_2;   // 0x0104(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	const class UInputAction*                     K2Node_EnhancedInputActionEvent_SourceAction_2;    // 0x0108(0x0008)(ConstParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Conv_InputActionValueToBool_ReturnValue_2; // 0x0110(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Conv_InputActionValueToBool_ReturnValue_3; // 0x0111(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4697[0x6];                                     // 0x0112(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FInputActionValue                      K2Node_EnhancedInputActionEvent_ActionValue_1;     // 0x0118(0x0020)(NoDestructor)
	float                                         K2Node_EnhancedInputActionEvent_ElapsedTime_1;     // 0x0138(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_EnhancedInputActionEvent_TriggeredTime_1;   // 0x013C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	const class UInputAction*                     K2Node_EnhancedInputActionEvent_SourceAction_1;    // 0x0140(0x0008)(ConstParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FInputActionValue                      K2Node_EnhancedInputActionEvent_ActionValue;       // 0x0148(0x0020)(NoDestructor)
	float                                         K2Node_EnhancedInputActionEvent_ElapsedTime;       // 0x0168(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_EnhancedInputActionEvent_TriggeredTime;     // 0x016C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	const class UInputAction*                     K2Node_EnhancedInputActionEvent_SourceAction;      // 0x0170(0x0008)(ConstParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Conv_InputActionValueToBool_ReturnValue_4; // 0x0178(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Conv_InputActionValueToBool_ReturnValue_5; // 0x0179(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4698[0x6];                                     // 0x017A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UInputAction*                           Temp_object_Variable_1;                            // 0x0180(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_2;                              // 0x0188(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_2_0;                            // 0x0190(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_2_1;                            // 0x0198(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_2_2;                            // 0x01A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_2_3;                            // 0x01A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_3;                              // 0x01B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_1;                              // 0x01B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4699[0x7];                                     // 0x01B9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        Temp_real_Variable_3_0;                            // 0x01C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_3_1;                            // 0x01C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_3_2;                            // 0x01D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_3_3;                            // 0x01D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UVUINavigationGlobalSubsystem*          CallFunc_GetGameInstanceSubsystem_ReturnValue;     // 0x01E0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IVEnhancedInputNavigable> CallFunc_NavigateToWidget_Widget_CastInput;        // 0x01E8(0x0010)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x01F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_469A[0x7];                                     // 0x01F9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0200(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue_1;              // 0x0208(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_forward;                              // 0x0210(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_469B[0x7];                                     // 0x0211(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonButtonBase*                      K2Node_ComponentBoundEvent_Button;                 // 0x0218(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0220(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Skip_ReturnValue;                         // 0x0221(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_469C[0x6];                                     // 0x0222(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UVUINavigationGlobalSubsystem*          CallFunc_GetGameInstanceSubsystem_ReturnValue_1;   // 0x0228(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IVEnhancedInputNavigable> CallFunc_NavigateToWidget_Widget_CastInput_1;      // 0x0230(0x0010)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          CallFunc_GetIsFocussed_ReturnValue;                // 0x0240(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetIsFocussed_ReturnValue_1;              // 0x0241(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetIsFocussed_ReturnValue_2;              // 0x0242(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetIsFocussed_ReturnValue_3;              // 0x0243(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetIsFocussed_ReturnValue_4;              // 0x0244(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetIsFocussed_ReturnValue_5;              // 0x0245(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetIsFocussed_ReturnValue_6;              // 0x0246(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetIsFocussed_ReturnValue_7;              // 0x0247(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FInputActionValue                      K2Node_EnhancedInputActionEvent_ActionValue_6;     // 0x0248(0x0020)(NoDestructor)
	float                                         K2Node_EnhancedInputActionEvent_ElapsedTime_6;     // 0x0268(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_EnhancedInputActionEvent_TriggeredTime_6;   // 0x026C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	const class UInputAction*                     K2Node_EnhancedInputActionEvent_SourceAction_6;    // 0x0270(0x0008)(ConstParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetIsEnabled_ReturnValue;                 // 0x0278(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_469D[0x7];                                     // 0x0279(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        Temp_real_Variable_2;                              // 0x0280(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_1_2;                            // 0x0288(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Conv_InputActionValueToBool_ReturnValue_6; // 0x0290(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_469E[0x7];                                     // 0x0291(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FInputActionValue                      K2Node_EnhancedInputActionEvent_ActionValue_7;     // 0x0298(0x0020)(NoDestructor)
	float                                         K2Node_EnhancedInputActionEvent_ElapsedTime_7;     // 0x02B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_EnhancedInputActionEvent_TriggeredTime_7;   // 0x02BC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	const class UInputAction*                     K2Node_EnhancedInputActionEvent_SourceAction_7;    // 0x02C0(0x0008)(ConstParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_3;                              // 0x02C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_1_3;                            // 0x02D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Conv_InputActionValueToBool_ReturnValue_7; // 0x02D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen) == 0x000008, "Wrong alignment on WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen");
static_assert(sizeof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen) == 0x0002E0, "Wrong size on WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, EntryPoint) == 0x000000, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, K2Node_EnhancedInputActionEvent_ActionValue_5) == 0x000008, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::K2Node_EnhancedInputActionEvent_ActionValue_5' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, K2Node_EnhancedInputActionEvent_ElapsedTime_5) == 0x000028, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::K2Node_EnhancedInputActionEvent_ElapsedTime_5' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, K2Node_EnhancedInputActionEvent_TriggeredTime_5) == 0x00002C, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::K2Node_EnhancedInputActionEvent_TriggeredTime_5' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, K2Node_EnhancedInputActionEvent_SourceAction_5) == 0x000030, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::K2Node_EnhancedInputActionEvent_SourceAction_5' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, K2Node_EnhancedInputActionEvent_ActionValue_4) == 0x000038, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::K2Node_EnhancedInputActionEvent_ActionValue_4' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, K2Node_EnhancedInputActionEvent_ElapsedTime_4) == 0x000058, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::K2Node_EnhancedInputActionEvent_ElapsedTime_4' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, K2Node_EnhancedInputActionEvent_TriggeredTime_4) == 0x00005C, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::K2Node_EnhancedInputActionEvent_TriggeredTime_4' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, K2Node_EnhancedInputActionEvent_SourceAction_4) == 0x000060, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::K2Node_EnhancedInputActionEvent_SourceAction_4' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, CallFunc_Conv_InputActionValueToBool_ReturnValue) == 0x000068, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::CallFunc_Conv_InputActionValueToBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, CallFunc_Conv_InputActionValueToBool_ReturnValue_1) == 0x000069, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::CallFunc_Conv_InputActionValueToBool_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, Temp_object_Variable) == 0x000070, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::Temp_object_Variable' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, Temp_real_Variable) == 0x000078, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::Temp_real_Variable' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, Temp_real_Variable_0) == 0x000080, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::Temp_real_Variable_0' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, Temp_real_Variable_1) == 0x000088, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::Temp_real_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, Temp_real_Variable_1) == 0x000090, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::Temp_real_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, Temp_bool_Variable) == 0x000098, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, Temp_real_Variable_1_0) == 0x0000A0, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::Temp_real_Variable_1_0' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, Temp_real_Variable_1_1) == 0x0000A8, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::Temp_real_Variable_1_1' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, K2Node_EnhancedInputActionEvent_ActionValue_3) == 0x0000B0, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::K2Node_EnhancedInputActionEvent_ActionValue_3' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, K2Node_EnhancedInputActionEvent_ElapsedTime_3) == 0x0000D0, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::K2Node_EnhancedInputActionEvent_ElapsedTime_3' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, K2Node_EnhancedInputActionEvent_TriggeredTime_3) == 0x0000D4, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::K2Node_EnhancedInputActionEvent_TriggeredTime_3' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, K2Node_EnhancedInputActionEvent_SourceAction_3) == 0x0000D8, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::K2Node_EnhancedInputActionEvent_SourceAction_3' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, K2Node_EnhancedInputActionEvent_ActionValue_2) == 0x0000E0, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::K2Node_EnhancedInputActionEvent_ActionValue_2' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, K2Node_EnhancedInputActionEvent_ElapsedTime_2) == 0x000100, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::K2Node_EnhancedInputActionEvent_ElapsedTime_2' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, K2Node_EnhancedInputActionEvent_TriggeredTime_2) == 0x000104, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::K2Node_EnhancedInputActionEvent_TriggeredTime_2' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, K2Node_EnhancedInputActionEvent_SourceAction_2) == 0x000108, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::K2Node_EnhancedInputActionEvent_SourceAction_2' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, CallFunc_Conv_InputActionValueToBool_ReturnValue_2) == 0x000110, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::CallFunc_Conv_InputActionValueToBool_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, CallFunc_Conv_InputActionValueToBool_ReturnValue_3) == 0x000111, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::CallFunc_Conv_InputActionValueToBool_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, K2Node_EnhancedInputActionEvent_ActionValue_1) == 0x000118, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::K2Node_EnhancedInputActionEvent_ActionValue_1' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, K2Node_EnhancedInputActionEvent_ElapsedTime_1) == 0x000138, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::K2Node_EnhancedInputActionEvent_ElapsedTime_1' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, K2Node_EnhancedInputActionEvent_TriggeredTime_1) == 0x00013C, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::K2Node_EnhancedInputActionEvent_TriggeredTime_1' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, K2Node_EnhancedInputActionEvent_SourceAction_1) == 0x000140, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::K2Node_EnhancedInputActionEvent_SourceAction_1' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, K2Node_EnhancedInputActionEvent_ActionValue) == 0x000148, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::K2Node_EnhancedInputActionEvent_ActionValue' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, K2Node_EnhancedInputActionEvent_ElapsedTime) == 0x000168, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::K2Node_EnhancedInputActionEvent_ElapsedTime' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, K2Node_EnhancedInputActionEvent_TriggeredTime) == 0x00016C, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::K2Node_EnhancedInputActionEvent_TriggeredTime' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, K2Node_EnhancedInputActionEvent_SourceAction) == 0x000170, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::K2Node_EnhancedInputActionEvent_SourceAction' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, CallFunc_Conv_InputActionValueToBool_ReturnValue_4) == 0x000178, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::CallFunc_Conv_InputActionValueToBool_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, CallFunc_Conv_InputActionValueToBool_ReturnValue_5) == 0x000179, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::CallFunc_Conv_InputActionValueToBool_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, Temp_object_Variable_1) == 0x000180, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::Temp_object_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, Temp_real_Variable_2) == 0x000188, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::Temp_real_Variable_2' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, Temp_real_Variable_2_0) == 0x000190, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::Temp_real_Variable_2_0' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, Temp_real_Variable_2_1) == 0x000198, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::Temp_real_Variable_2_1' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, Temp_real_Variable_2_2) == 0x0001A0, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::Temp_real_Variable_2_2' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, Temp_real_Variable_2_3) == 0x0001A8, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::Temp_real_Variable_2_3' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, Temp_real_Variable_3) == 0x0001B0, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::Temp_real_Variable_3' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, Temp_bool_Variable_1) == 0x0001B8, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::Temp_bool_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, Temp_real_Variable_3_0) == 0x0001C0, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::Temp_real_Variable_3_0' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, Temp_real_Variable_3_1) == 0x0001C8, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::Temp_real_Variable_3_1' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, Temp_real_Variable_3_2) == 0x0001D0, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::Temp_real_Variable_3_2' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, Temp_real_Variable_3_3) == 0x0001D8, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::Temp_real_Variable_3_3' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, CallFunc_GetGameInstanceSubsystem_ReturnValue) == 0x0001E0, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::CallFunc_GetGameInstanceSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, CallFunc_NavigateToWidget_Widget_CastInput) == 0x0001E8, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::CallFunc_NavigateToWidget_Widget_CastInput' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, K2Node_Event_IsDesignTime) == 0x0001F8, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::K2Node_Event_IsDesignTime' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, CallFunc_PlayAnimation_ReturnValue) == 0x000200, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::CallFunc_PlayAnimation_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, CallFunc_PlayAnimation_ReturnValue_1) == 0x000208, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::CallFunc_PlayAnimation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, K2Node_Event_forward) == 0x000210, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::K2Node_Event_forward' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, K2Node_ComponentBoundEvent_Button) == 0x000218, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::K2Node_ComponentBoundEvent_Button' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, CallFunc_IsValid_ReturnValue) == 0x000220, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, CallFunc_Skip_ReturnValue) == 0x000221, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::CallFunc_Skip_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, CallFunc_GetGameInstanceSubsystem_ReturnValue_1) == 0x000228, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::CallFunc_GetGameInstanceSubsystem_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, CallFunc_NavigateToWidget_Widget_CastInput_1) == 0x000230, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::CallFunc_NavigateToWidget_Widget_CastInput_1' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, CallFunc_GetIsFocussed_ReturnValue) == 0x000240, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::CallFunc_GetIsFocussed_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, CallFunc_GetIsFocussed_ReturnValue_1) == 0x000241, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::CallFunc_GetIsFocussed_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, CallFunc_GetIsFocussed_ReturnValue_2) == 0x000242, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::CallFunc_GetIsFocussed_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, CallFunc_GetIsFocussed_ReturnValue_3) == 0x000243, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::CallFunc_GetIsFocussed_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, CallFunc_GetIsFocussed_ReturnValue_4) == 0x000244, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::CallFunc_GetIsFocussed_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, CallFunc_GetIsFocussed_ReturnValue_5) == 0x000245, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::CallFunc_GetIsFocussed_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, CallFunc_GetIsFocussed_ReturnValue_6) == 0x000246, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::CallFunc_GetIsFocussed_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, CallFunc_GetIsFocussed_ReturnValue_7) == 0x000247, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::CallFunc_GetIsFocussed_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, K2Node_EnhancedInputActionEvent_ActionValue_6) == 0x000248, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::K2Node_EnhancedInputActionEvent_ActionValue_6' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, K2Node_EnhancedInputActionEvent_ElapsedTime_6) == 0x000268, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::K2Node_EnhancedInputActionEvent_ElapsedTime_6' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, K2Node_EnhancedInputActionEvent_TriggeredTime_6) == 0x00026C, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::K2Node_EnhancedInputActionEvent_TriggeredTime_6' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, K2Node_EnhancedInputActionEvent_SourceAction_6) == 0x000270, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::K2Node_EnhancedInputActionEvent_SourceAction_6' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, CallFunc_GetIsEnabled_ReturnValue) == 0x000278, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::CallFunc_GetIsEnabled_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, Temp_real_Variable_2) == 0x000280, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::Temp_real_Variable_2' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, Temp_real_Variable_1_2) == 0x000288, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::Temp_real_Variable_1_2' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, CallFunc_Conv_InputActionValueToBool_ReturnValue_6) == 0x000290, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::CallFunc_Conv_InputActionValueToBool_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, K2Node_EnhancedInputActionEvent_ActionValue_7) == 0x000298, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::K2Node_EnhancedInputActionEvent_ActionValue_7' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, K2Node_EnhancedInputActionEvent_ElapsedTime_7) == 0x0002B8, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::K2Node_EnhancedInputActionEvent_ElapsedTime_7' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, K2Node_EnhancedInputActionEvent_TriggeredTime_7) == 0x0002BC, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::K2Node_EnhancedInputActionEvent_TriggeredTime_7' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, K2Node_EnhancedInputActionEvent_SourceAction_7) == 0x0002C0, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::K2Node_EnhancedInputActionEvent_SourceAction_7' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, Temp_real_Variable_3) == 0x0002C8, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::Temp_real_Variable_3' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, Temp_real_Variable_1_3) == 0x0002D0, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::Temp_real_Variable_1_3' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen, CallFunc_Conv_InputActionValueToBool_ReturnValue_7) == 0x0002D8, "Member 'WBP_Modern_Onboarding_HDRScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_HDRScreen::CallFunc_Conv_InputActionValueToBool_ReturnValue_7' has a wrong offset!");

// Function WBP_Modern_Onboarding_HDRScreen.WBP_Modern_Onboarding_HDRScreen_C.Get Brighness Row
// 0x0EA0 (0x0EA0 - 0x0000)
struct WBP_Modern_Onboarding_HDRScreen_C_Get_Brighness_Row final
{
public:
	struct FModernSettingTableRow                 Row;                                               // 0x0000(0x0138)(Parm, OutParm)
	struct FModernSettingTableRow                 K2Node_MakeStruct_ModernSettingTableRow;           // 0x0138(0x0138)()
	struct FModernSettingTableRow                 K2Node_MakeStruct_ModernSettingTableRow_1;         // 0x0270(0x0138)()
	class UAltarGameUserSetting*                  CallFunc_GetInstance_ReturnValue;                  // 0x03A8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FModernSettingTableRow                 K2Node_MakeStruct_ModernSettingTableRow_2;         // 0x03B0(0x0138)()
	class UVModernSettingPageTable*               CallFunc_GetSettingPageTable_ReturnValue;          // 0x04E8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FModernSettingPageTableRow             CallFunc_GetDataTableRowFromName_OutRow;           // 0x04F0(0x0830)()
	bool                                          CallFunc_GetDataTableRowFromName_ReturnValue;      // 0x0D20(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_469F[0x7];                                     // 0x0D21(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FModernSettingCategoryTableRow         CallFunc_GetDataTableRowFromName_OutRow_1;         // 0x0D28(0x0028)()
	bool                                          CallFunc_GetDataTableRowFromName_ReturnValue_1;    // 0x0D50(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_46A0[0x7];                                     // 0x0D51(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FModernSettingTableRow                 CallFunc_GetDataTableRowFromName_OutRow_2;         // 0x0D58(0x0138)()
	bool                                          CallFunc_GetDataTableRowFromName_ReturnValue_2;    // 0x0E90(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Modern_Onboarding_HDRScreen_C_Get_Brighness_Row) == 0x000010, "Wrong alignment on WBP_Modern_Onboarding_HDRScreen_C_Get_Brighness_Row");
static_assert(sizeof(WBP_Modern_Onboarding_HDRScreen_C_Get_Brighness_Row) == 0x000EA0, "Wrong size on WBP_Modern_Onboarding_HDRScreen_C_Get_Brighness_Row");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_Get_Brighness_Row, Row) == 0x000000, "Member 'WBP_Modern_Onboarding_HDRScreen_C_Get_Brighness_Row::Row' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_Get_Brighness_Row, K2Node_MakeStruct_ModernSettingTableRow) == 0x000138, "Member 'WBP_Modern_Onboarding_HDRScreen_C_Get_Brighness_Row::K2Node_MakeStruct_ModernSettingTableRow' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_Get_Brighness_Row, K2Node_MakeStruct_ModernSettingTableRow_1) == 0x000270, "Member 'WBP_Modern_Onboarding_HDRScreen_C_Get_Brighness_Row::K2Node_MakeStruct_ModernSettingTableRow_1' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_Get_Brighness_Row, CallFunc_GetInstance_ReturnValue) == 0x0003A8, "Member 'WBP_Modern_Onboarding_HDRScreen_C_Get_Brighness_Row::CallFunc_GetInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_Get_Brighness_Row, K2Node_MakeStruct_ModernSettingTableRow_2) == 0x0003B0, "Member 'WBP_Modern_Onboarding_HDRScreen_C_Get_Brighness_Row::K2Node_MakeStruct_ModernSettingTableRow_2' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_Get_Brighness_Row, CallFunc_GetSettingPageTable_ReturnValue) == 0x0004E8, "Member 'WBP_Modern_Onboarding_HDRScreen_C_Get_Brighness_Row::CallFunc_GetSettingPageTable_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_Get_Brighness_Row, CallFunc_GetDataTableRowFromName_OutRow) == 0x0004F0, "Member 'WBP_Modern_Onboarding_HDRScreen_C_Get_Brighness_Row::CallFunc_GetDataTableRowFromName_OutRow' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_Get_Brighness_Row, CallFunc_GetDataTableRowFromName_ReturnValue) == 0x000D20, "Member 'WBP_Modern_Onboarding_HDRScreen_C_Get_Brighness_Row::CallFunc_GetDataTableRowFromName_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_Get_Brighness_Row, CallFunc_GetDataTableRowFromName_OutRow_1) == 0x000D28, "Member 'WBP_Modern_Onboarding_HDRScreen_C_Get_Brighness_Row::CallFunc_GetDataTableRowFromName_OutRow_1' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_Get_Brighness_Row, CallFunc_GetDataTableRowFromName_ReturnValue_1) == 0x000D50, "Member 'WBP_Modern_Onboarding_HDRScreen_C_Get_Brighness_Row::CallFunc_GetDataTableRowFromName_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_Get_Brighness_Row, CallFunc_GetDataTableRowFromName_OutRow_2) == 0x000D58, "Member 'WBP_Modern_Onboarding_HDRScreen_C_Get_Brighness_Row::CallFunc_GetDataTableRowFromName_OutRow_2' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_Get_Brighness_Row, CallFunc_GetDataTableRowFromName_ReturnValue_2) == 0x000E90, "Member 'WBP_Modern_Onboarding_HDRScreen_C_Get_Brighness_Row::CallFunc_GetDataTableRowFromName_ReturnValue_2' has a wrong offset!");

// Function WBP_Modern_Onboarding_HDRScreen.WBP_Modern_Onboarding_HDRScreen_C.GetMissingStep
// 0x02B0 (0x02B0 - 0x0000)
struct WBP_Modern_Onboarding_HDRScreen_C_GetMissingStep final
{
public:
	class FText                                   MissingText;                                       // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
	struct FModernSettingTableRow                 ModernSettingTableRow;                             // 0x0018(0x0138)(Parm, OutParm)
	TArray<struct FModernSettingSingleCommand>    K2Node_MakeArray_Array;                            // 0x0150(0x0010)(ReferenceParm)
	struct FModernSettingStepProperties           K2Node_MakeStruct_ModernSettingStepProperties;     // 0x0160(0x0018)()
	struct FModernSettingTableRow                 K2Node_MakeStruct_ModernSettingTableRow;           // 0x0178(0x0138)()
};
static_assert(alignof(WBP_Modern_Onboarding_HDRScreen_C_GetMissingStep) == 0x000008, "Wrong alignment on WBP_Modern_Onboarding_HDRScreen_C_GetMissingStep");
static_assert(sizeof(WBP_Modern_Onboarding_HDRScreen_C_GetMissingStep) == 0x0002B0, "Wrong size on WBP_Modern_Onboarding_HDRScreen_C_GetMissingStep");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_GetMissingStep, MissingText) == 0x000000, "Member 'WBP_Modern_Onboarding_HDRScreen_C_GetMissingStep::MissingText' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_GetMissingStep, ModernSettingTableRow) == 0x000018, "Member 'WBP_Modern_Onboarding_HDRScreen_C_GetMissingStep::ModernSettingTableRow' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_GetMissingStep, K2Node_MakeArray_Array) == 0x000150, "Member 'WBP_Modern_Onboarding_HDRScreen_C_GetMissingStep::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_GetMissingStep, K2Node_MakeStruct_ModernSettingStepProperties) == 0x000160, "Member 'WBP_Modern_Onboarding_HDRScreen_C_GetMissingStep::K2Node_MakeStruct_ModernSettingStepProperties' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_GetMissingStep, K2Node_MakeStruct_ModernSettingTableRow) == 0x000178, "Member 'WBP_Modern_Onboarding_HDRScreen_C_GetMissingStep::K2Node_MakeStruct_ModernSettingTableRow' has a wrong offset!");

// Function WBP_Modern_Onboarding_HDRScreen.WBP_Modern_Onboarding_HDRScreen_C.InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_0
// 0x0030 (0x0030 - 0x0000)
struct WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_0 final
{
public:
	struct FInputActionValue                      ActionValue;                                       // 0x0000(0x0020)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
	float                                         ElapsedTime;                                       // 0x0020(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         TriggeredTime;                                     // 0x0024(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	const class UInputAction*                     SourceAction;                                      // 0x0028(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_0) == 0x000008, "Wrong alignment on WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_0");
static_assert(sizeof(WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_0) == 0x000030, "Wrong size on WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_0");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_0, ActionValue) == 0x000000, "Member 'WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_0::ActionValue' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_0, ElapsedTime) == 0x000020, "Member 'WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_0::ElapsedTime' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_0, TriggeredTime) == 0x000024, "Member 'WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_0::TriggeredTime' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_0, SourceAction) == 0x000028, "Member 'WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_0::SourceAction' has a wrong offset!");

// Function WBP_Modern_Onboarding_HDRScreen.WBP_Modern_Onboarding_HDRScreen_C.InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_1
// 0x0030 (0x0030 - 0x0000)
struct WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_1 final
{
public:
	struct FInputActionValue                      ActionValue;                                       // 0x0000(0x0020)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
	float                                         ElapsedTime;                                       // 0x0020(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         TriggeredTime;                                     // 0x0024(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	const class UInputAction*                     SourceAction;                                      // 0x0028(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_1) == 0x000008, "Wrong alignment on WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_1");
static_assert(sizeof(WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_1) == 0x000030, "Wrong size on WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_1");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_1, ActionValue) == 0x000000, "Member 'WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_1::ActionValue' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_1, ElapsedTime) == 0x000020, "Member 'WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_1::ElapsedTime' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_1, TriggeredTime) == 0x000024, "Member 'WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_1::TriggeredTime' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_1, SourceAction) == 0x000028, "Member 'WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_1::SourceAction' has a wrong offset!");

// Function WBP_Modern_Onboarding_HDRScreen.WBP_Modern_Onboarding_HDRScreen_C.InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_2
// 0x0030 (0x0030 - 0x0000)
struct WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_2 final
{
public:
	struct FInputActionValue                      ActionValue;                                       // 0x0000(0x0020)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
	float                                         ElapsedTime;                                       // 0x0020(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         TriggeredTime;                                     // 0x0024(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	const class UInputAction*                     SourceAction;                                      // 0x0028(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_2) == 0x000008, "Wrong alignment on WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_2");
static_assert(sizeof(WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_2) == 0x000030, "Wrong size on WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_2");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_2, ActionValue) == 0x000000, "Member 'WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_2::ActionValue' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_2, ElapsedTime) == 0x000020, "Member 'WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_2::ElapsedTime' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_2, TriggeredTime) == 0x000024, "Member 'WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_2::TriggeredTime' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_2, SourceAction) == 0x000028, "Member 'WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_2::SourceAction' has a wrong offset!");

// Function WBP_Modern_Onboarding_HDRScreen.WBP_Modern_Onboarding_HDRScreen_C.InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_3
// 0x0030 (0x0030 - 0x0000)
struct WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_3 final
{
public:
	struct FInputActionValue                      ActionValue;                                       // 0x0000(0x0020)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
	float                                         ElapsedTime;                                       // 0x0020(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         TriggeredTime;                                     // 0x0024(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	const class UInputAction*                     SourceAction;                                      // 0x0028(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_3) == 0x000008, "Wrong alignment on WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_3");
static_assert(sizeof(WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_3) == 0x000030, "Wrong size on WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_3");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_3, ActionValue) == 0x000000, "Member 'WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_3::ActionValue' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_3, ElapsedTime) == 0x000020, "Member 'WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_3::ElapsedTime' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_3, TriggeredTime) == 0x000024, "Member 'WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_3::TriggeredTime' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_3, SourceAction) == 0x000028, "Member 'WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_3::SourceAction' has a wrong offset!");

// Function WBP_Modern_Onboarding_HDRScreen.WBP_Modern_Onboarding_HDRScreen_C.InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_4
// 0x0030 (0x0030 - 0x0000)
struct WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_4 final
{
public:
	struct FInputActionValue                      ActionValue;                                       // 0x0000(0x0020)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
	float                                         ElapsedTime;                                       // 0x0020(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         TriggeredTime;                                     // 0x0024(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	const class UInputAction*                     SourceAction;                                      // 0x0028(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_4) == 0x000008, "Wrong alignment on WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_4");
static_assert(sizeof(WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_4) == 0x000030, "Wrong size on WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_4");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_4, ActionValue) == 0x000000, "Member 'WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_4::ActionValue' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_4, ElapsedTime) == 0x000020, "Member 'WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_4::ElapsedTime' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_4, TriggeredTime) == 0x000024, "Member 'WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_4::TriggeredTime' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_4, SourceAction) == 0x000028, "Member 'WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_4::SourceAction' has a wrong offset!");

// Function WBP_Modern_Onboarding_HDRScreen.WBP_Modern_Onboarding_HDRScreen_C.InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_5
// 0x0030 (0x0030 - 0x0000)
struct WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_5 final
{
public:
	struct FInputActionValue                      ActionValue;                                       // 0x0000(0x0020)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
	float                                         ElapsedTime;                                       // 0x0020(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         TriggeredTime;                                     // 0x0024(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	const class UInputAction*                     SourceAction;                                      // 0x0028(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_5) == 0x000008, "Wrong alignment on WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_5");
static_assert(sizeof(WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_5) == 0x000030, "Wrong size on WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_5");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_5, ActionValue) == 0x000000, "Member 'WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_5::ActionValue' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_5, ElapsedTime) == 0x000020, "Member 'WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_5::ElapsedTime' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_5, TriggeredTime) == 0x000024, "Member 'WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_5::TriggeredTime' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_5, SourceAction) == 0x000028, "Member 'WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_5::SourceAction' has a wrong offset!");

// Function WBP_Modern_Onboarding_HDRScreen.WBP_Modern_Onboarding_HDRScreen_C.InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_6
// 0x0030 (0x0030 - 0x0000)
struct WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_6 final
{
public:
	struct FInputActionValue                      ActionValue;                                       // 0x0000(0x0020)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
	float                                         ElapsedTime;                                       // 0x0020(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         TriggeredTime;                                     // 0x0024(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	const class UInputAction*                     SourceAction;                                      // 0x0028(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_6) == 0x000008, "Wrong alignment on WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_6");
static_assert(sizeof(WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_6) == 0x000030, "Wrong size on WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_6");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_6, ActionValue) == 0x000000, "Member 'WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_6::ActionValue' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_6, ElapsedTime) == 0x000020, "Member 'WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_6::ElapsedTime' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_6, TriggeredTime) == 0x000024, "Member 'WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_6::TriggeredTime' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_6, SourceAction) == 0x000028, "Member 'WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_6::SourceAction' has a wrong offset!");

// Function WBP_Modern_Onboarding_HDRScreen.WBP_Modern_Onboarding_HDRScreen_C.InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_7
// 0x0030 (0x0030 - 0x0000)
struct WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_7 final
{
public:
	struct FInputActionValue                      ActionValue;                                       // 0x0000(0x0020)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
	float                                         ElapsedTime;                                       // 0x0020(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         TriggeredTime;                                     // 0x0024(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	const class UInputAction*                     SourceAction;                                      // 0x0028(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_7) == 0x000008, "Wrong alignment on WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_7");
static_assert(sizeof(WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_7) == 0x000030, "Wrong size on WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_7");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_7, ActionValue) == 0x000000, "Member 'WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_7::ActionValue' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_7, ElapsedTime) == 0x000020, "Member 'WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_7::ElapsedTime' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_7, TriggeredTime) == 0x000024, "Member 'WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_7::TriggeredTime' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_7, SourceAction) == 0x000028, "Member 'WBP_Modern_Onboarding_HDRScreen_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_7::SourceAction' has a wrong offset!");

// Function WBP_Modern_Onboarding_HDRScreen.WBP_Modern_Onboarding_HDRScreen_C.OnExit
// 0x0001 (0x0001 - 0x0000)
struct WBP_Modern_Onboarding_HDRScreen_C_OnExit final
{
public:
	bool                                          Forward;                                           // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Modern_Onboarding_HDRScreen_C_OnExit) == 0x000001, "Wrong alignment on WBP_Modern_Onboarding_HDRScreen_C_OnExit");
static_assert(sizeof(WBP_Modern_Onboarding_HDRScreen_C_OnExit) == 0x000001, "Wrong size on WBP_Modern_Onboarding_HDRScreen_C_OnExit");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_OnExit, Forward) == 0x000000, "Member 'WBP_Modern_Onboarding_HDRScreen_C_OnExit::Forward' has a wrong offset!");

// Function WBP_Modern_Onboarding_HDRScreen.WBP_Modern_Onboarding_HDRScreen_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WBP_Modern_Onboarding_HDRScreen_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Modern_Onboarding_HDRScreen_C_PreConstruct) == 0x000001, "Wrong alignment on WBP_Modern_Onboarding_HDRScreen_C_PreConstruct");
static_assert(sizeof(WBP_Modern_Onboarding_HDRScreen_C_PreConstruct) == 0x000001, "Wrong size on WBP_Modern_Onboarding_HDRScreen_C_PreConstruct");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'WBP_Modern_Onboarding_HDRScreen_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function WBP_Modern_Onboarding_HDRScreen.WBP_Modern_Onboarding_HDRScreen_C.SetupBrightnessSlider
// 0x0138 (0x0138 - 0x0000)
struct WBP_Modern_Onboarding_HDRScreen_C_SetupBrightnessSlider final
{
public:
	struct FModernSettingTableRow                 CallFunc_Get_Brighness_Row_Row;                    // 0x0000(0x0138)()
};
static_assert(alignof(WBP_Modern_Onboarding_HDRScreen_C_SetupBrightnessSlider) == 0x000008, "Wrong alignment on WBP_Modern_Onboarding_HDRScreen_C_SetupBrightnessSlider");
static_assert(sizeof(WBP_Modern_Onboarding_HDRScreen_C_SetupBrightnessSlider) == 0x000138, "Wrong size on WBP_Modern_Onboarding_HDRScreen_C_SetupBrightnessSlider");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_SetupBrightnessSlider, CallFunc_Get_Brighness_Row_Row) == 0x000000, "Member 'WBP_Modern_Onboarding_HDRScreen_C_SetupBrightnessSlider::CallFunc_Get_Brighness_Row_Row' has a wrong offset!");

// Function WBP_Modern_Onboarding_HDRScreen.WBP_Modern_Onboarding_HDRScreen_C.This Is For Plugin Compliance
// 0x0001 (0x0001 - 0x0000)
struct WBP_Modern_Onboarding_HDRScreen_C_This_Is_For_Plugin_Compliance final
{
public:
	bool                                          NewParam;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Modern_Onboarding_HDRScreen_C_This_Is_For_Plugin_Compliance) == 0x000001, "Wrong alignment on WBP_Modern_Onboarding_HDRScreen_C_This_Is_For_Plugin_Compliance");
static_assert(sizeof(WBP_Modern_Onboarding_HDRScreen_C_This_Is_For_Plugin_Compliance) == 0x000001, "Wrong size on WBP_Modern_Onboarding_HDRScreen_C_This_Is_For_Plugin_Compliance");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_This_Is_For_Plugin_Compliance, NewParam) == 0x000000, "Member 'WBP_Modern_Onboarding_HDRScreen_C_This_Is_For_Plugin_Compliance::NewParam' has a wrong offset!");

// Function WBP_Modern_Onboarding_HDRScreen.WBP_Modern_Onboarding_HDRScreen_C.BP_GetDesiredFocusTarget
// 0x0010 (0x0010 - 0x0000)
struct WBP_Modern_Onboarding_HDRScreen_C_BP_GetDesiredFocusTarget final
{
public:
	class UWidget*                                ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetIsEnabled_ReturnValue;                 // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Modern_Onboarding_HDRScreen_C_BP_GetDesiredFocusTarget) == 0x000008, "Wrong alignment on WBP_Modern_Onboarding_HDRScreen_C_BP_GetDesiredFocusTarget");
static_assert(sizeof(WBP_Modern_Onboarding_HDRScreen_C_BP_GetDesiredFocusTarget) == 0x000010, "Wrong size on WBP_Modern_Onboarding_HDRScreen_C_BP_GetDesiredFocusTarget");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_BP_GetDesiredFocusTarget, ReturnValue) == 0x000000, "Member 'WBP_Modern_Onboarding_HDRScreen_C_BP_GetDesiredFocusTarget::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_BP_GetDesiredFocusTarget, CallFunc_GetIsEnabled_ReturnValue) == 0x000008, "Member 'WBP_Modern_Onboarding_HDRScreen_C_BP_GetDesiredFocusTarget::CallFunc_GetIsEnabled_ReturnValue' has a wrong offset!");

// Function WBP_Modern_Onboarding_HDRScreen.WBP_Modern_Onboarding_HDRScreen_C.CanBeSkiped
// 0x0001 (0x0001 - 0x0000)
struct WBP_Modern_Onboarding_HDRScreen_C_CanBeSkiped final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Modern_Onboarding_HDRScreen_C_CanBeSkiped) == 0x000001, "Wrong alignment on WBP_Modern_Onboarding_HDRScreen_C_CanBeSkiped");
static_assert(sizeof(WBP_Modern_Onboarding_HDRScreen_C_CanBeSkiped) == 0x000001, "Wrong size on WBP_Modern_Onboarding_HDRScreen_C_CanBeSkiped");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_CanBeSkiped, ReturnValue) == 0x000000, "Member 'WBP_Modern_Onboarding_HDRScreen_C_CanBeSkiped::ReturnValue' has a wrong offset!");

// Function WBP_Modern_Onboarding_HDRScreen.WBP_Modern_Onboarding_HDRScreen_C.CanEnter
// 0x0003 (0x0003 - 0x0000)
struct WBP_Modern_Onboarding_HDRScreen_C_CanEnter final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsOnboardingSettingsDone_ReturnValue;     // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Modern_Onboarding_HDRScreen_C_CanEnter) == 0x000001, "Wrong alignment on WBP_Modern_Onboarding_HDRScreen_C_CanEnter");
static_assert(sizeof(WBP_Modern_Onboarding_HDRScreen_C_CanEnter) == 0x000003, "Wrong size on WBP_Modern_Onboarding_HDRScreen_C_CanEnter");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_CanEnter, ReturnValue) == 0x000000, "Member 'WBP_Modern_Onboarding_HDRScreen_C_CanEnter::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_CanEnter, CallFunc_IsOnboardingSettingsDone_ReturnValue) == 0x000001, "Member 'WBP_Modern_Onboarding_HDRScreen_C_CanEnter::CallFunc_IsOnboardingSettingsDone_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_CanEnter, CallFunc_Not_PreBool_ReturnValue) == 0x000002, "Member 'WBP_Modern_Onboarding_HDRScreen_C_CanEnter::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");

// Function WBP_Modern_Onboarding_HDRScreen.WBP_Modern_Onboarding_HDRScreen_C.CanExit
// 0x0001 (0x0001 - 0x0000)
struct WBP_Modern_Onboarding_HDRScreen_C_CanExit final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Modern_Onboarding_HDRScreen_C_CanExit) == 0x000001, "Wrong alignment on WBP_Modern_Onboarding_HDRScreen_C_CanExit");
static_assert(sizeof(WBP_Modern_Onboarding_HDRScreen_C_CanExit) == 0x000001, "Wrong size on WBP_Modern_Onboarding_HDRScreen_C_CanExit");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_CanExit, ReturnValue) == 0x000000, "Member 'WBP_Modern_Onboarding_HDRScreen_C_CanExit::ReturnValue' has a wrong offset!");

// Function WBP_Modern_Onboarding_HDRScreen.WBP_Modern_Onboarding_HDRScreen_C.DoesNeedEnterAnimation
// 0x0002 (0x0002 - 0x0000)
struct WBP_Modern_Onboarding_HDRScreen_C_DoesNeedEnterAnimation final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Modern_Onboarding_HDRScreen_C_DoesNeedEnterAnimation) == 0x000001, "Wrong alignment on WBP_Modern_Onboarding_HDRScreen_C_DoesNeedEnterAnimation");
static_assert(sizeof(WBP_Modern_Onboarding_HDRScreen_C_DoesNeedEnterAnimation) == 0x000002, "Wrong size on WBP_Modern_Onboarding_HDRScreen_C_DoesNeedEnterAnimation");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_DoesNeedEnterAnimation, ReturnValue) == 0x000000, "Member 'WBP_Modern_Onboarding_HDRScreen_C_DoesNeedEnterAnimation::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_DoesNeedEnterAnimation, CallFunc_Not_PreBool_ReturnValue) == 0x000001, "Member 'WBP_Modern_Onboarding_HDRScreen_C_DoesNeedEnterAnimation::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");

// Function WBP_Modern_Onboarding_HDRScreen.WBP_Modern_Onboarding_HDRScreen_C.DoesNeedExitAnimation
// 0x0002 (0x0002 - 0x0000)
struct WBP_Modern_Onboarding_HDRScreen_C_DoesNeedExitAnimation final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Modern_Onboarding_HDRScreen_C_DoesNeedExitAnimation) == 0x000001, "Wrong alignment on WBP_Modern_Onboarding_HDRScreen_C_DoesNeedExitAnimation");
static_assert(sizeof(WBP_Modern_Onboarding_HDRScreen_C_DoesNeedExitAnimation) == 0x000002, "Wrong size on WBP_Modern_Onboarding_HDRScreen_C_DoesNeedExitAnimation");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_DoesNeedExitAnimation, ReturnValue) == 0x000000, "Member 'WBP_Modern_Onboarding_HDRScreen_C_DoesNeedExitAnimation::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_HDRScreen_C_DoesNeedExitAnimation, CallFunc_Not_PreBool_ReturnValue) == 0x000001, "Member 'WBP_Modern_Onboarding_HDRScreen_C_DoesNeedExitAnimation::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");

}

