#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Modern_Onboarding_VirtuosVideoScreen

#include "Basic.hpp"

#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function WBP_Modern_Onboarding_VirtuosVideoScreen.WBP_Modern_Onboarding_VirtuosVideoScreen_C.BndEvt__WBP_Modern_Onboarding_VirtuosVideoScreen_BinkVirtuosVideo_K2Node_ComponentBoundEvent_3_AltarBinkMediaPlayerOnVideoOpenned__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct WBP_Modern_Onboarding_VirtuosVideoScreen_C_BndEvt__WBP_Modern_Onboarding_VirtuosVideoScreen_BinkVirtuosVideo_K2Node_ComponentBoundEvent_3_AltarBinkMediaPlayerOnVideoOpenned__DelegateSignature final
{
public:
	class FString                                 OpenedUrl;                                         // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Modern_Onboarding_VirtuosVideoScreen_C_BndEvt__WBP_Modern_Onboarding_VirtuosVideoScreen_BinkVirtuosVideo_K2Node_ComponentBoundEvent_3_AltarBinkMediaPlayerOnVideoOpenned__DelegateSignature) == 0x000008, "Wrong alignment on WBP_Modern_Onboarding_VirtuosVideoScreen_C_BndEvt__WBP_Modern_Onboarding_VirtuosVideoScreen_BinkVirtuosVideo_K2Node_ComponentBoundEvent_3_AltarBinkMediaPlayerOnVideoOpenned__DelegateSignature");
static_assert(sizeof(WBP_Modern_Onboarding_VirtuosVideoScreen_C_BndEvt__WBP_Modern_Onboarding_VirtuosVideoScreen_BinkVirtuosVideo_K2Node_ComponentBoundEvent_3_AltarBinkMediaPlayerOnVideoOpenned__DelegateSignature) == 0x000010, "Wrong size on WBP_Modern_Onboarding_VirtuosVideoScreen_C_BndEvt__WBP_Modern_Onboarding_VirtuosVideoScreen_BinkVirtuosVideo_K2Node_ComponentBoundEvent_3_AltarBinkMediaPlayerOnVideoOpenned__DelegateSignature");
static_assert(offsetof(WBP_Modern_Onboarding_VirtuosVideoScreen_C_BndEvt__WBP_Modern_Onboarding_VirtuosVideoScreen_BinkVirtuosVideo_K2Node_ComponentBoundEvent_3_AltarBinkMediaPlayerOnVideoOpenned__DelegateSignature, OpenedUrl) == 0x000000, "Member 'WBP_Modern_Onboarding_VirtuosVideoScreen_C_BndEvt__WBP_Modern_Onboarding_VirtuosVideoScreen_BinkVirtuosVideo_K2Node_ComponentBoundEvent_3_AltarBinkMediaPlayerOnVideoOpenned__DelegateSignature::OpenedUrl' has a wrong offset!");

// Function WBP_Modern_Onboarding_VirtuosVideoScreen.WBP_Modern_Onboarding_VirtuosVideoScreen_C.ExecuteUbergraph_WBP_Modern_Onboarding_VirtuosVideoScreen
// 0x0068 (0x0068 - 0x0000)
struct WBP_Modern_Onboarding_VirtuosVideoScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_VirtuosVideoScreen final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetIsFocussed_ReturnValue;                // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_forward;                              // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_46A5[0x2];                                     // 0x0006(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGeometry                              K2Node_Event_MyGeometry;                           // 0x0008(0x0038)(IsPlainOldData, NoDestructor)
	float                                         K2Node_Event_InDeltaTime;                          // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0044(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue_1;                 // 0x0045(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Prepare_ReturnValue;                      // 0x0046(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Open_ReturnValue;                         // 0x0047(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Play_ReturnValue;                         // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_46A6[0x7];                                     // 0x0049(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 K2Node_ComponentBoundEvent_OpenedUrl;              // 0x0050(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_Play_ReturnValue_1;                       // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Modern_Onboarding_VirtuosVideoScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_VirtuosVideoScreen) == 0x000008, "Wrong alignment on WBP_Modern_Onboarding_VirtuosVideoScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_VirtuosVideoScreen");
static_assert(sizeof(WBP_Modern_Onboarding_VirtuosVideoScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_VirtuosVideoScreen) == 0x000068, "Wrong size on WBP_Modern_Onboarding_VirtuosVideoScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_VirtuosVideoScreen");
static_assert(offsetof(WBP_Modern_Onboarding_VirtuosVideoScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_VirtuosVideoScreen, EntryPoint) == 0x000000, "Member 'WBP_Modern_Onboarding_VirtuosVideoScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_VirtuosVideoScreen::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_VirtuosVideoScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_VirtuosVideoScreen, CallFunc_GetIsFocussed_ReturnValue) == 0x000004, "Member 'WBP_Modern_Onboarding_VirtuosVideoScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_VirtuosVideoScreen::CallFunc_GetIsFocussed_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_VirtuosVideoScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_VirtuosVideoScreen, K2Node_Event_forward) == 0x000005, "Member 'WBP_Modern_Onboarding_VirtuosVideoScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_VirtuosVideoScreen::K2Node_Event_forward' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_VirtuosVideoScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_VirtuosVideoScreen, K2Node_Event_MyGeometry) == 0x000008, "Member 'WBP_Modern_Onboarding_VirtuosVideoScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_VirtuosVideoScreen::K2Node_Event_MyGeometry' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_VirtuosVideoScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_VirtuosVideoScreen, K2Node_Event_InDeltaTime) == 0x000040, "Member 'WBP_Modern_Onboarding_VirtuosVideoScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_VirtuosVideoScreen::K2Node_Event_InDeltaTime' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_VirtuosVideoScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_VirtuosVideoScreen, CallFunc_BooleanAND_ReturnValue) == 0x000044, "Member 'WBP_Modern_Onboarding_VirtuosVideoScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_VirtuosVideoScreen::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_VirtuosVideoScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_VirtuosVideoScreen, CallFunc_BooleanAND_ReturnValue_1) == 0x000045, "Member 'WBP_Modern_Onboarding_VirtuosVideoScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_VirtuosVideoScreen::CallFunc_BooleanAND_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_VirtuosVideoScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_VirtuosVideoScreen, CallFunc_Prepare_ReturnValue) == 0x000046, "Member 'WBP_Modern_Onboarding_VirtuosVideoScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_VirtuosVideoScreen::CallFunc_Prepare_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_VirtuosVideoScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_VirtuosVideoScreen, CallFunc_Open_ReturnValue) == 0x000047, "Member 'WBP_Modern_Onboarding_VirtuosVideoScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_VirtuosVideoScreen::CallFunc_Open_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_VirtuosVideoScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_VirtuosVideoScreen, CallFunc_Play_ReturnValue) == 0x000048, "Member 'WBP_Modern_Onboarding_VirtuosVideoScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_VirtuosVideoScreen::CallFunc_Play_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_VirtuosVideoScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_VirtuosVideoScreen, K2Node_ComponentBoundEvent_OpenedUrl) == 0x000050, "Member 'WBP_Modern_Onboarding_VirtuosVideoScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_VirtuosVideoScreen::K2Node_ComponentBoundEvent_OpenedUrl' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_VirtuosVideoScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_VirtuosVideoScreen, CallFunc_Play_ReturnValue_1) == 0x000060, "Member 'WBP_Modern_Onboarding_VirtuosVideoScreen_C_ExecuteUbergraph_WBP_Modern_Onboarding_VirtuosVideoScreen::CallFunc_Play_ReturnValue_1' has a wrong offset!");

// Function WBP_Modern_Onboarding_VirtuosVideoScreen.WBP_Modern_Onboarding_VirtuosVideoScreen_C.OnExit
// 0x0001 (0x0001 - 0x0000)
struct WBP_Modern_Onboarding_VirtuosVideoScreen_C_OnExit final
{
public:
	bool                                          Forward;                                           // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Modern_Onboarding_VirtuosVideoScreen_C_OnExit) == 0x000001, "Wrong alignment on WBP_Modern_Onboarding_VirtuosVideoScreen_C_OnExit");
static_assert(sizeof(WBP_Modern_Onboarding_VirtuosVideoScreen_C_OnExit) == 0x000001, "Wrong size on WBP_Modern_Onboarding_VirtuosVideoScreen_C_OnExit");
static_assert(offsetof(WBP_Modern_Onboarding_VirtuosVideoScreen_C_OnExit, Forward) == 0x000000, "Member 'WBP_Modern_Onboarding_VirtuosVideoScreen_C_OnExit::Forward' has a wrong offset!");

// Function WBP_Modern_Onboarding_VirtuosVideoScreen.WBP_Modern_Onboarding_VirtuosVideoScreen_C.Tick
// 0x003C (0x003C - 0x0000)
struct WBP_Modern_Onboarding_VirtuosVideoScreen_C_Tick final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	float                                         InDeltaTime;                                       // 0x0038(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Modern_Onboarding_VirtuosVideoScreen_C_Tick) == 0x000004, "Wrong alignment on WBP_Modern_Onboarding_VirtuosVideoScreen_C_Tick");
static_assert(sizeof(WBP_Modern_Onboarding_VirtuosVideoScreen_C_Tick) == 0x00003C, "Wrong size on WBP_Modern_Onboarding_VirtuosVideoScreen_C_Tick");
static_assert(offsetof(WBP_Modern_Onboarding_VirtuosVideoScreen_C_Tick, MyGeometry) == 0x000000, "Member 'WBP_Modern_Onboarding_VirtuosVideoScreen_C_Tick::MyGeometry' has a wrong offset!");
static_assert(offsetof(WBP_Modern_Onboarding_VirtuosVideoScreen_C_Tick, InDeltaTime) == 0x000038, "Member 'WBP_Modern_Onboarding_VirtuosVideoScreen_C_Tick::InDeltaTime' has a wrong offset!");

// Function WBP_Modern_Onboarding_VirtuosVideoScreen.WBP_Modern_Onboarding_VirtuosVideoScreen_C.BP_GetDesiredFocusTarget
// 0x0008 (0x0008 - 0x0000)
struct WBP_Modern_Onboarding_VirtuosVideoScreen_C_BP_GetDesiredFocusTarget final
{
public:
	class UWidget*                                ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Modern_Onboarding_VirtuosVideoScreen_C_BP_GetDesiredFocusTarget) == 0x000008, "Wrong alignment on WBP_Modern_Onboarding_VirtuosVideoScreen_C_BP_GetDesiredFocusTarget");
static_assert(sizeof(WBP_Modern_Onboarding_VirtuosVideoScreen_C_BP_GetDesiredFocusTarget) == 0x000008, "Wrong size on WBP_Modern_Onboarding_VirtuosVideoScreen_C_BP_GetDesiredFocusTarget");
static_assert(offsetof(WBP_Modern_Onboarding_VirtuosVideoScreen_C_BP_GetDesiredFocusTarget, ReturnValue) == 0x000000, "Member 'WBP_Modern_Onboarding_VirtuosVideoScreen_C_BP_GetDesiredFocusTarget::ReturnValue' has a wrong offset!");

// Function WBP_Modern_Onboarding_VirtuosVideoScreen.WBP_Modern_Onboarding_VirtuosVideoScreen_C.CanEnter
// 0x0001 (0x0001 - 0x0000)
struct WBP_Modern_Onboarding_VirtuosVideoScreen_C_CanEnter final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Modern_Onboarding_VirtuosVideoScreen_C_CanEnter) == 0x000001, "Wrong alignment on WBP_Modern_Onboarding_VirtuosVideoScreen_C_CanEnter");
static_assert(sizeof(WBP_Modern_Onboarding_VirtuosVideoScreen_C_CanEnter) == 0x000001, "Wrong size on WBP_Modern_Onboarding_VirtuosVideoScreen_C_CanEnter");
static_assert(offsetof(WBP_Modern_Onboarding_VirtuosVideoScreen_C_CanEnter, ReturnValue) == 0x000000, "Member 'WBP_Modern_Onboarding_VirtuosVideoScreen_C_CanEnter::ReturnValue' has a wrong offset!");

// Function WBP_Modern_Onboarding_VirtuosVideoScreen.WBP_Modern_Onboarding_VirtuosVideoScreen_C.CanExit
// 0x0001 (0x0001 - 0x0000)
struct WBP_Modern_Onboarding_VirtuosVideoScreen_C_CanExit final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Modern_Onboarding_VirtuosVideoScreen_C_CanExit) == 0x000001, "Wrong alignment on WBP_Modern_Onboarding_VirtuosVideoScreen_C_CanExit");
static_assert(sizeof(WBP_Modern_Onboarding_VirtuosVideoScreen_C_CanExit) == 0x000001, "Wrong size on WBP_Modern_Onboarding_VirtuosVideoScreen_C_CanExit");
static_assert(offsetof(WBP_Modern_Onboarding_VirtuosVideoScreen_C_CanExit, ReturnValue) == 0x000000, "Member 'WBP_Modern_Onboarding_VirtuosVideoScreen_C_CanExit::ReturnValue' has a wrong offset!");

// Function WBP_Modern_Onboarding_VirtuosVideoScreen.WBP_Modern_Onboarding_VirtuosVideoScreen_C.DoesNeedEnterAnimation
// 0x0001 (0x0001 - 0x0000)
struct WBP_Modern_Onboarding_VirtuosVideoScreen_C_DoesNeedEnterAnimation final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Modern_Onboarding_VirtuosVideoScreen_C_DoesNeedEnterAnimation) == 0x000001, "Wrong alignment on WBP_Modern_Onboarding_VirtuosVideoScreen_C_DoesNeedEnterAnimation");
static_assert(sizeof(WBP_Modern_Onboarding_VirtuosVideoScreen_C_DoesNeedEnterAnimation) == 0x000001, "Wrong size on WBP_Modern_Onboarding_VirtuosVideoScreen_C_DoesNeedEnterAnimation");
static_assert(offsetof(WBP_Modern_Onboarding_VirtuosVideoScreen_C_DoesNeedEnterAnimation, ReturnValue) == 0x000000, "Member 'WBP_Modern_Onboarding_VirtuosVideoScreen_C_DoesNeedEnterAnimation::ReturnValue' has a wrong offset!");

// Function WBP_Modern_Onboarding_VirtuosVideoScreen.WBP_Modern_Onboarding_VirtuosVideoScreen_C.DoesNeedExitAnimation
// 0x0001 (0x0001 - 0x0000)
struct WBP_Modern_Onboarding_VirtuosVideoScreen_C_DoesNeedExitAnimation final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Modern_Onboarding_VirtuosVideoScreen_C_DoesNeedExitAnimation) == 0x000001, "Wrong alignment on WBP_Modern_Onboarding_VirtuosVideoScreen_C_DoesNeedExitAnimation");
static_assert(sizeof(WBP_Modern_Onboarding_VirtuosVideoScreen_C_DoesNeedExitAnimation) == 0x000001, "Wrong size on WBP_Modern_Onboarding_VirtuosVideoScreen_C_DoesNeedExitAnimation");
static_assert(offsetof(WBP_Modern_Onboarding_VirtuosVideoScreen_C_DoesNeedExitAnimation, ReturnValue) == 0x000000, "Member 'WBP_Modern_Onboarding_VirtuosVideoScreen_C_DoesNeedExitAnimation::ReturnValue' has a wrong offset!");

// Function WBP_Modern_Onboarding_VirtuosVideoScreen.WBP_Modern_Onboarding_VirtuosVideoScreen_C.ShouldBeSkiped
// 0x0001 (0x0001 - 0x0000)
struct WBP_Modern_Onboarding_VirtuosVideoScreen_C_ShouldBeSkiped final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Modern_Onboarding_VirtuosVideoScreen_C_ShouldBeSkiped) == 0x000001, "Wrong alignment on WBP_Modern_Onboarding_VirtuosVideoScreen_C_ShouldBeSkiped");
static_assert(sizeof(WBP_Modern_Onboarding_VirtuosVideoScreen_C_ShouldBeSkiped) == 0x000001, "Wrong size on WBP_Modern_Onboarding_VirtuosVideoScreen_C_ShouldBeSkiped");
static_assert(offsetof(WBP_Modern_Onboarding_VirtuosVideoScreen_C_ShouldBeSkiped, ReturnValue) == 0x000000, "Member 'WBP_Modern_Onboarding_VirtuosVideoScreen_C_ShouldBeSkiped::ReturnValue' has a wrong offset!");

}

