#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Modern_Onboarding_Gameplay

#include "Basic.hpp"

#include "WBP_Modern_Onboarding_Gameplay_classes.hpp"
#include "WBP_Modern_Onboarding_Gameplay_parameters.hpp"


namespace SDK
{

// Function WBP_Modern_Onboarding_Gameplay.WBP_Modern_Onboarding_Gameplay_C.BndEvt__WBP_Modern_Onboarding_Gameplay_ContinueButton_K2Node_ComponentBoundEvent_1_OnClick__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_Modern_Onboarding_Gameplay_C::BndEvt__WBP_Modern_Onboarding_Gameplay_ContinueButton_K2Node_ComponentBoundEvent_1_OnClick__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_Onboarding_Gameplay_C", "BndEvt__WBP_Modern_Onboarding_Gameplay_ContinueButton_K2Node_ComponentBoundEvent_1_OnClick__DelegateSignature");

	Params::WBP_Modern_Onboarding_Gameplay_C_BndEvt__WBP_Modern_Onboarding_Gameplay_ContinueButton_K2Node_ComponentBoundEvent_1_OnClick__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Modern_Onboarding_Gameplay.WBP_Modern_Onboarding_Gameplay_C.BP_OnHandleBackAction
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UWBP_Modern_Onboarding_Gameplay_C::BP_OnHandleBackAction()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_Onboarding_Gameplay_C", "BP_OnHandleBackAction");

	Params::WBP_Modern_Onboarding_Gameplay_C_BP_OnHandleBackAction Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_Modern_Onboarding_Gameplay.WBP_Modern_Onboarding_Gameplay_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_Modern_Onboarding_Gameplay_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_Onboarding_Gameplay_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Modern_Onboarding_Gameplay.WBP_Modern_Onboarding_Gameplay_C.ExecuteUbergraph_WBP_Modern_Onboarding_Gameplay
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Modern_Onboarding_Gameplay_C::ExecuteUbergraph_WBP_Modern_Onboarding_Gameplay(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_Onboarding_Gameplay_C", "ExecuteUbergraph_WBP_Modern_Onboarding_Gameplay");

	Params::WBP_Modern_Onboarding_Gameplay_C_ExecuteUbergraph_WBP_Modern_Onboarding_Gameplay Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Modern_Onboarding_Gameplay.WBP_Modern_Onboarding_Gameplay_C.GetDifficultyModeRow
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FModernSettingTableRow           Row                                                    (Parm, OutParm)

void UWBP_Modern_Onboarding_Gameplay_C::GetDifficultyModeRow(struct FModernSettingTableRow* Row)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_Onboarding_Gameplay_C", "GetDifficultyModeRow");

	Params::WBP_Modern_Onboarding_Gameplay_C_GetDifficultyModeRow Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Row != nullptr)
		*Row = std::move(Parms.Row);
}


// Function WBP_Modern_Onboarding_Gameplay.WBP_Modern_Onboarding_Gameplay_C.GetMissingStep
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             MissingText                                            (BlueprintVisible, BlueprintReadOnly, Parm)
// struct FModernSettingTableRow           ModernSettingTableRow                                  (Parm, OutParm)

void UWBP_Modern_Onboarding_Gameplay_C::GetMissingStep(const class FText& MissingText, struct FModernSettingTableRow* ModernSettingTableRow)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_Onboarding_Gameplay_C", "GetMissingStep");

	Params::WBP_Modern_Onboarding_Gameplay_C_GetMissingStep Parms{};

	Parms.MissingText = std::move(MissingText);

	UObject::ProcessEvent(Func, &Parms);

	if (ModernSettingTableRow != nullptr)
		*ModernSettingTableRow = std::move(Parms.ModernSettingTableRow);
}


// Function WBP_Modern_Onboarding_Gameplay.WBP_Modern_Onboarding_Gameplay_C.GetToggleAdaptiveTrigger
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FModernSettingTableRow           Row                                                    (Parm, OutParm)

void UWBP_Modern_Onboarding_Gameplay_C::GetToggleAdaptiveTrigger(struct FModernSettingTableRow* Row)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_Onboarding_Gameplay_C", "GetToggleAdaptiveTrigger");

	Params::WBP_Modern_Onboarding_Gameplay_C_GetToggleAdaptiveTrigger Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Row != nullptr)
		*Row = std::move(Parms.Row);
}


// Function WBP_Modern_Onboarding_Gameplay.WBP_Modern_Onboarding_Gameplay_C.GetToggleVibrationRow
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FModernSettingTableRow           Row                                                    (Parm, OutParm)

void UWBP_Modern_Onboarding_Gameplay_C::GetToggleVibrationRow(struct FModernSettingTableRow* Row)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_Onboarding_Gameplay_C", "GetToggleVibrationRow");

	Params::WBP_Modern_Onboarding_Gameplay_C_GetToggleVibrationRow Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Row != nullptr)
		*Row = std::move(Parms.Row);
}


// Function WBP_Modern_Onboarding_Gameplay.WBP_Modern_Onboarding_Gameplay_C.GetVibrationStrengthRow
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FModernSettingTableRow           Row                                                    (Parm, OutParm)

void UWBP_Modern_Onboarding_Gameplay_C::GetVibrationStrengthRow(struct FModernSettingTableRow* Row)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_Onboarding_Gameplay_C", "GetVibrationStrengthRow");

	Params::WBP_Modern_Onboarding_Gameplay_C_GetVibrationStrengthRow Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Row != nullptr)
		*Row = std::move(Parms.Row);
}


// Function WBP_Modern_Onboarding_Gameplay.WBP_Modern_Onboarding_Gameplay_C.InitFooter
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_Modern_Onboarding_Gameplay_C::InitFooter()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_Onboarding_Gameplay_C", "InitFooter");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Modern_Onboarding_Gameplay.WBP_Modern_Onboarding_Gameplay_C.InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_0
// (BlueprintEvent)
// Parameters:
// struct FInputActionValue                ActionValue                                            (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// float                                   ElapsedTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   TriggeredTime                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UInputAction*                     SourceAction                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_Modern_Onboarding_Gameplay_C::InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_0(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_Onboarding_Gameplay_C", "InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_0");

	Params::WBP_Modern_Onboarding_Gameplay_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_0 Parms{};

	Parms.ActionValue = std::move(ActionValue);
	Parms.ElapsedTime = ElapsedTime;
	Parms.TriggeredTime = TriggeredTime;
	Parms.SourceAction = SourceAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Modern_Onboarding_Gameplay.WBP_Modern_Onboarding_Gameplay_C.InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_1
// (BlueprintEvent)
// Parameters:
// struct FInputActionValue                ActionValue                                            (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// float                                   ElapsedTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   TriggeredTime                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UInputAction*                     SourceAction                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_Modern_Onboarding_Gameplay_C::InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_1(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_Onboarding_Gameplay_C", "InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_1");

	Params::WBP_Modern_Onboarding_Gameplay_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_1 Parms{};

	Parms.ActionValue = std::move(ActionValue);
	Parms.ElapsedTime = ElapsedTime;
	Parms.TriggeredTime = TriggeredTime;
	Parms.SourceAction = SourceAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Modern_Onboarding_Gameplay.WBP_Modern_Onboarding_Gameplay_C.InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_2
// (BlueprintEvent)
// Parameters:
// struct FInputActionValue                ActionValue                                            (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// float                                   ElapsedTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   TriggeredTime                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UInputAction*                     SourceAction                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_Modern_Onboarding_Gameplay_C::InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_2(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_Onboarding_Gameplay_C", "InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_2");

	Params::WBP_Modern_Onboarding_Gameplay_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_2 Parms{};

	Parms.ActionValue = std::move(ActionValue);
	Parms.ElapsedTime = ElapsedTime;
	Parms.TriggeredTime = TriggeredTime;
	Parms.SourceAction = SourceAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Modern_Onboarding_Gameplay.WBP_Modern_Onboarding_Gameplay_C.InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_3
// (BlueprintEvent)
// Parameters:
// struct FInputActionValue                ActionValue                                            (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// float                                   ElapsedTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   TriggeredTime                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UInputAction*                     SourceAction                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_Modern_Onboarding_Gameplay_C::InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_3(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_Onboarding_Gameplay_C", "InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_3");

	Params::WBP_Modern_Onboarding_Gameplay_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_ResetSettings_K2Node_EnhancedInputActionEvent_3 Parms{};

	Parms.ActionValue = std::move(ActionValue);
	Parms.ElapsedTime = ElapsedTime;
	Parms.TriggeredTime = TriggeredTime;
	Parms.SourceAction = SourceAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Modern_Onboarding_Gameplay.WBP_Modern_Onboarding_Gameplay_C.InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_4
// (BlueprintEvent)
// Parameters:
// struct FInputActionValue                ActionValue                                            (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// float                                   ElapsedTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   TriggeredTime                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UInputAction*                     SourceAction                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_Modern_Onboarding_Gameplay_C::InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_4(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_Onboarding_Gameplay_C", "InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_4");

	Params::WBP_Modern_Onboarding_Gameplay_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_4 Parms{};

	Parms.ActionValue = std::move(ActionValue);
	Parms.ElapsedTime = ElapsedTime;
	Parms.TriggeredTime = TriggeredTime;
	Parms.SourceAction = SourceAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Modern_Onboarding_Gameplay.WBP_Modern_Onboarding_Gameplay_C.InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_5
// (BlueprintEvent)
// Parameters:
// struct FInputActionValue                ActionValue                                            (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// float                                   ElapsedTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   TriggeredTime                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UInputAction*                     SourceAction                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_Modern_Onboarding_Gameplay_C::InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_5(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_Onboarding_Gameplay_C", "InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_5");

	Params::WBP_Modern_Onboarding_Gameplay_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_5 Parms{};

	Parms.ActionValue = std::move(ActionValue);
	Parms.ElapsedTime = ElapsedTime;
	Parms.TriggeredTime = TriggeredTime;
	Parms.SourceAction = SourceAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Modern_Onboarding_Gameplay.WBP_Modern_Onboarding_Gameplay_C.InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_6
// (BlueprintEvent)
// Parameters:
// struct FInputActionValue                ActionValue                                            (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// float                                   ElapsedTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   TriggeredTime                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UInputAction*                     SourceAction                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_Modern_Onboarding_Gameplay_C::InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_6(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_Onboarding_Gameplay_C", "InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_6");

	Params::WBP_Modern_Onboarding_Gameplay_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_6 Parms{};

	Parms.ActionValue = std::move(ActionValue);
	Parms.ElapsedTime = ElapsedTime;
	Parms.TriggeredTime = TriggeredTime;
	Parms.SourceAction = SourceAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Modern_Onboarding_Gameplay.WBP_Modern_Onboarding_Gameplay_C.InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_7
// (BlueprintEvent)
// Parameters:
// struct FInputActionValue                ActionValue                                            (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// float                                   ElapsedTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   TriggeredTime                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UInputAction*                     SourceAction                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_Modern_Onboarding_Gameplay_C::InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_7(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_Onboarding_Gameplay_C", "InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_7");

	Params::WBP_Modern_Onboarding_Gameplay_C_InpActEvt_IA_UI_Specific_OnboardingGeneric_Skip_K2Node_EnhancedInputActionEvent_7 Parms{};

	Parms.ActionValue = std::move(ActionValue);
	Parms.ElapsedTime = ElapsedTime;
	Parms.TriggeredTime = TriggeredTime;
	Parms.SourceAction = SourceAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Modern_Onboarding_Gameplay.WBP_Modern_Onboarding_Gameplay_C.LaunchEnterAnimation
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UWBP_Modern_Onboarding_Gameplay_C::LaunchEnterAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_Onboarding_Gameplay_C", "LaunchEnterAnimation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Modern_Onboarding_Gameplay.WBP_Modern_Onboarding_Gameplay_C.LaunchExitAnimation
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UWBP_Modern_Onboarding_Gameplay_C::LaunchExitAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_Onboarding_Gameplay_C", "LaunchExitAnimation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Modern_Onboarding_Gameplay.WBP_Modern_Onboarding_Gameplay_C.OnEnterAnimationEnded
// (BlueprintCallable, BlueprintEvent)

void UWBP_Modern_Onboarding_Gameplay_C::OnEnterAnimationEnded()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_Onboarding_Gameplay_C", "OnEnterAnimationEnded");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Modern_Onboarding_Gameplay.WBP_Modern_Onboarding_Gameplay_C.OnExit
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Forward                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Modern_Onboarding_Gameplay_C::OnExit(bool Forward)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_Onboarding_Gameplay_C", "OnExit");

	Params::WBP_Modern_Onboarding_Gameplay_C_OnExit Parms{};

	Parms.Forward = Forward;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Modern_Onboarding_Gameplay.WBP_Modern_Onboarding_Gameplay_C.OnExitAnimationEnded
// (BlueprintCallable, BlueprintEvent)

void UWBP_Modern_Onboarding_Gameplay_C::OnExitAnimationEnded()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_Onboarding_Gameplay_C", "OnExitAnimationEnded");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Modern_Onboarding_Gameplay.WBP_Modern_Onboarding_Gameplay_C.OnFocus
// (Event, Protected, BlueprintCallable, BlueprintEvent)

void UWBP_Modern_Onboarding_Gameplay_C::OnFocus()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_Onboarding_Gameplay_C", "OnFocus");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Modern_Onboarding_Gameplay.WBP_Modern_Onboarding_Gameplay_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Modern_Onboarding_Gameplay_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_Onboarding_Gameplay_C", "PreConstruct");

	Params::WBP_Modern_Onboarding_Gameplay_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Modern_Onboarding_Gameplay.WBP_Modern_Onboarding_Gameplay_C.Reset
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_Modern_Onboarding_Gameplay_C::Reset()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_Onboarding_Gameplay_C", "Reset");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Modern_Onboarding_Gameplay.WBP_Modern_Onboarding_Gameplay_C.ResetAllSettings
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_Modern_Onboarding_Gameplay_C::ResetAllSettings()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_Onboarding_Gameplay_C", "ResetAllSettings");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Modern_Onboarding_Gameplay.WBP_Modern_Onboarding_Gameplay_C.SaveAllSettings
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_Modern_Onboarding_Gameplay_C::SaveAllSettings()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_Onboarding_Gameplay_C", "SaveAllSettings");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Modern_Onboarding_Gameplay.WBP_Modern_Onboarding_Gameplay_C.SelectTitle
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_Modern_Onboarding_Gameplay_C::SelectTitle()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_Onboarding_Gameplay_C", "SelectTitle");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Modern_Onboarding_Gameplay.WBP_Modern_Onboarding_Gameplay_C.SetupDifficultyModeStep
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_Modern_Onboarding_Gameplay_C::SetupDifficultyModeStep()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_Onboarding_Gameplay_C", "SetupDifficultyModeStep");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Modern_Onboarding_Gameplay.WBP_Modern_Onboarding_Gameplay_C.SetupToggleAdaptiveTrigger
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_Modern_Onboarding_Gameplay_C::SetupToggleAdaptiveTrigger()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_Onboarding_Gameplay_C", "SetupToggleAdaptiveTrigger");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Modern_Onboarding_Gameplay.WBP_Modern_Onboarding_Gameplay_C.SetupToggleVibrationStep
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_Modern_Onboarding_Gameplay_C::SetupToggleVibrationStep()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_Onboarding_Gameplay_C", "SetupToggleVibrationStep");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Modern_Onboarding_Gameplay.WBP_Modern_Onboarding_Gameplay_C.SetupVibrationStrengthSlider
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_Modern_Onboarding_Gameplay_C::SetupVibrationStrengthSlider()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_Onboarding_Gameplay_C", "SetupVibrationStrengthSlider");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Modern_Onboarding_Gameplay.WBP_Modern_Onboarding_Gameplay_C.This Is For Plugin Compliance
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    NewParam                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Modern_Onboarding_Gameplay_C::This_Is_For_Plugin_Compliance(bool NewParam)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_Onboarding_Gameplay_C", "This Is For Plugin Compliance");

	Params::WBP_Modern_Onboarding_Gameplay_C_This_Is_For_Plugin_Compliance Parms{};

	Parms.NewParam = NewParam;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Modern_Onboarding_Gameplay.WBP_Modern_Onboarding_Gameplay_C.BP_GetDesiredFocusTarget
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UWidget* UWBP_Modern_Onboarding_Gameplay_C::BP_GetDesiredFocusTarget() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_Onboarding_Gameplay_C", "BP_GetDesiredFocusTarget");

	Params::WBP_Modern_Onboarding_Gameplay_C_BP_GetDesiredFocusTarget Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_Modern_Onboarding_Gameplay.WBP_Modern_Onboarding_Gameplay_C.CanBeSkiped
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UWBP_Modern_Onboarding_Gameplay_C::CanBeSkiped() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_Onboarding_Gameplay_C", "CanBeSkiped");

	Params::WBP_Modern_Onboarding_Gameplay_C_CanBeSkiped Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_Modern_Onboarding_Gameplay.WBP_Modern_Onboarding_Gameplay_C.CanEnter
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UWBP_Modern_Onboarding_Gameplay_C::CanEnter() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_Onboarding_Gameplay_C", "CanEnter");

	Params::WBP_Modern_Onboarding_Gameplay_C_CanEnter Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_Modern_Onboarding_Gameplay.WBP_Modern_Onboarding_Gameplay_C.CanExit
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UWBP_Modern_Onboarding_Gameplay_C::CanExit() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_Onboarding_Gameplay_C", "CanExit");

	Params::WBP_Modern_Onboarding_Gameplay_C_CanExit Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_Modern_Onboarding_Gameplay.WBP_Modern_Onboarding_Gameplay_C.DoesNeedEnterAnimation
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UWBP_Modern_Onboarding_Gameplay_C::DoesNeedEnterAnimation() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_Onboarding_Gameplay_C", "DoesNeedEnterAnimation");

	Params::WBP_Modern_Onboarding_Gameplay_C_DoesNeedEnterAnimation Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_Modern_Onboarding_Gameplay.WBP_Modern_Onboarding_Gameplay_C.DoesNeedExitAnimation
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UWBP_Modern_Onboarding_Gameplay_C::DoesNeedExitAnimation() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_Onboarding_Gameplay_C", "DoesNeedExitAnimation");

	Params::WBP_Modern_Onboarding_Gameplay_C_DoesNeedExitAnimation Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_Modern_Onboarding_Gameplay.WBP_Modern_Onboarding_Gameplay_C.GetFirstFocussableElement
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class UVAltarWidget*                    Widget                                                 (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_Modern_Onboarding_Gameplay_C::GetFirstFocussableElement(class UVAltarWidget** Widget) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Modern_Onboarding_Gameplay_C", "GetFirstFocussableElement");

	Params::WBP_Modern_Onboarding_Gameplay_C_GetFirstFocussableElement Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Widget != nullptr)
		*Widget = Parms.Widget;
}

}

